### ISSUE TITLE
failed to select an OpenTelemetry Instrumentation instance

### ISSUE THREAD

**Issue by Sorvatus** [open-telemetry/opentelemetry-operator#1004]
Hi all, 

we a trying to enable auto instrumentation for nodejs but we get always "failed to select an OpenTelemetry Instrumentation instance".

The operator, instrumentation crd, deployment are at same namespace.

-----
```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: nodejs-instrumentation
spec:
  exporter:
    endpoint: http://some-service:port
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
```
-----
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-own-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-own-operator
  template:
    metadata:
      labels:
        app: my-own-operator
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "monitoring/nodejs-instrumentation"
    spec:
      containers:
      - name: my-own-operator
        image: my-own-operator
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "128Mi"
            cpu: "500m"
```
-----

Logs from operator
```
{"level":"info","ts":1658829063.07036,"msg":"Starting the OpenTelemetry Operator","opentelemetry-operator":"0.56.0","opentelemetry-collector":"ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.56.0","opentelemetry-targetallocator":"ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:0.1.0","auto-instrumentation-java":"ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.11.1","auto-instrumentation-nodejs":"ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.27.0","auto-instrumentation-python":"ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.30b1","build-date":"2022-07-25T11:12:51Z","go-version":"go1.18.4","go-arch":"amd64","go-os":"linux","labels-filter":[]}
{"level":"info","ts":1658829063.0712924,"logger":"setup","msg":"watching namespace(s)","namespaces":"*"}
I0726 09:51:04.177701       1 request.go:601] Waited for 1.011083514s due to client-side throttling, not priority and fairness, request: GET:https://100.126.0.1:443/apis/scheduling.k8s.io/v1?timeout=32s
{"level":"info","ts":1658829064.586558,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":"127.0.0.1:8080"}
{"level":"info","ts":1658829064.5896792,"logger":"controller-runtime.builder","msg":"Registering a mutating webhook","GVK":"opentelemetry.io/v1alpha1, Kind=OpenTelemetryCollector","path":"/mutate-opentelemetry-io-v1alpha1-opentelemetrycollector"}
{"level":"info","ts":1658829064.5898952,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/mutate-opentelemetry-io-v1alpha1-opentelemetrycollector"}
{"level":"info","ts":1658829064.590005,"logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"opentelemetry.io/v1alpha1, Kind=OpenTelemetryCollector","path":"/validate-opentelemetry-io-v1alpha1-opentelemetrycollector"}
{"level":"info","ts":1658829064.590163,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-opentelemetry-io-v1alpha1-opentelemetrycollector"}
{"level":"info","ts":1658829064.590361,"logger":"controller-runtime.builder","msg":"Registering a mutating webhook","GVK":"opentelemetry.io/v1alpha1, Kind=Instrumentation","path":"/mutate-opentelemetry-io-v1alpha1-instrumentation"}
{"level":"info","ts":1658829064.590459,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/mutate-opentelemetry-io-v1alpha1-instrumentation"}
{"level":"info","ts":1658829064.5905726,"logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"opentelemetry.io/v1alpha1, Kind=Instrumentation","path":"/validate-opentelemetry-io-v1alpha1-instrumentation"}
{"level":"info","ts":1658829064.5906649,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-opentelemetry-io-v1alpha1-instrumentation"}
{"level":"info","ts":1658829064.5909274,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/mutate-v1-pod"}
{"level":"info","ts":1658829064.5910625,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1658829064.5912406,"logger":"controller-runtime.webhook.webhooks","msg":"Starting webhook server"}
{"level":"info","ts":1658829064.5915742,"msg":"Starting server","kind":"health probe","addr":":8081"}
{"level":"info","ts":1658829064.5915728,"msg":"Starting server","path":"/metrics","kind":"metrics","addr":"127.0.0.1:8080"}
I0726 09:51:04.591886       1 leaderelection.go:248] attempting to acquire leader lease monitoring/9f7554c3.opentelemetry.io...
{"level":"info","ts":1658829064.5920238,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":1658829064.5926023,"logger":"controller-runtime.webhook","msg":"Serving webhook server","host":"","port":9443}
{"level":"info","ts":1658829064.594896,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
{"level":"error","ts":1658829106.2243314,"msg":"failed to select an OpenTelemetry Instrumentation instance for this pod","namespace":"","name":"","error":"Instrumentation.opentelemetry.io \"nodejs-instrumentation\" not found","stacktrace":"github.com/open-telemetry/opentelemetry-operator/internal/webhookhandler.(*podSidecarInjector).Handle\n\t/workspace/internal/webhookhandler/webhookhandler.go:92\nsigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/webhook/admission/webhook.go:146\nsigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/webhook/admission/http.go:98\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/promhttp/instrument_server.go:40\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/promhttp/instrument_server.go:117\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/promhttp/instrument_server.go:84\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2462\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2916\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1966"}
```

we had also tested with 
instrumentation.opentelemetry.io/inject-nodejs: "nodejs-instrumentation"
instrumentation.opentelemetry.io/inject-nodejs: "true"

And i'm also surprise that the namespace and name are empty at log.
```  
failed to select an OpenTelemetry Instrumentation instance for this pod","namespace":"","name":""
```

Any advice, what i have forgot?
