### ISSUE TITLE
Webhook timout when creating an Instrumentation on GKE private cluster

### ISSUE THREAD

**Issue by CyberHippo** [open-telemetry/opentelemetry-operator#1009]
Hi,
When creating an `Instrumentation` resource on a private GKE cluster I encounter the following error:
```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "minstrumentation.kb.io": failed to call webhook: Post "https://opentelemetry-operator-webhook-service.opentelemetry-operator-system.svc:443/mutate-opentelemetry-io-v1alpha1-instrumentation?timeout=10s": context deadline exceeded
```
This issue is similar to [this issue about `ingress-nginx` on private GKE clusters](https://github.com/kubernetes/ingress-nginx/issues/6147) and is due to GCP firewall rules of private GKE clusters. 
I would suggest adding a note about it in the documentation (similarly to https://github.com/kubernetes/ingress-nginx/pull/5487) to help other users of this great operator.

## Steps to reproduce

Install the operator in an existing private GKE cluster where [`cert-manager` is installed](https://cert-manager.io/docs/installation/):
```bash
kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml
```
Once the `opentelemetry-operator` deployment is ready, create an OpenTelemetry Instrumentation resource:
```yaml
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
EOF
```

## Solution

You will need to either add a firewall rule that allows master nodes access to port `9443/tcp` on worker nodes, or change the existing rule that allows access to port `80/tcp`, `443/tcp` and `10254/tcp` to also allow access to port `9443/tcp`.

```bash
kubectl get endpoints --namespace opentelemetry-operator-system opentelemetry-operator-webhook-service
NAME                                     ENDPOINTS         AGE
opentelemetry-operator-webhook-service   10.56.6.98:9443   60m
```

I could open a PR to add a note in the operator documentation about this issue if needed.
