### ISSUE TITLE
Python Auto-Instrumentation permissions

### ISSUE THREAD

**Issue by edenkoveshi** [open-telemetry/opentelemetry-operator#1013]
Hi,
When setting up OTEL operator on Openshift and using python auto-instrumentation, I am getting the following error in the init container on all files:

[ **Note:** The automatic injection seems to work even with that error. I'm simply trying to understand that]

```
cp: can't preserve ownership of '/otel-auto-instrumentation/ ./<some-file>': Operation not permitted
```

My instrumentation YAML:
```yaml
kind: Instrumentation
apiVersion: opentelemetry.io/v1alpha1
metadata:
  name: instrumentation
spec:
  exporter:
    endpoint: <my-endpoint:4137>
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    image: <my-repo>/autoinstrumentation-python:0.30b1
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: <my-endpoint:4138>
  java:
   image: <java-image>
 nodejs:
   image: <nodejs-image>
```
The deployment is simply some python container I've made
This works quite well in my test environment (Kind kubernetes)
However on Openshift 4.8 I am getting the described error.
My guess is that it is related to the Pod Security Context being changed.

The modified pod on Openshift has the following properties:
```yaml
initContainers:
  - name: opentelemetry-auto-instrumentation
    securityContext:
      capabilities:
         drop:
           -  KILL
           -  MKNOD
           -  SETGUID
           -  SETUID
         runAsUser: 1000650000
securityContext:
  seLinuxOptions:
     level: 's0:c26,c0'
  fsGroup: 1000650000
containers:
  - name: myapp
    securityContext:
      capabilities:
       drop:
         -  KILL
         -  MKNOD
         -  SETGUID
         -  SETUID
      runAsUser: 1000650000
  - name: otc-container
    securityContext:
     capabilities:
       drop:
         -  KILL
         -  MKNOD
         -  SETGUID
         -  SETUID
     runAsUser: 1000650000
```
Any ideas on this?
Can the auto instrumentation container use the existing user & group or does it have to use SETUID,SETGUID permissions?
