### ISSUE TITLE
Set environment variables only not work

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-operator#1025]
I want Set environment variables without injection sdk, I use config below as a `Instrumentation`:
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: opentelemetry-autoinstrumentation
spec:
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python
  dotnet:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet
  env:
    - name: OTEL_SERVICE_NAME
      value: my-app
  sampler:
    type: always_on
```

the deployment with annotation:
```yaml
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: 'true'
```

after the Pod restart, I don't find the expect env in container object, is there some wrong in my config? By the way, I don't find any log about inject env in manager's container
