### ISSUE TITLE
Update default view ClusterRole when installing operator

### ISSUE THREAD

**Issue by bryan-aguilar** [open-telemetry/opentelemetry-operator#1047]
It would be nice if the default kubernetes [view](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles) role would get updated with `opentelemetry.io` resources at installation time. Cert-manager installation does this and it is a nice feature. Currently, an additional ClusterRole needs to be created so that these permissions get aggregated.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-operator-readonly
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: [opentelemetry.io]
  resources: ["instrumentations", "opentelemetrycollectors"]
  verbs: ["get", "list", "watch"] 
```

**Comment by jaronoff97** [comment]
I think this is done by the operator's [helm chart](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/templates/clusterrole.yaml). How are you currently installing the operator?

**Comment by bryan-aguilar** [comment]
Following the [getting-started](https://github.com/open-telemetry/opentelemetry-operator#getting-started) guide on the README.

**Comment by bryan-aguilar** [comment]
This is good info though, maybe the `getting-started` guide could be improved to call out the helm chart.

**Comment by bryan-aguilar** [comment]
So it doesn't look like the helm chart installation does what I was looking for @jaronoff97. Ideally I would like to have one `ClusterRoleBinding` (shown below) that grants read-only access to cluster resources. It binds to the default `view` ClusterRole mentioned in the original issue comment. 

Installing the helm chart does not aggregate these rules up to the default ClusterRole. Does this issue instead belong in the `helm-charts` repo? If so can someone transfer it, I would be happy to submit a PR adding this to the helm chart if this is something that the org would want. 

```
kind: ClusterRoleBinding
metadata:
  name: read-only
subjects:
- kind: Group
  name: dev-readonly
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
```
