### ISSUE TITLE
[bug] OpenTelemetryCollector reconcile loop panics

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-operator#1143]
It seems that the [last commit](https://github.com/open-telemetry/opentelemetry-operator/blob/10404ebe147630a070768f346a541524672700ec/pkg/collector/container.go#L171) on the main branch caused a panic to be triggered when logging. It should affect the planned [ v0.61.0](https://github.com/open-telemetry/opentelemetry-operator/pull/1131) release.

When applying this configuration:
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  mode: "deployment"
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
```

I get this output:
```golang
github.com/open-telemetry/opentelemetry-operator/pkg/collector.getConfigContainerPorts
        /home/frzifus/git/go/observability/opentelemetry-operator/pkg/collector/container.go:171
github.com/open-telemetry/opentelemetry-operator/pkg/collector.Container
        /home/frzifus/git/go/observability/opentelemetry-operator/pkg/collector/container.go:49
github.com/open-telemetry/opentelemetry-operator/pkg/collector.Deployment
        /home/frzifus/git/go/observability/opentelemetry-operator/pkg/collector/deployment.go:55
github.com/open-telemetry/opentelemetry-operator/pkg/collector/reconcile.Deployments
        /home/frzifus/git/go/observability/opentelemetry-operator/pkg/collector/reconcile/deployment.go:38
github.com/open-telemetry/opentelemetry-operator/controllers.(*OpenTelemetryCollectorReconciler).RunTasks
        /home/frzifus/git/go/observability/opentelemetry-operator/controllers/opentelemetrycollector_controller.go:165
github.com/open-telemetry/opentelemetry-operator/controllers.(*OpenTelemetryCollectorReconciler).Reconcile
        /home/frzifus/git/go/observability/opentelemetry-operator/controllers/opentelemetrycollector_controller.go:155
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /home/frzifus/git/golang_workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /home/frzifus/git/golang_workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /home/frzifus/git/golang_workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /home/frzifus/git/golang_workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234
```

---
