### ISSUE TITLE
OpenTelemetryCollectorReconciler errors related to replicas

### ISSUE THREAD

**Issue by Allex1** [open-telemetry/opentelemetry-operator#1182]
Running 0.60.0 operator deployed via the manifests provided.
My otelcol version is 0.62.1 and is defined as a deployment:
```
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: deployment
  labels:
    app: deployment-collector
spec:
  mode: deployment
  image: "otel/opentelemetry-collector:0.62.1"
  podAnnotations:
    test: test
  replicas: 1
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
...........................
```

Although the pod is created I get the following errors from the controller pod:

```
{"level":"error","ts":1666078045.97082,"logger":"controllers.OpenTelemetryCollector","msg":"failed to reconcile opentelemetry","error":"failed to update the scale subresource status for the OpenTelemetry CR: failed to get deployment status.replicas: Deployment.apps \"deployment-collector\" not found","stacktrace":"github.com/open-telemetry/opentelemetry-operator/controllers.(*OpenTelemetryCollectorReconciler).RunTasks\n\t/workspace/controllers/opentelemetrycollector_controller.go:166\ngithub.com/open-telemetry/opentelemetry-operator/controllers.(*OpenTelemetryCollectorReconciler).Reconcile\n\t/workspace/controllers/opentelemetrycollector_controller.go:155\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}


{"level":"error","ts":1666078045.970875,"msg":"Reconciler error","controller":"opentelemetrycollector","controllerGroup":"opentelemetry.io","controllerKind":"OpenTelemetryCollector","OpenTelemetryCollector":{"name":"deployment","namespace":"ns-team-app1"},"namespace":"ns-team-app1","name":"deployment","reconcileID":"684eae20-2f64-4126-add4-c879846201dc","error":"failed to update the scale subresource status for the OpenTelemetry CR: failed to get deployment status.replicas: Deployment.apps \"deployment-collector\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}
```

Seems some kind of naming mismatch between the `otelcol` CR and the actual deployment name `deployment-collector`
Also the controller runs in a different ns than the `otelcol` CR, but I think I reproduced it in the same ns as well.
