### ISSUE TITLE
Is it possible to build a customized opentelemetry-operator

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry-operator#1183]
We would like to use the contributed receiver and exporter in kubernetes. But I found the default opentelemetry collector which was defined in the yaml file is otel-collector, not otel-collector-contrib. 
Is there anyway to change the collector to the otel-collecotr-contrib? Is it possible that provide me a instruction or guide to customize the otel-operator yaml file?

**Comment by avadhut123pisal** [comment]
Hi @sweetxiaodai, you can set the collector container image to the `.spec.image` of OpenTelemetryCollector CR. 

For eg:

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  image: otel/opentelemetry-collector-contrib:0.51.0
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
```
