### ISSUE TITLE
Auto instrumentation for dotnet Error

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-operator#1190]
I install the opentelemetry-operator by helm and apply this :
```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
  namespace: insight-system
spec:
  java:
    image: your-customized-auto-instrumentation-image:java
  nodejs:
    image: your-customized-auto-instrumentation-image:nodejs
  python:
    image: your-customized-auto-instrumentation-image:python
  dotnet:
    image: your-customized-auto-instrumentation-image:dotnet
```

I get errors:
```
error validating "/private/var/folders/lf/x5ztzcnx6gs4qb2x9kyc_lg80000gn/T/82bb122d5a2048a6fa103f3bc8920198/resource.yaml": error validating data: ValidationError(Instrumentation.spec): unknown field "dotnet" in io.opentelemetry.v1alpha1.Instrumentation.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

env:
the operator chart version: 0.13.2
the operator image: v0.60.0

**Comment by pavolloffay** [comment]
The CR is not correct the images that you are showing are non-existent. 

Either remove the images or use one of the released ones https://github.com/orgs/open-telemetry/packages?repo_name=opentelemetry-operator 


Please re-open if there is another issue.

**Comment by Frapschen** [comment]
the error is no about image but `error validating data: ValidationError(Instrumentation.spec): unknown field "dotnet" in io.opentelemetry.v1alpha1.Instrumentation.spec`

I have tried with right image.

**Comment by pavolloffay** [comment]
I would suggest installing the operator via https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.61.0 and see if the issue is still there.

**Comment by Frapschen** [comment]
@pavolloffay  Problem still exist in my enviroment, steps to reproduce:
1. `helm upgrade opentelemetry-operator open-telemetry/opentelemetry-operator -n otel-operator --install --cleanup-on-fail --create-namespace`
```
kube-shell> helm list -n otel-operator
NAME                  	NAMESPACE    	REVISION	UPDATED                             	STATUS  	CHART                        	APP VERSION
opentelemetry-operator	otel-operator	1       	2022-12-01 20:14:53.525404 +0800 CST	deployed	opentelemetry-operator-0.19.2	0.63.1 
```

2. apply cr
```
kubectl apply -n otel-operator -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
  namespace: webstore-demo
spec:
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.20.2
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.31.0
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.35b0
  dotnet:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:0.5.0
EOF
```

then get the error:
```
error: error validating "STDIN": error validating data: ValidationError(Instrumentation.spec): unknown field "dotnet" in io.opentelemetry.v1alpha1.Instrumentation.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

I `grep` the schema of `instrumentations.opentelemetry.io` : 
`kube-shell> kubectl describe crd instrumentations.opentelemetry.io |grep dotnet` got nothing.
