### ISSUE TITLE
Increase resources / operator pod OOM

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#1191]
One customer of ours is experiencing OOM of the operator pod. 

The issue is happening in large clusters and they were able to get a stable operator deployment after increasing the memory to ~700 MB.  The memory stabilizes at around 450 MB (got via kubectl top). 

Applying `ENABLE_WEBHOOKS: false` didn't help the memory was fluctuating from 300-500 MB.

**Comment by pavolloffay** [comment]
Operator is currently using  https://github.com/open-telemetry/opentelemetry-operator/blob/main/bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml#L315-L321

```yaml
                resources:
                  limits:
                    cpu: 200m
                    memory: 256Mi
                  requests:
                    cpu: 100m
                    memory: 64Mi
```


For instance Jaeger operator is using https://github.com/jaegertracing/jaeger-operator/blob/main/bundle/manifests/jaeger-operator.clusterserviceversion.yaml#L424-L430


```yaml
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 100m
                    memory: 128Mi
```
