### ISSUE TITLE
.NET sidecard error when applaction start

### ISSUE THREAD

**Issue by sb185296** [open-telemetry/opentelemetry-operator#1195]
hi team ,

we did a POC with NodeJS and is working good
but when we add to our .NET Core 5.1 application

```
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: 'true'
        sidecar.opentelemetry.io/inject: 'true'
or
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: 'true'
        sidecar.opentelemetry.io/inject: 'false'
```
we get error and our app not start

```
 dotnet: symbol lookup error: /otel-auto-instrumentation/OpenTelemetry.AutoInstrumentation.Native.so: undefined symbol: pthread_cond_clockwait        
```
![image](https://user-images.githubusercontent.com/66299621/197342842-e2f04036-e948-47ec-9327-6fd69b9facc0.png)

![image](https://user-images.githubusercontent.com/66299621/197342861-0c0e48d0-98ae-4a9f-b829-679b9ac3f9d2.png)

if we runing only with , nothing is happends :\
```
      annotations:
        sidecar.opentelemetry.io/inject: 'true'
```

config:

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-sidecar
spec:
  mode: sidecar
  config: |
    receivers:
      jaeger:
        protocols:
          thrift_compact:
    processors:
    exporters:
      logging:
      jaeger:
        endpoint: "jaeger-collector.observability.svc:14250"   
        tls:
          insecure: true        
      zipkin:
        endpoint: "http://zipkin.observability.svc:9411/api/v2/spans"        
    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: []
          exporters: [logging,jaeger,zipkin]
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
spec:
  exporter:
    endpoint: http://otel-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
```

what are we missin ? we didnt able to find what are difrents

**Comment by sb185296** [comment]
we also add to our dockerfile this : https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/dotnet/Dockerfile

and add as ENV 

            - name: CORECLR_ENABLE_PROFILING
              value: '1'
            - name: CORECLR_PROFILER
              value: '{918728DD-259F-4A6A-AC2B-B85E1B658318}'
            - name: CORECLR_PROFILER_PATH
              value: /autoinstrumentation/OpenTelemetry.AutoInstrumentation.Native.so
            - name: DOTNET_STARTUP_HOOKS
              value: /autoinstrumentation/netcoreapp3.1/OpenTelemetry.AutoInstrumentation.StartupHook.dll
            - name: DOTNET_ADDITIONAL_DEPS
              value: /autoinstrumentation/AdditionalDeps
            - name: OTEL_DOTNET_AUTO_HOME
              value: /autoinstrumentation
            - name: DOTNET_SHARED_STORE
              value: /autoinstrumentation/store

![image](https://user-images.githubusercontent.com/66299621/197389054-8e9be81b-e76d-4b13-8b34-b931b884c6d1.png)

and same error :\

**Comment by Kielek** [comment]
Hi @sb185296,

I suppose that your issue could be related with the version of docker image you are trying to instrument. Could you please share you docker image details? Especially base image could be helpful.

> we also add to our dockerfile this : https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/dotnet/Dockerfile

This part should be injected by the opentelemetry-operator. It is not needed to do it manually.

**Comment by pellared** [comment]
My guess is that the container has too old glibc version (<2.30). I suggest updating to at least glibc 2.31.

**Comment by sb185296** [comment]
> Hi @sb185296,
> 
> I suppose that your issue could be related with the version of docker image you are trying to instrument. Could you please share you docker image details? Especially base image could be helpful.
> 
> > we also add to our dockerfile this : https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/dotnet/Dockerfile
> 
> This part should be injected by the opentelemetry-operator. It is not needed to do it manually.


FROM mcr.microsoft.com/dotnet/aspnet:.0 AS base
FROM mcr.microsoft.com/dotnet/sdk:.0-alpine AS build

**Comment by sb185296** [comment]
``

> glibc

ldd --version
ldd (Debian GLIBC 2.28-10+deb10u1) 2.28

let me update it and come back :)

**Comment by pellared** [comment]
Side note: if you would like to use an Alpine-based container then changing:

```
ADD https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/download/v$version/opentelemetry-dotnet-instrumentation-linux-glibc.zip .`
```

to

```
ADD https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/download/v$version/opentelemetry-dotnet-instrumentation-linux-glibc.zip .
```

should do the work. I am mentioning it as I see you are using .NET SDK on Alpine. Usually people do the other way - build on Ubuntu and deploy on Alpine 😉

**Comment by Kielek** [comment]
Auto Instrumentation for .NET is hosted under: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation
All tests application are available under: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/main/test/test-applications/integrations
You can find more under example folder: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/main/examples

The tests application are ready to be instrumented by AutoInstrumentation and does not have any reference to OpenTelemetry libraries.

**Comment by sb185296** [comment]
thanks for that

we looking on that
first we upgrade to .net6 to see if its fix the problem

thanks

**Comment by sb185296** [comment]
hi team ,

thanks for the help :)

we was getting error : 
```
warn    zapgrpc/zapgrpc.go:191    [core] [Server #3] grpc: Server.Serve failed to create ServerTransport: connection error: desc
```
i found this : https://github.com/open-telemetry/opentelemetry-operator/issues/862


and we change Instrumentation to that

```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    endpoint: http://localhost:4318/v1/traces
  propagators:
    - tracecontext
    - baggage
    #- b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"

```

and now its working with .Dotnet6

is that ok ? or we need to undrestand why GRPC not working ?
or its bug in the operator ?
