### ISSUE TITLE
Is there a way to provide the config in Instrumentation and OpenTelemetryCollector in the form of a configmap?

### ISSUE THREAD

**Issue by petrmac** [open-telemetry/opentelemetry-operator#1196]
Hello, 

I cannot find any way how to pass the config as a configmap rather than the inline `config`
```
config: |
    receivers:
      hostmetrics:
        collection_interval: 10s
        scrapers:
          cpu:
          load:
          memory:
...
```

Applies for both `Instrumentation` and `OpenTelemetryCollector`.

.. or am I just missing something?

Thx
