### ISSUE TITLE
Do not auto-create service account if an existing one is specified

### ISSUE THREAD

**Issue by csquire** [open-telemetry/opentelemetry-operator#1224]
**Problem:**
When ` serviceAccount` is set on an OpenTelemetryCollector, a service account based on the collector name still gets created even though it's unused. The extra serviceAccount is just noise and should not be created. From looking at the code, it appears a targetAllocator serviceAccount will also be auto-created by the operator when an existing serviceAccount is specified.

**Expected:**
No service accounts are auto-created when an existing serviceAccount is specified

**Actual:**
Service accounts are auto-created even if an existing one is specified

**To Reproduce:**
Create a service account, in my case I made an `opentelemetry-collector` SA
Apply a collector with a serviceAccount, I used the `simplest` collector below as a test

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
  namespace: opentelemetry
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
      telemetry:
        logs:
          level: info
          initial_fields:
            app: otel-collector
        metrics:
          level: detailed
          address: 0.0.0.0:8888

  resources:
    limits:
      memory: 500Mi
    requests:
      memory: 200Mi
      cpu: 200m
  serviceAccount: opentelemetry-collector
```
