### ISSUE TITLE
Documentation for restricted securityContext

### ISSUE THREAD

**Issue by jawnsy** [open-telemetry/opentelemetry-operator#1264]
Hello there,

Thanks so much for this great operator! The otel-collector sidecar and deployment seem to work fine with some more restrictive securityContext settings, and I'd like to propose adding documentation to describe how to implement this, as these changes would be especially relevant for people running in a restricted environment, such as OpenShift.

Since changing the defaults would be a breaking change, the safest option would be a doc-only change describing how this can be done. However, I think using more restrictive defaults would be a nice future change.

These are the settings I'm using for sidecars:

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
spec:
  mode: sidecar
  securityContext:
    runAsUser: 10001 # we use this in our environment, but should omit this for better compatibility with OpenShift, in which case clusters will inherit from the image USER
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL
```

And these are the settings I'm using for the deployment:

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
spec:
  mode: deployment
  securityContext:
    runAsUser: 10001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL
  podSecurityContext:
    runAsUser: 10001
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
```

Thanks for considering this!

See also:

* https://github.com/open-telemetry/opentelemetry-operator/issues/1262
* https://github.com/open-telemetry/opentelemetry-operator/issues/1084
* https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollector
