### ISSUE TITLE
Multi Traces same service name causes confusion

### ISSUE THREAD

**Issue by Kaitou786** [open-telemetry/opentelemetry-operator#1280]
Hi, I have some services running in multiple namespaces with different versions. I am collecting the traces and sending it to the jaeger backend. 

For example, I have  a deployment name `api` in namespaceA and in namespaceB

I have specific instrumentation object in both namespace and in both of them I have specified 

```
resource:
    addK8sUIDAttributes: true
    resourceAttributes:
      namespace: namespace
```

But in the jaeger UI there are traces merged and I see a single service there `api` which makes it challenging to know which trace is coming from which deployment.

is there any way to segregate these traces based on the namespace ?
