### ISSUE TITLE
OpenTelemetry `targetAllocator` component appears to include all endpoints in every job when using the `prometheusCR` setting

### ISSUE THREAD

**Issue by lukeplausin** [open-telemetry/opentelemetry-operator#1294]
Hi there, I am trying to configure OpenTelemetry to scrape Prometheus metrics via already existing `PodMonitor`/`ServiceMonitor` custom resource definitions.

It seems that when I deploy OpenTelemetry with the operator, the `targetAllocator` component does launch and it will return a list of Jobs when I hit the `/jobs` API endpoint of the allocator. However, the list of targets in each job seems to include every single endpoint in the cluster, including endpoints that are not part of the `ServiceMonitor`, and even including endpoints which are not even related to prometheus.

I am using chart version `0.19.1`, targetAllocator version `0.64.1`.

Relevant config from the `OpenTelemetryCollector` object:

```yaml
  targetAllocator:
    enabled: true
    prometheusCR:
      enabled: true
    # filterStrategy: relabel-config
    image: ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:0.64.1
```

When I hit the `/jobs` endpoint, select a job and then curl the endpoint for that job, the list of targets is enormous and includes basically every endpoint in the cluster. This causes open telemetry to try every single endpoint multiple times per service monitor per polling interval. Open Telemetry can't keep up and the data coming out of it is a mess.

The behaviour that I would expect is for each job to have one single target so that Open Telemetry only scrapes one endpoint per job.

Thanks

**Comment by jaronoff97** [comment]
Hello! Could you share one of the ServiceMonitor objects where you're seeing every endpoint in the cluster? The way that Prometheus pulls these targets is by using service discovery which is then filtered using a relabel configuration. If you're seeing endpoints unrelated to Prometheus this is expected. If you're seeing endpoints for a job that don't match anything related to your ServiceMonitor, that would be a different issue. Knowing your ServiceMonitor configuration would help us understand more here.

**Comment by sfc-gh-rscott** [comment]
@lukeplausin  I ran into the same thing. It was caused by not specifying `filterStrategy: relabel-config` on the `targetAllocator` config.

**Comment by Aneurysm9** [comment]
Should this be made the default filter?

**Comment by silverbp** [comment]
Was this never resolved, cause I'm having the same issue, setting filterStrategy: relabel-config doesn't resolve it. I only have one ServiceMonitor to just test this and it's from the k8s autoscaler helm chart.

**Comment by jaronoff97** [comment]
@silverbp could you share an example of this, as well as:
* collector version
* target allocator version
* operator version
* collector config

**Comment by silverbp** [comment]
operator image: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.70.0
target allocator image: ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:0.70.0
collector image: otel/opentelemetry-collector-contrib:0.71.0

I'm using the helm chart to install the controller with all default values.

I did have to manually create the service accounts and assign appropriate roles to it in k8s since the helm chart does not do that.

`apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: metrics
  namespace: monitoring
spec:
  mode: statefulset
  serviceAccount: ot-collector
  targetAllocator:
    enabled: true
    serviceAccount:  ot-target-allocator
    prometheusCR:
      enabled: true
      filterStrategy: relabel-config
  config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 10s
            static_configs:
            - targets: [ '0.0.0.0:8888' ]

    exporters:
      logging:
        verbosity: detailed

    service:
      pipelines:
        metrics:
          receivers: [ prometheus ]
          processors: []
          exporters: [ logging ]`

**Comment by jaronoff97** [comment]
Thank you for sharing your config, are there any logs or examples you can share of the target allocator including more endpoints than it should?

**Comment by silverbp** [comment]
If you monitor the detailed logs from the metric-collector, it's only logging metrics from this..

```
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 10s
            static_configs:
            - targets: [ '0.0.0.0:8888' ]
```

**Comment by silverbp** [comment]
is it only matching based on the namespace selector from the ServiceMonitor? It seems to be pulling everything from that namespace which is kube-system, so there's a lot in there.

```
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: autoscaler
      app.kubernetes.io/name: aws-cluster-autoscaler
```
