### ISSUE TITLE
[target-allocator] generates empty configmap for collectors.

### ISSUE THREAD

**Issue by FuyuanChu** [open-telemetry/opentelemetry-operator#1299]
I'm trying to deploy opentelemetry collectors using the opentelemetry operator to scrape Prometheus metrics and send metrics to remote storage using `prometheusremotewrite` exporter.

It worked when I used the most simple config. Just add scrap jobs to `prometheus` receiver and use `prometheusremotewrite` exporter to send metrics.

However, when I tried to set up the otel collector with `target allocator`, the `target allocator` didn't generate a proper configmap for collectors.

The configmap generated by the `target allocator` is called `allocator-collector` and this configmap only has one key "collector.yaml' with an empty value. Since the configmap is incorrect, the collector pod keeps restarting.

I suppose the target allocator will create a configmap for collectors using `OpenTelemetryCollector.spec.config` with receivers replaced.

* Version  `ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.66.0`

* manifest
```yaml
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: allocator
spec:
  mode: statefulset
  replicas: 1
  serviceAccount: otel-collector-sa
  targetAllocator:
    enabled: true
    prometheusCR:
      enabled: false
      #  serviceMonitorSelector:
      #  "release": "kube-prometheus-stack"
    replicas: 1
    serviceAccount: otel-collector-sa
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 1Gi
  config: |
    exporters:
      prometheusremotewrite/monitoring-center:
        endpoint: http://vminsert.monitoring/insert/0/prometheus/api/v1/write
        tls:
          insecure: true
        resource_to_telemetry_conversion:
          enabled: true
    extensions:
      health_check: null
      zpages: null
    processors:
      batch: null
      memory_limiter:
        check_interval: 2s
        limit_mib: 1024
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: 30s
          scrape_configs:
          - enable_http2: true
            follow_redirects: true
            honor_timestamps: true
            job_name: cert-manager
            kubernetes_sd_configs:
            - enable_http2: true
              follow_redirects: true
              kubeconfig_file: ""
              namespaces:
                names:
                - monitoring
                own_namespace: false
              role: endpoints
            metrics_path: /metrics
            relabel_configs:
            - action: replace
              regex: (.*)
              replacement: $1
              separator: ;
              source_labels:
              - job
              target_label: __tmp_prometheus_job_name
            - action: keep
              regex: (controller);true
              replacement: $1
              separator: ;
              source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_component
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_component
            - action: keep
              regex: (cert-manager);true
              replacement: $1
              separator: ;
              source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_instance
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_instance
            - action: keep
              regex: (cert-manager);true
              replacement: $1
              separator: ;
              source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_name
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_name
            - action: keep
              regex: "9402"
              replacement: $1
              separator: ;
              source_labels:
              - __meta_kubernetes_pod_container_port_number
    service:
      extensions:
      - health_check
      - zpages
      pipelines:
        metrics/monitoring-center:
          exporters:
          - prometheusremotewrite/monitoring-center
          processors:
          - memory_limiter
          - batch
          receivers:
          - prometheus
      telemetry:
        metrics:
          address: 0.0.0.0:8889
```
