### ISSUE TITLE
Operator configured service port names do not match istio convention

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-operator#1306]
### Additional information
ServicePort names generated by the operator are not compatible with the [istio naming convention](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection). This leads to problems when using gRPC. Envoy (istio sidecar) uses the port name to determine the protocol used. For example if TLS traffic is transmitted or not. According to convention, a port handling tls traffic should have the prefix `tls-` or `https-`. Alternatively, since kubernetes 1.20 a new field [appProtocol](https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol) in the servicePort can be used to provide protocol information.

### What is the problem?

Envoy as well as HAProxy [[#902](https://github.com/open-telemetry/opentelemetry-operator/issues/902#issuecomment-1142301232)] fail the tls handshake if it is unclear what type of traffic it is. We saw the same issue on the [jaeger-operator#2101](https://github.com/jaegertracing/jaeger-operator/pull/2101) project.
`authentication handshake failed: tls: first record does not look like a TLS handshake`

### How are port names generated?

Currently, these are generated based on the collector configuration (`${receiver}-${suffix}`). 

```yaml
# in this case, we have two ports, named: examplereceiver and examplereceiver-settings
receivers:
  examplereceiver:
    endpoint: 0.0.0.0:12345
  examplereceiver/settings:
    endpoint: 0.0.0.0:12346
```
In the case of otlp, it is only possible to use tls or grpc as prefix or appProtocol with a work around. Therefore the desired port name or protocol must be specified in the CR.

**Example**
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  mode: "deployment"
  ports:
    - name: grpc-otlp
      appProtocol: grpc
      port: 4317
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
```

### Possible solutions

One of the easiest ways to do this would be to reverse the orientation of the generated names. 
E.g.: `${receiver}-${info}` => `${info}-${receiver}`
However, this would be a breaking change. Since manually created ingress entries or similar would no longer work.

In the case of otlp, the configuration provides all the necessary information to use the `appProtocol` field. If the `insecure=false` it is tls traffic. In case of `insecure=true` the specified protocol can be used (e.g. gRPC or HTTP). However, I am not sure that all receivers provide these configurations.
