### ISSUE TITLE
dotnet Instrumentation with azuremonitor not show DB query

### ISSUE THREAD

**Issue by sb185296** [open-telemetry/opentelemetry-operator#1341]
hi all ,

we start work with Azure to see the metrics
but we don't see any query to database , is that somtting that not support any more ? we did POC 1.5 mounts ago and its works great with same code...

maybe do we need to add somting the the YMAL? we see that its was use
instrumentationlibrary.name | OpenTelemetry.SqlClient
but now its use 
instrumentationlibrary.name | OpenTelemetry.Instrumentation.AspNetCore

![image](https://user-images.githubusercontent.com/66299621/209584800-7aac9b76-447c-40da-a6d1-75c940ba2b9d.png)

![image](https://user-images.githubusercontent.com/66299621/209584256-cbeb246c-974f-4a80-b88e-14f4cd165f8d.png)

this take 1.5 mounts ago
![image](https://user-images.githubusercontent.com/66299621/209584568-10320ccb-263f-472d-9510-df5bcda57606.png)

![image](https://user-images.githubusercontent.com/66299621/209584402-ad2d0df0-318f-4e28-af31-5be478222b8d.png)

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  mode: sidecar
  image: otel/opentelemetry-collector-contrib-dev:latest
  config: |
    receivers:
      jaeger:
        protocols:
          thrift_compact:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      logging:
        loglevel: debug

      otlp:
        endpoint: oteld-collector.default.svc.cluster.local:4317
        tls:
          insecure: true
      jaeger:
        endpoint: "jaeger-collector.observability.svc:14250"   
        tls:
          insecure: true        
      zipkin:
        endpoint: "http://zipkin.observability.svc:9411/api/v2/spans"        

      azuremonitor:
        endpoint: "https://dc.services.visualstudio.com/v2/track"
        instrumentation_key: "56c905b"
        # maxbatchsize is the maximum number of items that can be
        # queued before calling to the configured endpoint
        maxbatchsize: 100
        # maxbatchinterval is the maximum time to wait before calling
        # the configured endpoint.
        maxbatchinterval: 10s
    service:
      pipelines:
        traces:
          receivers: [otlp,jaeger]
          processors: []
          exporters: [azuremonitor,logging,jaeger,zipkin]
          #exporters: [logging,jaeger,zipkin]

---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    #endpoint: http://localhost:4317
    endpoint: http://localhost:4318/v1/traces
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  dotnet:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:latest


```

what are we missing?

thanks

**Comment by Kielek** [comment]
Could you please share

- operator version
- .NET version of instrumented applications
- logs from the OpenTelemetry .NET Automatic Istrumentation. Typically stored by operator under `/var/log/opentelemetry/dotnet`

BTW the latest operator is using OpenTelemetry .NET Automatic Istrumentation v0.5.0. Please check changelog if you are affected by this https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/CHANGELOG.md#050

**Comment by sb185296** [comment]
hi ,
so yes we just flow with that change log :\ its was remove the mssql support out of the box

we are trying now to make it work with the latest veation.
is that correct ?

```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    #endpoint: http://localhost:4317
    endpoint: http://localhost:4318/v1/traces
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  dotnet:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:latest
  env:
    - name: "OTEL_DOTNET_AUTO_LOGS_ENABLED"
      value: "true"
    - name: "OTEL_DOTNET_AUTO_TRACES_ENABLED"
      value: "true" 
    - name: "OTEL_DOTNET_AUTO_METRICS_ENABLED"
      value: "true" 
    - name: "OTEL_DOTNET_AUTO_OPENTRACING_ENABLED"
      value: "true"      
```


we was able to mange to make it work with older verastion

kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.64.1/opentelemetry-operator.yaml   
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  mode: sidecar
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.66.0
  config: |
    receivers:
      jaeger:
        protocols:
          thrift_compact:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      logging:
        loglevel: debug

      otlp:
        endpoint: oteld-collector.default.svc.cluster.local:4317
        tls:
          insecure: true
      jaeger:
        endpoint: "jaeger-collector.observability.svc:14250"   
        tls:
          insecure: true        
      zipkin:
        endpoint: "http://zipkin.observability.svc:9411/api/v2/spans"        

      azuremonitor:
        endpoint: "https://dc.services.visualstudio.com/v2/track"
        instrumentation_key: "56cb"
        # maxbatchsize is the maximum number of items that can be
        # queued before calling to the configured endpoint
        maxbatchsize: 100
        # maxbatchinterval is the maximum time to wait before calling
        # the configured endpoint.
        maxbatchinterval: 10s
    service:
      pipelines:
        traces:
          receivers: [otlp,jaeger]
          processors: []
          exporters: [azuremonitor,logging,jaeger,zipkin]
          #exporters: [logging,jaeger,zipkin]

---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    #endpoint: http://localhost:4317
    endpoint: http://localhost:4318/v1/traces
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  dotnet:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:0.4.0-beta.1
```
