### ISSUE TITLE
The PodMutator for the Instrumentation injection modifies the env variables of the pod after it is created

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#1366]
## Issue description
When the `instrumentation.opentelemetry.io/inject-sdk` annotation is added to a Pod running in OpenShift, it is never started. `$ kubectl describe pod <pod name>` shows the following problem:
```sh
  Warning  ErrorAddingLogicalPort  60s (x2 over 60s)  controlplane       addLogicalPort failed for israel/my-deployment-with-sidecar-586cc47659-b7j9c: failed to set annotation on pod my-deployment-with-sidecar-586cc47659-b7j9c: Pod "my-deployment-with-sidecar-586cc47659-b7j9c" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds`, `spec.tolerations` (only additions to existing tolerations) or `spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
  core.PodSpec{
    Volumes:        {{Name: "kube-api-access-h294g", VolumeSource: {Projected: &{Sources: {{ServiceAccountToken: &{ExpirationSeconds: 3607, Path: "token"}}, {ConfigMap: &{LocalObjectReference: {Name: "kube-root-ca.crt"}, Items: {{Key: "ca.crt", Path: "ca.crt"}}}}, {DownwardAPI: &{Items: {{Path: "namespace", FieldRef: &{APIVersion: "v1", FieldPath: "metadata.namespace"}}}}}, {ConfigMap: &{LocalObjectReference: {Name: "openshift-service-ca.crt"}, Items: {{Key: "service-ca.crt", Path: "service-ca.crt"}}}}}, DefaultMode: &420}}}, {Name: "otc-internal", VolumeSource: {ConfigMap: &{LocalObjectReference: {Name: "sidecar-collector"}, Items: {{Key: "collector.yaml", Path: "collector.yaml"}}, DefaultMode: &420}}}},
    InitContainers: nil,
    Containers: []core.Container{
      {
        ... // 5 identical fields
        Ports:   nil,
        EnvFrom: nil,
        Env: []core.EnvVar{
          ... // 6 identical elements
          {Name: "OTEL_TRACES_SAMPLER", Value: "parentbased_traceidratio"},
          {Name: "OTEL_TRACES_SAMPLER_ARG", Value: "0.25"},
+         {
+           Name: "OTEL_RESOURCE_ATTRIBUTES_POD_NAME",
+           ValueFrom: &core.EnvVarSource{
+             FieldRef: &core.ObjectFieldSelector{APIVersion: "v1", FieldPath: "metadata.name"},
+           },
+         },
+         {
+           Name: "OTEL_RESOURCE_ATTRIBUTES_NODE_NAME",
+           ValueFrom: &core.EnvVarSource{
+             FieldRef: &core.ObjectFieldSelector{APIVersion: "v1", FieldPath: "spec.nodeName"},
+           },
+         },
          {
            Name: "OTEL_RESOURCE_ATTRIBUTES",
            Value: strings.Join({
              ... // 129 identical bytes
              "TTRIBUTES_NODE_NAME),k8s.pod.name=$(OTEL_RESOURCE_ATTRIBUTES_POD",
              "_NAME),k8s.replicaset.name=my-deployment-with-sidecar-586cc47659",
+             ",k8s.node.name=$(OTEL_RESOURCE_ATTRIBUTES_NODE_NAME),k8s.pod.nam",
+             "e=$(OTEL_RESOURCE_ATTRIBUTES_POD_NAME),k8s.pod.uid=44e10a4a-846c",
+             "-4877-8b84-3c5dbff8d580",
            }, ""),
            ValueFrom: nil,
          },
        },
        Resources:    {},
        VolumeMounts: {{Name: "kube-api-access-h294g", ReadOnly: true, MountPath: "/var/run/secrets/kubernetes.io/serviceaccount"}},
        ... // 12 identical fields
      },
      {Name: "otc-container", Image: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentele"..., Args: {"--config=/conf/collector.yaml"}, Ports: {{Name: "metrics", ContainerPort: 8888, Protocol: "TCP"}, {Name: "otlp-grpc", ContainerPort: 4317, Protocol: "TCP"}, {Name: "otlp-http", ContainerPort: 4318, Protocol: "TCP"}, {Name: "otlp-http-legac", ContainerPort: 55681, Protocol: "TCP"}}, ...},
    },
    EphemeralContainers: nil,
    RestartPolicy:       "Always",
    ... // 26 identical fields
  }

```

The instrumentation tries to modify the ENV in the container. [This issue](https://github.com/openshift/origin/issues/11093) confirms this is not allowed in OpenShift.

## Steps to reproduce
1. Create an OCP Cluster (4.11 in my case)
2. Build and deploy the OpenTelemetry Collector in the cluster
3. Create the OTEL Collector and the instrumentation applying this CRs:
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: sidecar
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: sdk-only
spec:
  env:
    - name: SPLUNK_TRACE_RESPONSE_HEADER_ENABLED
      value: "true"
  exporter:
    endpoint: http://localhost:4317
  propagators:
    - jaeger
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  nodejs:
    env:
      - name: OTEL_NODEJS_DEBUG
        value: "true"
  python:
    env:
      - name: OTEL_ENV_VAR
        value: "true"

```
4. Create the CR for the bussiness application:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-with-sidecar
spec:
  selector:
    matchLabels:
      app: my-pod-with-sidecar
  replicas: 1
  template:
    metadata:
      labels:
        app: my-pod-with-sidecar
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-sdk: "true"
    spec:
      securityContext:
        runAsUser: 1000740000
        runAsGroup: 1000740000
        fsGroup: 1000740000
      containers:
      - name: myapp
        image: ghcr.io/anuraaga/express-hello-world:latest
```

> **Warning** 
> You need to set the `runAsUser` and `runAsGroup` fields depending on the values of `openshift.io/sa.scc.uid-range` and `openshift.io/sa.scc.supplemental-groups:` annotations from your namespace.

> **Note**
> This is a modified version of the `instrumentation-sdk` E2E test.
