### ISSUE TITLE
grant default sa permissions to access openshift infrastructure api

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-operator#1387]
See: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16079

```
kubectl auth can-i get infrastructures/status --as=system:serviceaccount:testing:otel-col-preview-collector 
Warning: resource 'infrastructures' is not namespace scoped in group 'config.openshift.io'
no
```

**Comment by frzifus** [comment]
hm.. I have now started to play around with the permissions a bit and would like to hear your thoughts. @open-telemetry/operator-maintainers  @open-telemetry/operator-ta-maintainers 

By default, a collector has no permissions to query the openshift infrastructure API. However, this is required if you want to use the resourcedetection processor.

Adding a role like:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-collector-role
rules:
  - apiGroups:
      - 'config.openshift.io'
    resources:
      - infrastructures
    verbs:
      - get
      - watch
      - list
```
and creating a rolebinding would work. So we could install this role by default and handle the binding in the reconciler. But these are specific permissions for a certain component which are not always required.

Another and possibly cleaner solution would be to make the overwriting of the SA available in general and not only in the TA.
https://github.com/open-telemetry/opentelemetry-operator/blob/6814271a01588fac2df297bcd00b9c555fab252f/apis/v1alpha1/opentelemetrycollector_types.go#L194-L197
