### ISSUE TITLE
Instrumentation CRD's need to have resource settings - request/limit options

### ISSUE THREAD

**Issue by svadlakonda575** [open-telemetry/opentelemetry-operator#1407]
Hi Team,  we are facing an issue with auto instrumentation crd to copy the agent jar to application pod, when the pod comes up init container level resources are being taken from namespace defaults.. which is 8 cpu, 8GB memory .. causing resource issues, is there a way i can set up the limits in crd object. sample file applied.

```
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector:4317/
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: `"0.25"`
  python:
    env:
      # Required if endpoint is set to 4317.
      # Python autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4137.
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318/
EOF
```
