### ISSUE TITLE
Pods stuck in terminating state because of sdk injection

### ISSUE THREAD

**Issue by cdaguerre** [open-telemetry/opentelemetry-operator#1417]
The `instrumentation.opentelemetry.io/inject-sdk` annotation keeps job pods from being terminated.
As soon as I remove it, the pods disappear. 
The pods have the following finalizer:
```yaml
  finalizers:
  - batch.kubernetes.io/job-tracking
```
I couldn't find any related issue here and nothing helpful from the controller manager logs...

**Comment by edude03** [comment]
I have the same issue - I did see a related issue but looking for it at the moment. Basically it's because the operator is trying to modify the pod after it's been deployed already. Seems to have started since google upgrade us from 1.23.x -> 1.24.x

**Comment by man0s** [comment]
I've stumbled into the same issue.

**Comment by WesleyKlop** [comment]
What I see happening as well is that when I just try to remove the finalizer, the controller complains that I'm trying to edit immutable fields. These fields being the OTEL_* environment variables, which I think break because a pod that is being removed won't have a name/namespace but those are injected into the environment variable.

**Comment by fyuan1316** [comment]
I believe [#2584](https://github.com/open-telemetry/opentelemetry-operator/pull/2584) has addressed this issue.

You can follow the steps below to verify that the issue will not happen again.
Create a task with a run time of 1 minute and delete the pod while the task is running. the pod will not get stuck in a terminating state.

```yaml
# Apply Instrumentation
...

# annotate ns
kubectl annotate namespace otel-ext-1 instrumentation.opentelemetry.io/inject-java="true"

# Create Job
kubectl apply -f - <<EOF
apiVersion: batch/v1
kind: Job
metadata:
  name: pause-and-sleep-job
  namespace: otel-ext-1
spec:
  template:
    spec:
      containers:
      - name: pause-and-sleep
        image: busybox
        command: ["/bin/sh", "-c", "echo 'Pausing for 20 seconds...'; sleep 60; echo 'Task completed.'"]
      restartPolicy: Never

EOF
```
