### ISSUE TITLE
Competing replicaset when using args

### ISSUE THREAD

**Issue by edwintye** [open-telemetry/opentelemetry-operator#1460]
It would appear that using `spec.args` causes the operator to spin up `ReplicaSet` of all ordering/variant due to the way that the string array `args` does not enforce an order.  I have observed this in EKS v1.21, and have been able to replicate this in a local kind cluster for v1.21, v.1.22, and v1.25.  For example, if I use the following collector with the operator deployed using the official helm chart straight up:

```yaml
apiVersion: opentelemetry.io/v1alpha1
 kind: OpenTelemetryCollector
 metadata:
   name: otel
 spec:
   image: 'otel/opentelemetry-collector-contrib:0.69.0'
   args:
     feature-gates: +exporter.datadogexporter.metricexportnativeclient
   config: |
     receivers:
       otlp:
         protocols:
           grpc:
           http:
     processors:
 
     exporters:
       logging:
 
     service:
       pipelines:
         traces:
           receivers: [otlp]
           processors: []
           exporters: [logging]
```

then we can see that two sets of replica will spin up where one will be the dominant.  This may not happen every time as it does depend on how the array is arranged initially.  This is driven by the `Deployment` where the `revision` gets a bump whenever the operator wants to reconcile. To confirm, we can get the output via

```sh
kubectl get rs -o jsonpath='{range .items[*]}{.spec.template.spec.containers[0].args}'
# my output
➜ ["--config=/conf/collector.yaml","--feature-gates=+exporter.datadogexporter.metricexportnativeclient"]["--feature-gates=+exporter.datadogexporter.metricexportnativeclient","--config=/conf/collector.yaml"]
```
which shows that both ordering exists.

If we add the following test (to `pkg/collector/deployment_test.go`) representing  a minimal version of the config above, we can see that the test flip between pass and fail (probably bias to one side dependent for reasons beyond my understanding).

```golang
func TestDeploymentArgs(t *testing.T) {
    otelcol := v1alpha1.OpenTelemetryCollector{
       ObjectMeta: metav1.ObjectMeta{
          Name: "my-instance",
       },
       Spec: v1alpha1.OpenTelemetryCollectorSpec{
          Args: map[string]string{
             "feature-gates": "+random-feature",
          },
       },
    }
    cfg := config.New()
    d := Deployment(cfg, logger, otelcol)
    assert.Equal(t, "--config=/conf/collector.yaml", d.Spec.Template.Spec.Containers[0].Args[0])
    assert.Equal(t, "--feature-gates=+random-feature", d.Spec.Template.Spec.Containers[0].Args[1])
}
```

I haven't looked much further to see if there is a better way to use the crd or there is a quick fix in the operator itself.
