### ISSUE TITLE
Automatically add target_allocator section to prometheus receiver config if allocator is enabled

### ISSUE THREAD

**Issue by swiatekm-sumo** [open-telemetry/opentelemetry-operator#1581]
Since 0.62.0, [prometheus receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/README.md#opentelemetry-operator) allows us to directly query the target allocator for job definitions like so:

```yaml
receivers:
  prometheus:
    target_allocator:
      endpoint: http://my-targetallocator-service
      interval: 30s
      collector_id: collector-1
```

We should automatically add this configuration section to the prometheus receiver config if the allocator is enabled for a given Collector object. 

Right now we only add a `http_sd_config` with the allocator url to each [scrape job definition](https://github.com/open-telemetry/opentelemetry-operator/blob/eabe95a0abe6ae206987b51897983504f2edfb9f/pkg/collector/reconcile/config_replace.go#L65), which I think is unnecessary now that the receiver has direct support for the allocator.
