### ISSUE TITLE
ServiceMonitorSelector labels are not honored correctly

### ISSUE THREAD

**Issue by missourian55** [open-telemetry/opentelemetry-operator#1595]
I am facing this strange issue and here are the steps to reproduce the bug.

1. Deploy *two distinct collectors*, one with ```serviceMonitorSelector``` configuration and the other *without it*

2. Deploy a ```ServiceMonitor``` configuration without the  label attribute specified in the `serviceMonitorSelector`.

3. Both the collectors  logs shows that  *no targets have been registered*.

4. Add the label specified in the `serviceMonitorSelector` to the `ServiceMonitor` and redeploy.

5. Verify in the logs of both collectors that targets are registered on both the collectors, the one with serviceMonitorSelector and the collector without it. 

**One with ServiceMonitorSelector**

```yaml
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: adot-1
  namespace: default
spec:
  mode: statefulset
  serviceAccount: collector-sa
  targetAllocator:
    enabled: true
    serviceAccount: allocator-sa
    filterStrategy: relabel-config
    prometheusCR:
      enabled: true
      serviceMonitorSelector:
        env: production
  env:
    - name: KUBERNETES_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  config: |
    receivers:
      prometheus:
        target_allocator:
          endpoint: "http://adot-1-targetallocator"
          interval: 30s
          collector_id: ${POD_NAME}
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 1000s
            static_configs:
            - targets: [ '0.0.0.0:8888' ]
    
    processors:
      batch/metrics:
        timeout: 60s  

    exporters:
      logging:
        loglevel: debug

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch/metrics]
          exporters: [logging]
---
```

**One without ServiceMonitorSelector**

```yaml
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: adot-2
  namespace: default
spec:
  mode: statefulset
  serviceAccount: collector-sa
  targetAllocator:
    enabled: true
    serviceAccount: allocator-sa
    filterStrategy: relabel-config
    prometheusCR:
      enabled: true
  env:
    - name: KUBERNETES_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  config: |
    receivers:
      prometheus:
        target_allocator:
          endpoint: "http://adot-2-targetallocator"
          interval: 30s
          collector_id: ${POD_NAME}
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 1000s
            static_configs:
            - targets: [ '0.0.0.0:8888' ]
    
    processors:
      batch/metrics:
        timeout: 60s  

    exporters:
      logging:
        loglevel: debug
    
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch/metrics]
          exporters: [logging]
---
```

**Sample ServiceMonitor for testing**

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-monitor
  namespace: test
  labels:
    env: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-app
      app.kubernetes.io/version: 1.0
  namespaceSelector:
    matchNames:
      - test
  endpoints:
    - port: http
      path: /metrics
      interval: 20s
      scrapeTimeout: 10s
```
