### ISSUE TITLE
Specifying spec.image in otel collector causes error connecting Jaeger

### ISSUE THREAD

**Issue by xwgao** [open-telemetry/opentelemetry-operator#1596]
I installed OpenTelemetry operator 0.72.0 from OperatorHub in my OpenShift cluster and created an otel collector with spec  as below.
```
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      otlp/spanmetrics:
        protocols:
          grpc:
            endpoint: 0.0.0.0:12346

    processors:
      batch:
      spanmetrics:
        metrics_exporter: prometheus
        latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
        dimensions:
          - name: http.method
            default: GET
          - name: http.status_code
        dimensions_cache_size: 1000
        aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"

    exporters:
      logging:
      jaeger:
        endpoint: my-jaeger-collector-headless.jaeger-demo.svc:14250
        tls:
          ca_file: "/etc/pki/ca-trust/source/service-ca/service-ca.crt"
      prometheus:
        endpoint: "0.0.0.0:8889"
        metric_expiration: 1440m

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [spanmetrics, batch]
          exporters: [logging, jaeger]
        metrics/spanmetrics:
          receivers: [otlp/spanmetrics]
          exporters: [prometheus]
        metrics:
          receivers: [otlp/spanmetrics]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
  mode: statefulset
  volumeMounts:
    - mountPath: /etc/pki/ca-trust/source/service-ca
      name: cabundle-volume
  volumes:
    - configMap:
        name: my-otelcol-cabundle
      name: cabundle-volume
  image: 'otel/opentelemetry-collector-contrib:0.73.0'
```
I've enabled auto-instrumentation for my Node.js services and installed Jaeger (in jaeger-demo namespace). What I want is to export the auto-collected traces to Jaeger and export the span metrics (e.g. latency or error rate of services) to Prometheus.
Using spanmetrics processor, the traces would be converted into metrics automatically. To use the spanmetrics  processor which is only available in collector contrib, I set `spec.image` of the otel collector to be `otel/opentelemetry-collector-contrib:0.73.0`, but I found the following error from the otel collector pod log.
```
2023-03-20T04:42:14.974Z	warn	zapgrpc/zapgrpc.go:195	[core] [Channel #2 SubChannel #3] grpc: addrConn.createTransport failed to connect to {
  "Addr": "my-jaeger-collector-headless.jaeger-demo.svc:14250",
  "ServerName": "my-jaeger-collector-headless.jaeger-demo.svc:14250",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
}. Err: connection error: desc = "transport: Error while dialing: dial tcp: lookup my-jaeger-collector-headless.jaeger-demo.svc: i/o timeout{"grpc_log": true}
2023-03-20T04:42:15.976Z	info	jaegerexporter@v0.73.0/exporter.go:184	State of the connection with the Jaeger Collector backend	{"kind": "exporter", "data_type": "traces", "name": "jaeger", "state": "IDLE"}
```
Actually if removing the `spec.image: 'otel/opentelemetry-collector-contrib:0.73.0'`  from the otel collector to use the default image ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.72.0. This error would disappear and I was able to view the traces of my services on the Jaeger UI. But in that case I can not use spanmetrics processor. Actually even if I added `spec.image: 'ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.72.0'`  in my otel collector I got the same error.
Can anyone help on this? Thanks a lot.
