### ISSUE TITLE
expose otel grpc on openshift

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-operator#1616]
I had no success to get this up and running with by configuring the appProtocol as described here (https://github.com/open-telemetry/opentelemetry-operator/issues/902#issuecomment-1142301232).

>  A route that uses the default certificate cannot use HTTP/2 connectivity. 

That might be the issue: https://cloud.redhat.com/blog/grpc-or-http/2-ingress-connectivity-in-openshift

Openshift:
```
Server Version: 4.12.1
Kubernetes Version: v1.25.4+a34b9e9
```

Example:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: ingest-collector-grpc
spec:
  ports:
  - appProtocol: h2c
    name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tls-otel-collector-grpc
spec:
  host: otlp-grpc.apps.open-svc....
  port:
    targetPort: otlp-grpc
  tls:
    termination: edge
  to:
    kind: Service
    name: ingest-collector-grpc
    weight: 100
  wildcardPolicy: None

```

Exporing the service using the type `loadbalancer` might works - looking into that.
