### ISSUE TITLE
operator-opamp-bridge: fails to unmarshal  spec yaml with go-yaml 

### ISSUE THREAD

**Issue by dsobolev-nr** [open-telemetry/opentelemetry-operator#1687]
Hi,

The following spec fields

serviceAccount
upgradeStrategy
targetAllocator
(not sure if there are others)

are ignored when unmarshalling spec yaml:

https://github.com/open-telemetry/opentelemetry-operator/blob/6aa597790db904c78dbdb0a6afb132921814b9f9/cmd/operator-opamp-bridge/operator/client.go#L102

if I add corresponding yaml tags: 
```go
ServiceAccount string `json:"serviceAccount,omitempty" yaml:"serviceAccount,omitempty"`
```

https://github.com/open-telemetry/opentelemetry-operator/blob/6aa597790db904c78dbdb0a6afb132921814b9f9/apis/v1alpha1/opentelemetrycollector_types.go#L116 

it worked. 

go-yaml module requires explicit yaml tagging, so I can not explain how some spec fields (config, image, env, replicas etc) work. Please correct me where I can mistake here.

### How to reproduce

Use the following spec to update  collector's spec. We expect ```ServiceAccount``` to change in the Deployment description. But it does not.

```yaml
serviceAccount: some-service-account-name
config: |
  receivers:
    otlp:
      protocols:
        grpc:
        http:
  processors:
    memory_limiter:
      check_interval: 1s
      limit_percentage: 75
      spike_limit_percentage: 15
    batch:
      send_batch_size: 10000
      timeout: 10s

  exporters:
    logging:

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: []
        exporters: [logging]
```
