### ISSUE TITLE
Expose prometheusexporter port in collector pod

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#1689]
Use case: I want to use https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter to export pipeline's metrics  to prometheus by using the `podmonitor`. 
The `podmonitor` has config to set the port as string https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint.

When `prometheusexporter`  is enabled the port is not exposed as container port on the collector 

```yaml
    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889
```

```yaml
    name: otc-container
    ports:
    - containerPort: 8888
      name: metrics
      protocol: TCP
    - containerPort: 4317
      name: otlp-grpc
      protocol: TCP
    - containerPort: 4318
      name: otlp-http
      protocol: TCP
    - containerPort: 55681
      name: otlp-http-legac
      protocol: TCP
```
