### ISSUE TITLE
OpenTelemetryCollector fails if prometheus-operator is installed before opentelemetry-operator

### ISSUE THREAD

**Issue by andyjansson** [open-telemetry/opentelemetry-operator#1700]
When applying the OpenTelemetryCollector template:
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
```

if [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator) is installed before openetelemetry-operator, the application will fail with the following error:

```
Error from server (InternalError): error when creating ".\\opentelemetry-collector.yaml": Internal error occurred: failed calling webhook "[mopentelemetrycollector.kb.io](http://mopentelemetrycollector.kb.io/)": failed to call webhook: Post [https://opentelemetry-operator-webhook-service.opentelemetry-operator-system.svc:443/mutate-opentelemetry-io-v1alpha1-opentelemetrycollector?timeout=10s](https://opentelemetry-operator-webhook-service.opentelemetry-operator-system.svc/mutate-opentelemetry-io-v1alpha1-opentelemetrycollector?timeout=10s): context deadline exceeded
```

If opentelemetry-operator is installed before prometheus-operator, everything is fine.

I'm running kind 0.18 on Windows 10 with podman 4.4.4.
