### ISSUE TITLE
 Apache HTTPD auto-instrumentation docker image for arm64 mismatch arch

### ISSUE THREAD

**Issue by fdiskbrain** [open-telemetry/opentelemetry-operator#1724]
Apache HTTPD auto-instrumentation docker image for arm64 build with Apache HTTPD x64 libs. 
In build dockerfile [L12-15](https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/apache-httpd/Dockerfile#L12-L15)

```

...
RUN wget https://github.com/open-telemetry/opentelemetry-cpp-contrib/releases/download/webserver%2Fv$version/opentelemetry-webserver-sdk-x64-linux.tgz.zip
RUN unzip opentelemetry-webserver-sdk-x64-linux.tgz.zip
RUN mkdir agent
RUN tar -xvf opentelemetry-webserver-sdk-x64-linux.tgz -C agent
...
```

The action build and push arm64 images
```
....
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: autoinstrumentation/apache-httpd
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          build-args: version=${{ env.VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
...
```
https://github.com/open-telemetry/opentelemetry-operator/blob/main/.github/workflows/publish-autoinstrumentation-apache-httpd.yaml#L59
