### ISSUE TITLE
setting http_sd_config in the collector CRD causes the configmap to be empty

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#1742]
[Reported here](https://cloud-native.slack.com/archives/C033BJ8BASU/p1684178321289029). 

Setting the TA config block for the collector like so would cause the operator to fail to unmarshal the config now that we return the entire prometheus receiver configuration when creating the collector's configmap
```
...
target_allocator:
      endpoint: http://test-targetallocator:80
      interval: 30s
      collector_id: ${POD_NAME}
      http_sd_config:
        refresh_interval: 60s
...
```
