### ISSUE TITLE
Help with auto instrumentation 

### ISSUE THREAD

**Issue by sreejesh-radhakrishnan-db** [open-telemetry/opentelemetry-operator#1744]
Hi 
My limited knowledge on this subject than an issue. But not sure where else I could ask this. hence trying my luck here. 

I am following the https://opentelemetry.io/docs/k8s-operator/automatic/#create-an-opentelemetry-collector-optional , I could see Operator, Collector up and running in my cluster and  I annotated the  container too.  Still no trace/metric/log is been pushed to collector log nor on application container  log or to cloud trace. 

I can see the INIT CONTAINER IS starting up  and there is only one command " cp /javaagent.jar /otel-auto-instrumentation/javaagent.jar"

My Q - should I have to explicitly change the java command line for the application  to use this jar? if so how can I do that?

Should I add in my deployment something like this 
env:
        - name: JAVA_TOOL_OPTIONS
          value: /otel-auto-instrumentation/javaagent.jar

**Comment by rassmate** [comment]
You do not need to change JAVA_TOOL_OTIONS manually but you need to tell the injected agent where the collector is running.

I am doing this by applying this file to my cluster with operator
```yml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: autoinstrumentation
  namespace: observability
spec:
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
 
  java: 
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: <url-to-collector-here>
```
When the java agent is injected it is using this config
