### ISSUE TITLE
Support opentelemetry Javaagent extensions

### ISSUE THREAD

**Issue by dreaminghk** [open-telemetry/opentelemetry-operator#1758]
Hi everyone! We are looking into implement an custom propagator to propagate x-request-id for ISTIO as an opentelemetry extension.

As instructed in [this page](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension#build-and-add-extensions), we can implement that, built it as a jar and build a custom java instrumentation image that include that jar.

But the OpentelemetryOperator has to instruct the client to use it by adding -Dotel.javaagent.extensions

```
java -javaagent:path/to/opentelemetry-javaagent.jar \
     -Dotel.javaagent.extensions=build/libs/opentelemetry-java-instrumentation-extension-demo-1.0-all.jar
     -jar myapp.jar
```

I have tried something like the following in the **Instrumentation** Object:
```
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    env:
      - name: JAVA_TOOL_OPTIONS
        value: "$(JAVA_TOOL_OPTIONS) -Dotel.javaagent.extensions=build/libs/opentelemetry-java-instrumentation-extension-demo-1.0-all.jar"
```
However, only env names starting with OTEL_ and SPLUNK_ are supported. 

Does anyone has any idea on how to instruct the application to use a opentelemetry extension? Thank you!

**Comment by jaronoff97** [comment]
If you have a custom image with your code already, all you should need to do is change the java image in the instrumentation object rather than change the environment variables. ([docs](https://github.com/open-telemetry/opentelemetry-operator/blob/main/apis/v1alpha1/instrumentation_types.go#L113-L116))

example:

```
  java:
    image: <your-custom-image>:<tag>
```

**Comment by dreaminghk** [comment]
Thanks @jaronoff97 for your reply! In that case, looks like we will need to build the propagator into the OpenTelemetry Java Agent to produce a single jar file.

**Comment by pavolloffay** [comment]
Let's reopen this, as the java extension questions come up often. We should consider supporting it and document it. 

We can still require users to provide a custom image with java agent but additionally copy the extension as well and allow configuring it.

**Comment by crossoverJie** [comment]
```dockerfile
FROM busybox


ADD open-telemetry/opentelemetry-javaagent.jar /javaagent.jar

# Copy extensions to specify a path.
ADD open-telemetry/extensions/ext-1.0.0.jar /extensions/ext-1.0.0.jar

RUN chmod -R go+r /javaagent.jar
RUN chmod -R go+r /extensions/otel-extensions-pulsar-client-metrics-1.0.0.jar
```
---

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  java:
    image: custom-image:1.0.0
    extensions: /extensions
    env:
    # If extension.jar already exists in the container, you can only specify a specific path with this environment variable.
      - name: OTEL_EXTENSIONS_DIR
        value: /custom-dir
```

We can copy `extension.jar` to the specified directory in a custom image, and Operator will copy jars from the `${java.extensions}` directory to `/otel-auto-instrumentation/extension`.

JVM parameters will also be added to the `JAVA_TOOL_OPTIONS` environment variable: `-Dotel.javaagent.extensions=/otel-auto-instrumentation/extensions/extension.jar`.


At the same time, add an environment variable `OTEL_EXTENSIONS_DIR`, the default value of which can be `/otel-auto-instrumentation/extensions`.

If `extension.jar` already exists in the container, we can only specify a specific path with this environment variable.


Are there any other better solutions?

**Comment by crossoverJie** [comment]
> I need this as well and was working on a draft very similiar to @crossoverJie solution. Can a PR be opened?

I'm preparing a code implementation, and I'll submit a PR after it's done.

**Comment by pavolloffay** [comment]
@crossoverJie @cb645j does the extension jar has to be rebuilt for every javaagent release?

**Comment by pavolloffay** [comment]
I would prefer if the extension Jar would be separate from the auto-instrumentation image. 


I am thinking of something like this:

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  java:
    extensions:
      - image: pavolloffay/java-auto-instrumentation-extension1
        dir: /opt/java-extensions
```

The operator would create an init-container per extension and copy the content from `extensions.dir`  to a shared volume where the agent is copied as well and it would configure the ENV var to load the extension
