### ISSUE TITLE
is there a way to use opentelemetry-collector-contrib in opentelemetry-operator

### ISSUE THREAD

**Issue by Mahi-R7** [open-telemetry/opentelemetry-operator#1761]
So I am trying to use sigv4auth extension in the collector deployed using opentelemetry-operator, but it turned out that sigv4auth extension is not available in the collector deployed by opentelemetry-operator

is there a way I can use [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/sigv4authextension) in the opentelemetry-operator

**Comment by jverce** [comment]
@Mahi-R7 did you manage to solve this? I'm having the same issue, trying to use the StatsD receiver and the Datadog exporter.

**Comment by TylerHelmuth** [comment]
The solution is to pass the `--collector-image` flag with the collector image and version to the operator on startup.

**Comment by jverce** [comment]
Thanks @TylerHelmuth!

For those installing the operator using pure YAML, take a look at the [`.spec.image`](https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollectorspec) option:
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: foo
spec:
  image: otel/opentelemetry-collector-contrib
  # ...
```
