### ISSUE TITLE
How to limit sidecar's memory and cpu

### ISSUE THREAD

**Issue by Liubey** [open-telemetry/opentelemetry-operator#1766]
Sorry for pose a question.
I want to inject sidecar to the pods. But I'm confused how to limit resource at sidecar mode?
My config just like the example:
```
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: sidecar-for-my-app
spec:
  mode: sidecar
  config: |
    receivers:
      jaeger:
        protocols:
          thrift_compact:
    processors:

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: []
          exporters: [logging]
EOF
```

so how to limit it? Or only can protect pod by [memory limiter](https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiterprocessor/README.md)?
Thank you~
