### ISSUE TITLE
Cannot inject envs to targetAllocator

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-operator#1773]
We have several serviceMonitors, which are using environment variables, e.g:

```
spec:
  endpoints:
  - port: otelcol-metrics
  namespaceSelector:
    matchNames:
    - $(NAMESPACE)
  selector:
    matchLabels:
      sumologic.com/app: fluentd-metrics
      sumologic.com/scrape: "true"
```

It would be nice to add and support `env` in `targetAllocator` so we could seamlessly migrate from Prometheus to OpenTelemetry
