### ISSUE TITLE
Allow the overriding of the app name if its set as a label

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#1777]
Right now we set the label in the collector's meta as such:
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: garbage
  annotations:
...
  labels:
...
    app.kubernetes.io/name: example
```

But the operator overrides this without looking to be `garbage` instead of `example`. We should allow the user's specification to take precedence here.
