### ISSUE TITLE
Operator crashes when upgrading an OTEL Collector instance using the deprecated fields for HPA

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#1799]
The OpenTelemetry Operator crashes while upgrading one OpenTelemetry Collector instance from `0.63.1` to `0.78.0`. 

The issue appears when one of the collectors uses the `.spec.minReplicas` and `.spec.maxReplicas` to enable the HPA.

## Steps to reproduce:
1. Deploy OpenTelemetry Operator `0.63.1`:
    ```sh
    $ kubectl create -f https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.63.1/opentelemetry-operator.yaml
    ```
2. Deploy this CR:
    ```yaml
    apiVersion: opentelemetry.io/v1alpha1
    kind: OpenTelemetryCollector
    metadata:
      name: simplest
    spec:
      minReplicas: 1
      maxReplicas: 2
      autoscaler:
        behavior:
          scaleUp:
            stabilizationWindowSeconds: 10
          scaleDown:
            stabilizationWindowSeconds: 15
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 5m
          memory: 64Mi
    
      config: |
        receivers:
          otlp:
            protocols:
              grpc:
              http:
        processors:
    
        exporters:
          logging:
    
        service:
          pipelines:
            traces:
              receivers: [otlp]
              processors: []
              exporters: [logging]
     ```
3. Upgrade the OpenTelemetry Operator version:
    ```sh
   $ kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.78.0/opentelemetry-operator.yaml
    ```
4. Wait until the upgrade process is triggered in the operator
5. The operator crashes

## Operator log output
```
{"level":"info","ts":"2023-06-05T16:14:56.505136619Z","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"opentelemetrycollector","controllerGroup":"opentelemetry.io","controllerKind":"OpenTelemetryCollector","OpenTelemetryCollector":{"name":"simplest","namespace":"test"},"namespace":"test","name":"simplest","reconcileID":"b677a3ca-414c-4793-8987-46ba2a02c5b6"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25f361f]

goroutine 407 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:115 +0x1fa
panic({0x2b9b920, 0x4f371a0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/open-telemetry/opentelemetry-operator/pkg/collector.HorizontalPodAutoscaler({{0x3757560, 0xc0009a9530}, {{0x376fc08, 0xc000c40420}, 0x0}, {0xc000054500, 0x45}, {0xc0000545a0, 0x4a}, {0xc000054730, ...}, ...}, ...)
	/workspace/pkg/collector/horizontalpodautoscaler.go:147 +0xc3f
github.com/open-telemetry/opentelemetry-operator/pkg/collector/reconcile.HorizontalPodAutoscalers({_, _}, {{0x377c740, 0xc0004d9e60}, {0x376ac90, 0xc000a168c0}, 0xc0009fe150, {{0x376fc08, 0xc000842ba0}, 0x0}, ...})
	/workspace/pkg/collector/reconcile/horizontalpodautoscaler.go:41 +0xf8
github.com/open-telemetry/opentelemetry-operator/controllers.(*OpenTelemetryCollectorReconciler).RunTasks(_, {_, _}, {{0x377c740, 0xc0004d9e60}, {0x376ac90, 0xc000a168c0}, 0xc0009fe150, {{0x376fc08, 0xc000842ba0}, ...}, ...})
	/workspace/controllers/opentelemetrycollector_controller.go:223 +0x199
github.com/open-telemetry/opentelemetry-operator/controllers.(*OpenTelemetryCollectorReconciler).Reconcile(0xc000483520, {0x376c040, 0xc000842b70}, {{{0xc000ea14d8, 0x4}, {0xc000ea14d0, 0x8}}})
	/workspace/controllers/opentelemetrycollector_controller.go:211 +0x378
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x376c040?, {0x376c040?, 0xc000842b70?}, {{{0xc000ea14d8?, 0x28f51e0?}, {0xc000ea14d0?, 0x37577b8?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0003f2460, {0x376bf98, 0xc0003ea910}, {0x2d472a0?, 0xc000352280?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314 +0x377
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003f2460, {0x376bf98, 0xc0003ea910})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222 +0x587
```
