### ISSUE TITLE
Inject custom span attributes per deployment

### ISSUE THREAD

**Issue by soujiro32167** [open-telemetry/opentelemetry-operator#1861]
For a specific deployment, I'd like to add a span attribute that is not shared with others. For example

```yaml
  annotations:
    sidecar.opentelemetry.io/inject: "true"
    sidecar.opentelemetry.io/additional-otel-attributes: "foo=bar"
```
