### ISSUE TITLE
Nodejs instrumentation - Propagator "xray" requested through environment variable is unavailable.

### ISSUE THREAD

**Issue by ademar-prothon** [open-telemetry/opentelemetry-operator#1869]
We are unable to use the xray propagator on an auto-instrumented nodejs app.
Env : k8s on eks v 1.26.4

Instrumentation : 
```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: exchange-platform
  namespace: default
spec:
  exporter:
    endpoint: http://xray-collector-collector.default.svc.cluster.local:4318
  propagators:
    - xray
  sampler:
    type: always_on
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://xray-collector-collector.default.svc.cluster.local:4317
      - name: OTEL_LOG_LEVEL
        value: info
```
Error message : 
`Propagator "xray" requested through environment variable is unavailable.`

Any ideas ? Thanks !
