### ISSUE TITLE
[target allocator] Scraping endpoints which are not ready

### ISSUE THREAD

**Issue by cmergenthaler** [open-telemetry/opentelemetry-operator#1883]
Seems like the target allocator identifies endpoints that are not ready and therefore scraping the metrics endpoints from otel-collector fails with `dial tcp 10.244.206.14:8080: connect: connection refused`.

The underlying servicemonitor's endpoints has following notReadyAddresses:
``` yaml 
notReadyAddresses:
  - ip: 10.244.206.14
    nodeName: my-node
    targetRef:
      kind: Pod
      name: my-pod
```

I don't think that this should be expected.
