### ISSUE TITLE
[target allocator] Minimal example from README does not work

### ISSUE THREAD

**Issue by cmergenthaler** [open-telemetry/opentelemetry-operator#1891]
Using the feature flag `operator.collector.rewritetargetallocator` as stated in [README](https://github.com/open-telemetry/opentelemetry-operator#target-allocator-config-rewriting) only works if prometheus receiver config is valid. A minimal example with the following (cited from readme) does not work with an error:
`admission webhook "vopentelemetrycollectorcreateupdate.kb.io" denied the request: the OpenTelemetry Spec Prometheus configuration is incorrect, prometheus property in the configuration doesn't contain valid prometheus`

``` yaml
  config: |
    receivers:
      prometheus:

    exporters:
      logging:

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [logging]
```

What would be a valid minimal example when using the feature flag?

EDIT: Found the solution and updated the README in #1892
