### ISSUE TITLE
Hardening of OpenTelemetryCollector and otc-container

### ISSUE THREAD

**Issue by ugur99** [open-telemetry/opentelemetry-operator#1904]
Hello team,

We're using `opentelemetry-operator`, and at the same time we're implementing some pod/container hardening solutions such as [pod security standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/). But by default `opentelemetryCollector` resources don't have `securityContext` configurations, and we're looking for a solution to manipulate these specs when the operator creates the new resources. As far as I can see all these specs are hardoced and not sure if there is a way to harden them unless using a mutation webhook for `otc-container` or `opentelemetryCollector` resources.

I have read the thing about Go automatic instrumentation and it needs some privileges; but for others I think these features should either be able to be manipulated or should be hardened in code as much as possible.

```
0s          Warning   FailedCreate        replicaset/some-deployment-5968db8c99   (combined from similar events): Error creating: pods "some-deployment-5968db8c99-wdsdr" is forbidden: violates PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "otc-container" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "otc-container" must set securityContext.capabilities.drop=["ALL"])
```

Default open telemetry collector resource settings:
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  ...
  labels:
    app.kubernetes.io/managed-by: opentelemetry-operator
  name: development
  namespace: some-namespace
spec:
  config: |
    ...
  ingress:
    route: {}
  mode: sidecar
  ports:
  - name: metrics
    port: 8888
    protocol: TCP
    targetPort: 0
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
  targetAllocator:
    prometheusCR: {}
    resources: {}
  upgradeStrategy: automatic
status:
  version: 0.80.0
```
