### ISSUE TITLE
Resource settings behave differently on otel-collector and target-allocator

### ISSUE THREAD

**Issue by cmergenthaler** [open-telemetry/opentelemetry-operator#1914]
Currently, the resource settings in OpenTelemetryCollector CRD behave differently for otel-collector and target-allocator. For the latter, default values are set if not provided which makes it impossible to i.e. unset cpu limits. On the collector, no default values are set at all, which makes it easy to customize to the pods' needs.

The following example will result in different setups for otel-collector and target-allocator. TA will have a default cpu limit of 200m, collector will have an unset cpu limit.
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  mode: deployment
  resources:
    requests:
      cpu: 150m
      memory: 200Mi
    limits:
      memory: 500Mi
  targetAllocator:
    enabled: true
    resources:
      requests:
        cpu: 150m
        memory: 200Mi
      limits:
        memory: 500Mi
```

**Comment by Toaddyan** [comment]
Just tried to replicate the issue with the following config: 
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  mode: statefulset
  targetAllocator:
    serviceAccount: opentelemetry-targetallocator-sa
    enabled: true
    resources:
      requests:
        cpu: 150m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 500Mi

  resources:
    requests:
      cpu: 150m
      memory: 200Mi
    limits:
      memory: 500Mi
```
and running a describe on the pod is giving me the following: 
```
k describe pod simplest-targetallocator-d7c87fcf9-p4kpk | grep -A 5 Limit
    Limits:
      memory:  500Mi
    Requests:
      cpu:     150m
      memory:  200Mi
```
which suggests that there is an uncapped CPU.
Could you elaborate further on the issue? Having difficulty replicating this

**Comment by Toaddyan** [comment]
I ran a sample config with the following: 
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  mode: statefulset
  targetAllocator:
    serviceAccount: opentelemetry-targetallocator-sa
    enabled: true
    resources:
      requests:
        cpu: 150m
        memory: 200Mi
      limits:
        memory: 500Mi

  resources:
    requests:
      cpu: 150m
      memory: 200Mi
    limits:
      cpu: 200m
      memory: 500Mi
   ```
 From this, I am seeing 
 ```
 k describe pod simplest-targetallocator-d7c87fcf9-p4kpk | grep -A 10 Limit
    Limits:
      memory:  500Mi
    Requests:
      cpu:     150m
      memory:  200Mi
```
I am seeing an unset CPU which matches the config that I have set up. 
Maybe I am missing something,  could you elaborate on the bug?
