### ISSUE TITLE
Make the instrumentation-go E2E test work in OpenShift

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#1919]
The `instrumentation-go` E2E test cannot be passed in OpenShift. The `README.md` lists the following required permissions for the Golang auto-instrumentation:

```yaml
securityContext:
    capabilities:
     add:
     - SYS_PTRACE
    privileged: true
    runAsUser: 0
```

It is needed to grant those permissions in the OpenShift cluster while the test execution.
