### ISSUE TITLE
instrumentation java agent fails to connect collector on grpc port with tls

### ISSUE THREAD

**Issue by blackluck** [open-telemetry/opentelemetry-operator#1929]
Hello,

we try to configure opentelemetry-operators instrumentation in kubernetes to connect to a collector on default 4317 grpc port but with tls and java agents fail with these kind of errors:
[otel.javaagent 2023-07-17 14:03:24:673 +0000] [OkHttp https://opentelemetry-collector.telemetry.svc:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export spans. The request could not be executed. Full error message: unexpected end of stream on https://opentelemetry-collector.telemetry.svc:4317/...
and
[otel.javaagent 2023-07-17 14:03:00:487 +0000] [OkHttp https://opentelemetry-collector.telemetry.svc:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: java.net.SocketException: Broken pipe (Write failed)

Instrumentation spec is like this globally and this isn't works with java:
```
  env:
  - name: OTEL_EXPORTER_OTLP_CERTIFICATE
    value: /run/secrets/kubernetes.io/serviceaccount/ca.crt
  exporter:
    endpoint: https://opentelemetry-collector.telemetry.svc:4317
```
But If configure java to http/protobuf it works, instrumentation like this:
```
  java:
    env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: https://opentelemetry-collector.telemetry.svc:4318
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
```

collector receiver config (cert is created manually where issuer is the same CA as kubernetes CA, this way don't need to mount extra secret for certs in auto instrumented pods, just use the default k8s CA):
```
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
            tls:
              cert_file: /usr/share/collector-certs/tls.crt
              key_file: /usr/share/collector-certs/tls.key
              min_version: "1.2"
          http:
            endpoint: ${env:MY_POD_IP}:4318
            tls:
              cert_file: /usr/share/collector-certs/tls.crt
              key_file: /usr/share/collector-certs/tls.key
              min_version: "1.2"

```

Is this intended or what issue could cause this, that only http tls port works with java?

Thanks

**Comment by TylerHelmuth** [comment]
@blackluck to check if TLS is the culprit is there any chance this can be tested with insecure?

```yaml
exporter:
    endpoint: http://opentelemetry-collector.telemetry.svc:4317
```

```yaml
receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
            tls:
              cert_file: /usr/share/collector-certs/tls.crt
              key_file: /usr/share/collector-certs/tls.key
              min_version: "1.2"
```
