### ISSUE TITLE
Expose the metrics port according to the OTEL Collector config

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#1931]
If somebody creates an OpenTelemetry Collector instance with the following configuration:
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: deployment
spec:
  mode: deployment
  config: |
    ...
    service:
      telemetry:
        metrics:
          level: detailed
          address: 0.0.0.0:9090
      pipelines:
```

The `metrics` port endpoint will be `9090` instead of `8888` (the default one). The operator will expose the `8888` without taking into account the  user configuration:
https://github.com/open-telemetry/opentelemetry-operator/blob/56f5de94dd3f1f83ac7dbdba3b8b4a6379317b48/pkg/collector/reconcile/service.go#L197-L200

> **Note**
>  [This issue was created from this thread](https://github.com/open-telemetry/opentelemetry-operator/pull/1874#discussion_r1264034952).
