### ISSUE TITLE
Sidecar injection not working for pods created via Deployment

### ISSUE THREAD

**Issue by lwj** [open-telemetry/opentelemetry-operator#1960]
Hi, first off want to mention that I'm not sure what the cause of this issue is. I'm fairly confident it's not an issue with the operator itself as I haven't seen this reported anywhere else and it's a very basic use case that's been well documented and tested. It's likely a mis-configuration on my end but I've exhausted all debugging options I know of and I'm wondering if anyone else has seen this before or knows how I can look into this further.

I've tried deploying the operator from both the helm chart and the raw manifests and am seeing the same issue. When deploying a collector in sidecar mode, it seems to only inject the otc-container when deploying Pods directly. Any pods created via another resource (i.e. Deployment) won't have the injection applied.

My collector configuration:
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          http:
          grpc:
    processors:
      batch:
    exporters:
      logging:
      otlp:
        endpoint:<external-otlp-collector>
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp]
```

Pod configuration (works - otc-container is injected at runtime):
```
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  annotations:
    sidecar.opentelemetry.io/inject: "true"
spec:
  containers:
  - name: myapp
    image: jaegertracing/vertx-create-span:operator-e2e-tests
    ports:
    - containerPort: 8080
      protocol: TCP
```

Deployment configuration (doesn't work - otc-container isn't injected at runtime):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      containers:
      - name: myapp
        image: jaegertracing/vertx-create-span:operator-e2e-tests
        ports:
        - containerPort: 8080
          protocol: TCP
```

There's no logs from the operator when the Deployment pod is being spun up indicating it's even being processed at all, but it does seem to be hitting the mutating webhook in some capacity and timing out, as increasing the timeout results in a noticeable delay to the pod creation.

Does anyone have any ideas for what might be causing this, or any additional logging that can be switched on? Have tried setting the log level to debug in the operator, but it's still not giving me any useful information.

For reference, I'm running on v1.23, which is supported according to the matrix.

Many thanks.
