### ISSUE TITLE
Support prefix for OTEL environment variables in the Instrumentation CR

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#1962]
The Quarkus runtime is already instrumented with OpenTelemtry, however it overrides OpenTelemtry env variables by adding `QUARKUS_` prefix. Therefore the Quarkus app cannot be instrumented with the `Instrumentation` CR via `instrumentation.opentelemetry.io/inject-sdk: "true"`.

https://quarkus.io/guides/opentelemetry#quarkus-opentelemetry_configuration

**Comment by pavolloffay** [comment]
The proposal of this ticket is to add prefix configuration for the env variables added by the operator.

**Comment by brunobat** [comment]
That would be great. Thanks @pavolloffay

**Comment by yuriolisa** [comment]
Can I take this one?

**Comment by TylerHelmuth** [comment]
@pavolloffay instead of adding a new env prefix, could we remove the constraint?

**Comment by jaronoff97** [comment]
Closed by https://github.com/open-telemetry/opentelemetry-operator/pull/2768

**Comment by CaffeineDaemon** [comment]
I still struggle with using `instrumentation.opentelemetry.io/inject-sdk: "true"` with a quarkus app.
Sure, with the validation removed i can set all the OTEL environment variables myself with the QUARKUS_ prefix. But i am using the `Instrumentation` CR so i don't have to set all OTEL environment variables myself in the first place. I also can't use expansion to reference a variable like `OTEL_PROPAGATORS` like so:

```
spec:
  env:
  - name: QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT
    value: $(QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT)
  - name: QUARKUS_OTEL_PROPAGATORS
    value: $(OTEL_PROPAGATORS)
```
The variables are not expanded. Am i doing something wrong?
