### ISSUE TITLE
Image with digest causes labels validation error during reconcile (more than 63 characters)

### ISSUE THREAD

**Issue by tcoville-coveo** [open-telemetry/opentelemetry-operator#1982]
Using an image including a `sha256` digest such as `otel/opentelemetry-collector-contrib@sha256:c6671841470b83007e0553cdadbc9d05f6cfe17b3ebe9733728dc4a579a5b532`  or also `otel/opentelemetry-collector-contrib:0.81.0@sha256:c6671841470b83007e0553cdadbc9d05f6cfe17b3ebe9733728dc4a579a5b532` generates an error when creating the k8s resources:
```
{
  "level": "error",
  "ts": "2023-08-03T16:43:59Z",
  "msg": "Reconciler error",
  "controller": "opentelemetrycollector",
  "controllerGroup": "opentelemetry.io",
  "controllerKind": "OpenTelemetryCollector",
  "OpenTelemetryCollector":
    { "name": "simplest", "namespace": "observability" },
  "namespace": "observability",
  "name": "simplest",
  "reconcileID": "518684fc-8052-4cd4-9c95-437fde1b07b6",
  "error": 'failed to reconcile the expected configmaps: failed to create: ConfigMap "simplest-collector" is invalid: metadata.labels: Invalid value: "c6671841470b83007e0553cdadbc9d05f6cfe17b3ebe9733728dc4a579a5b532": must be no more than 63 characters',
  "stacktrace":
    "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226",
}

```

Looking at the stacktrace this is likely caused by the common labels set on all resources not accounting for the 63 char limit on the version: 
https://github.com/open-telemetry/opentelemetry-operator/blob/440f7a733ae09d8683b4d1af423231e52308ac19/internal/manifests/collector/labels.go#L50-L55

Here is a full example for reproduction:
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  image: otel/opentelemetry-collector-contrib:0.81.0@sha256:c6671841470b83007e0553cdadbc9d05f6cfe17b3ebe9733728dc4a579a5b532
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
```
