### ISSUE TITLE
Support sidecar injection in another pod namespace different from the otel colletor instance.

### ISSUE THREAD

**Issue by rubenvp8510** [open-telemetry/opentelemetry-operator#199]
If I have an OpenTelemetry collector on sidecar mode in one namespace (eg, test1) but want a pod on other namespace (test2) to be injected, this is not actually possible with the opentelemetry-operator.

Steps to reproduce:
1) Install opentelemetry-operator
2) Create namespace test1 `kubectl create namespace test1`
2) Create an opentelemetry collector instance mode=sidecar:

```
kubectl apply -n test1 -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  mode: sidecar
  config: |
    receivers:
      jaeger:
        protocols:
          grpc:
    processors:
      queued_retry:

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: [queued_retry]
          exporters: [logging]
EOF
```
3) Create a pod in namespace test1
```
kubectl apply -n test1 -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
  annotations:
    sidecar.opentelemetry.io/inject: "true"
spec:
  containers:
  - name: myapp
    image: jaegertracing/vertx-create-span:operator-e2e-tests
    ports:
      - containerPort: 8080
        protocol: TCP
EOF
```
4) Verify that sidecar is injected 
```
kubectl get pods -n test1
NAME    READY   STATUS              RESTARTS   AGE
myapp   0/2     ContainerCreating   0          14s
```

5) Create namespace test2 `kubectl create namespace test2`
6) Create pod on namespace `test2
````
kubectl apply -n test1 -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
  annotations:
    sidecar.opentelemetry.io/inject: "true"
spec:
  containers:
  - name: myapp
    image: jaegertracing/vertx-create-span:operator-e2e-tests
    ports:
      - containerPort: 8080
        protocol: TCP
EOF
```
7)Sidecar is not injected
```
kubectl get pods -n test2
NAME    READY   STATUS    RESTARTS   AGE
myapp   1/1     Running   0          5s
```
