### ISSUE TITLE
Latest release breaks collector autoscaler

### ISSUE THREAD

**Issue by cmergenthaler** [open-telemetry/opentelemetry-operator#2018]
After upgrading to the latest release 0.82.0, I have noticed that the operator scaled down my otel-collector to a replica number lower than the configured `autoscaler.minReplicas`. The underlying HPA keeps showing the minReplica count as the desired and current replica count and also shows following events:

```
invalid metrics (1 invalid out of 1), first error is: failed to get cpu resource metric value: 
failed to get cpu utilization: did not receive metrics for any ready pods 
```

My autoscaler is configured as following and the actual number of pods is 2:

```yaml
spec:
  autoscaler:
    minReplicas: 3
    maxReplicas: 6
```
Any ideas what could cause this issue?

**Comment by jaronoff97** [comment]
I tested v0.82.0 with the spec you provided and everything worked as expected. Are your collectors pods up and healthy? Do they have resource requests and limits set? 

<img width="1160" alt="Screenshot 2023-08-14 at 11 16 41 AM" src="https://github.com/open-telemetry/opentelemetry-operator/assets/10070047/e0de88c7-76a7-4154-acb1-1737741be100">
<img width="658" alt="Screenshot 2023-08-14 at 11 17 16 AM" src="https://github.com/open-telemetry/opentelemetry-operator/assets/10070047/002cef03-252d-49d6-b2a2-37b5402842ce">

**Comment by jaronoff97** [comment]
(the label is incorrect, but i'm running an otel-operator pod w/ version 0.82.0)

**Comment by cmergenthaler** [comment]
@jaronoff97 Thanks for having a look! So after updating from 0.80.0 to 0.82.0, one of my otel-collector gets terminated event though my hpa shows 3 current & desired pods.
 The remaining 2 pods are running fine and healthy. Yes I do have set cpu/memory requests and memory limit (no cpu limit).
My Pods:
<img width="578" alt="Bildschirmfoto 2023-08-16 um 08 14 10" src="https://github.com/open-telemetry/opentelemetry-operator/assets/377953/d27e38b9-c9aa-4064-a661-1f324f8384f0">
HPA (somehow it doesn't show the error from my original post anymore):
<img width="1225" alt="Bildschirmfoto 2023-08-16 um 08 14 39" src="https://github.com/open-telemetry/opentelemetry-operator/assets/377953/e54eaecc-4028-41cc-85c1-8138e04152fe">
Status of my opentelemetrycollector CR (note it says 2/2 replicas here even though the hpa desires 3):
<img width="1683" alt="Bildschirmfoto 2023-08-16 um 08 16 28" src="https://github.com/open-telemetry/opentelemetry-operator/assets/377953/3d6c779b-a2e8-412c-9dc2-1de3300d05f5">

I don't understand why the HPA says 3 replicas are running when the OpentelemetryCollector only displays 2 replicas

**Comment by jaronoff97** [comment]
This is indeed very very odd... The only thing I can imagine is happening is that the replicas: 2 is being set on the CRD which is somehow overriding what you have set for the HPA. Are there any logs from the operator?

**Comment by jaronoff97** [comment]
From a quick glance, i don't see anything that would be causing this in between the releases. But I'm going to do some more testing on my clusters to check this.

**Comment by cmergenthaler** [comment]
> This is indeed very very odd... The only thing I can imagine is happening is that the replicas: 2 is being set on the CRD which is somehow overriding what you have set for the HPA. Are there any logs from the operator?
 
When the operator scales down the otel-collector it logs the following:
```
  ~ k logs -n monitoring opentelemetry-operator-5475947c7b-lznrz
  { "level": "info","ts": "2023-08-17T06:21:02Z","logger": "collector-upgrade","msg": "no upgrade routines are needed for the OpenTelemetry instance","name": "otel","namespace": "monitoring","version": "0.82.0","latest": "0.61.0" }
  { "level": "info","ts": "2023-08-17T06:21:02Z","logger": "collector-upgrade","msg": "skipping upgrade for OpenTelemetry Collector instance","name": "otel","namespace": "monitoring" }
  { "level": "info","ts": "2023-08-17T06:21:02Z","logger": "instrumentation-upgrade","msg": "no instances to upgrade" }
  { "level": "info","ts": "2023-08-17T06:21:03Z","msg": "Starting workers","controller": "opentelemetrycollector","controllerGroup": "opentelemetry.io","controllerKind": "OpenTelemetryCollector","worker count": 1 }
  { "level": "debug","ts": "2023-08-17T06:21:03Z","logger": "events","msg": "OpenTelemetry Config changed - monitoring/otel-targetallocator","type": "Normal","object": { "kind": "ConfigMap","namespace": "monitoring","name": "otel-targetallocator","uid": "744996b4-0e66-4abe-8ccf-22b363952e50","apiVersion": "v1","resourceVersion": "515704176" },"reason": "ConfigUpdate " }
```

Here are also my settings for the OpenTelemetryCollector (without the config):
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  mode: statefulset
  autoscaler:
    minReplicas: 3
    maxReplicas: 6
  resources:
    requests:
      cpu: 900m
      memory: 800Mi
    limits:
      memory: 2Gi
  targetAllocator:
    enabled: true
    allocationStrategy: consistent-hashing
    replicas: 2
    resources:
      requests:
        cpu: 150m
        memory: 200Mi
      limits:
        cpu: 1000m
        memory: 500Mi
    filterStrategy: relabel-config
    prometheusCR:
      enabled: true
```
