### ISSUE TITLE
Collector with prometheus exporter create service monitor automatically

### ISSUE THREAD

**Issue by yunchi0921** [open-telemetry/opentelemetry-operator#2058]
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: default
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  mode: deployment
  ports:
    - name: promexporter
      port: 8889
      protocol: TCP

  observability:
    metrics:
      enableMetrics: true
    
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [prometheus]
```

I want to use OpenTelemetry SDK to send metrics to our existing Prometheus server. Above Yaml file is the collector that I created in my Kubernetes cluster.  There are two endpoints ( Collector metrics port 8888 & Custom metric 8889) that should bPrometheus should scrape on my understanding, I need a ServiceMontor to select service `otel-collector-collector` and `otel-collector-collector-monitoring` to discover /Metrics that I want to collect. Is there any configuration that can be set on collector CR?  Or do I need to set ServiceMonitor manually?

```
otel-collector-collector              ClusterIP   172.20.31.163   <none>        8889/TCP,4317/TCP,4318/TCP   116m
otel-collector-collector-headless     ClusterIP   None            <none>        8889/TCP,4317/TCP,4318/TCP   116m
otel-collector-collector-monitoring   ClusterIP   172.20.66.2     <none>        8888/TCP                     116m
```
