### ISSUE TITLE
Restart OTEL Collector on change to imported ConfigMap

### ISSUE THREAD

**Issue by lsolovey** [open-telemetry/opentelemetry-operator#2070]
We configure OTEL Collector to read specific sub-sets of configuration from the separate "imported" file, using `${file:...}` syntax (as documented [here](https://opentelemetry.io/docs/collector/configuration/#basics)).

The imported file is mounted as a volume from a separate ConfigMap. See the definition of OTEL Collector CRD below, simplified for clarity.

**The question is:** how do we force OTEL Collector to restart (or reload the config) upon any change to the imported ConfigMap?

Manual restart of OTEL Collector (`kubectl rollout restart`) doesn't work, as explained in this issue: https://github.com/open-telemetry/opentelemetry-operator/issues/1300

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otelcollector
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
    processors:
      # Tail sampling configuration is externalized in the separate ConfigMap
      tail_sampling: ${file:config/tail-sampling.yaml}
    exporters:
      logging: {}
    service:
      pipelines:
        traces:
          receivers:
          - otlp
          processors:
          - tail_sampling
          exporters:
          - logging
  volumeMounts:
  # Mount ConfigMap which contains tail-sampling.yaml
  - mountPath: /config
    name: tail-sampling-configmap
  volumes:
  # Mount ConfigMap which contains tail-sampling.yaml
  - configMap:
      name: tail-sampling
      optional: true
    name: tail-sampling-configmap
```

FYI we use "imported" files because different parts of OTEL Collector are configured by different teams with different release cycles. Hence, we want to split such parts of configuration into separate imported ConfigMaps, to allow teams working independently.
