### ISSUE TITLE
Collector update with sidecar mode is not rollout

### ISSUE THREAD

**Issue by maxime-menard** [open-telemetry/opentelemetry-operator#2078]
I created a resource OpenTelemetryCollector with sidecar mode :

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
spec:
  mode: sidecar
```

and I added the relevant annotation to the Deployment of my app :
```
spec:
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: "my-collector"
```

This is working perfectly, but if I do any change on the CR `my-collector`, I don't see the sidecar restarting automatically to pickup the change. If I recreate the pod, I can see that the sidecar is using the latest configuration from "my-collector".

I don't have the same issue if I am using a collector with deployment mode for example, as I can see the pod related to the collector restarting automatically with latest configuration.
