### ISSUE TITLE
Help on how to use targetAllocator with relabel_config

### ISSUE THREAD

**Issue by sfc-gh-akrishnan** [open-telemetry/opentelemetry-operator#2134]
I am trying to convert my open-telemetry config to work with target allocator. I use relabel_configs in my job definition in open-telemetry config. 

From the [API docs](https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollectorspectargetallocatorprometheuscr), I see:
```
FilterStrategy determines how to filter targets before allocating them among the collectors. The only current option is relabel-config (drops targets based on prom relabel_config).
```

This only seems to be a key-value pair and relabel-config is the only allowed value. However, how can I define my custom relabel_config definition? 

Sorry if the answer is obvious. I am trying to wrap my head around this, and seeking help as I get onboarded to both open-telemetry and target allocator as well.

It would also super helpful to understand how the config would change with and without the usage of serviceMonitorSelector / podMonitorSelector (I am assuming that targetAllocator can only be used in tandem with either service / pod monitor). Is there a way to use targetAllocator without them?

**Comment by sfc-gh-akrishnan** [comment]
I learnt a lot over night reading the docs. Sorry for the noise. 

To help the progeny:
1) Setting `FilterStrategy` to `relabel-config` says TA to apply the `relabel_config` of prom receiver to take effect
2) TA does not need serviceMonitorSelector or podMonitorSelector to be working

Sample config for me that worked:
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: service-tel
  namespace: system-metrics
  labels:
    app: service-tel
spec:
  replicas: 3
  mode: statefulset
  targetAllocator:
    image: ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:main
    enabled: true
    allocationStrategy: consistent-hashing
    filterStrategy: relabel-config
    serviceAccount: service-tel
  config: |
    receivers:
      prometheus:
        target_allocator:
          endpoint: http://service-tel-targetallocator
          interval: 20s
          collector_id: "${POD_NAME}"
        config:
          scrape_configs:
          - job_name: 'my-app-scrapper'
            scrape_interval: 30s
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              action: keep
              regex: my-app-1
            metric_relabel_configs:
            - source_labels: [custom_label]
              regex: custom_value_1
              action: keep

            static_configs:
            - targets: ['my-app-1-service:4311']

    exporters:
      logging:
        verbosity: detailed
      prometheus:
        endpoint: "0.0.0.0:9001"

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [prometheus]
```

My app.py that I used for testing:
```
import random
import time
from prometheus_client import start_http_server, Counter

custom_label_value = "custom_value"
some_counter = Counter(name="some_counter", documentation="Sample counter", labelnames=["custom_label"])
some_counter.labels(custom_label=custom_label_value + "_0")

def main() -> None:
    label_counter = 1
    while True:
        random_sleep_time = random.randint(1, 20)
        print(f"Sleeping for {random_sleep_time} seconds", flush=True)
        time.sleep(random_sleep_time)
        some_counter.labels(custom_label=custom_label_value + "_" + str(label_counter)).inc()
        label_counter = (label_counter + 1) % 4

if __name__ == "__main__":
    start_http_server(port=4311)
    main()
```

The dockerfile:
```
FROM python:3.10-slim

EXPOSE 4311

WORKDIR /app
COPY ./requirements.txt ./app.py .
RUN pip3 install -r ./requirements.txt

CMD ["python", "app.py"]
```

It's corresponding yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-1
  namespace: system-metrics
spec:
  replicas: 200
  selector:
    matchLabels:
      app: my-app-1
  template:
    metadata:
      labels:
        app: my-app-1
    spec:
      containers:
        - name: my-app-1
          image: 172.31.22.159:5001/otel-prom:latest
          imagePullPolicy: Always
          ports:
            - name: prom
              containerPort: 4311
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-1-service
  namespace: system-metrics
  labels:
    app: my-app-1-service
spec:
  selector:
    app: my-app-1
  ports:
    - name: app-metrics-endpoint
      port: 4311
```

Other references that helped me:
* https://trstringer.com/opentelemetry-prometheus-metrics/
* https://opentelemetry.io/docs/kubernetes/operator/target-allocator/
* https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollector
