### ISSUE TITLE
OpenTelemetryCollector CRD configMap for collector's configuration purposes

### ISSUE THREAD

**Issue by sfc-gh-akrishnan** [open-telemetry/opentelemetry-operator#2135]
Does OpenTelemetryCollector CRD allow for a configMap that can be mounted for collector's configuration purposes? If so, is there any example?

**Comment by pavolloffay** [comment]
No, the collector config has to be inlined in the CR 

```yaml
spec:
  mode: deployment
  config: | 
```
