### ISSUE TITLE
Cannot drop using relabel_configs with Target Allocator

### ISSUE THREAD

**Issue by stuart23** [open-telemetry/opentelemetry-operator#2235]
### Component(s)

target allocator

## Description

I am trying to filter out a bunch of metrics that we are pulling with the PrometheusCR service discovery. The following is our collector spec:

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-metrics
  namespace: otel-metrics
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    serviceAccount: opentelemetry-targetallocator-sa
    filterStrategy: relabel-config
    prometheusCR:
      enabled: true
  config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              regex: '(ack-iam-metrics-service|cluster-autoscaler|rds-exporter-service)'
              action: drop

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        send_timestamps: true
        metric_expiration: 180m

    service:
      pipelines:
        metrics:
          receivers:
          - prometheus
          processors: []
          exporters:
          - prometheus
```

## Steps to Reproduce

Deploy the above Otel collector in a cluster that has ServiceMonitor CRs for ack-iam-metrics-service, cluster-autoscaler & ds-exporter-service.

## Expected Result

Metrics from the named services should be dropped and not appear in the output.

## Actual Result

Metrics from these services are still appearing in the exporter.

### Kubernetes Version

1.24.16

### Operator version

v0.85

### Collector version

v0.85

### Environment information

Target Allocator launched with `--enable-prometheus-cr-watcher`

**Comment by jaronoff97** [comment]
Unfortunately, this isn't really how scrape configs or prometheus work. You'll need to apply these relabel config rules to your servicemonitors directly. [ex](https://github.com/prometheus-operator/prometheus-operator/blob/2fc4fafd8b4f9b8c41f5a7e395b80d29d3e1f299/Documentation/user-guides/running-exporters.md#relabeling-and-metric-relabeling)

**Comment by flenoir** [comment]
Hi, it's really disturbing because i understood same things that @stuart23 . Anyway, do you confirm that there's not a way to get rid of some servicemonitor or podmonitor through TargetAllocator config ?

**Comment by jaronoff97** [comment]
@flenoir what do you mean by "get rid of some sericemonitor or podmonitor"? If you mean apply a default relabel config to them, no because that's not how servicemonitor and podmonitor config generation works today, you would want to apply those relabel configs to each of your servicemonitors or podmonitors.

**Comment by flenoir** [comment]
@jaronoff97 thanks for reply. I finally found a way to filter my scraping using serviceMonitor Labels.  Now i want to remove some metrics coming from this serviceMonitor

here's an extract of my serviceMonitor config :
```
  targetAllocator:
    enabled: true
    serviceAccount: my_sa
    # allocationStrategy: "consistent-hashing"
    replicas: 2
    prometheusCR:
      enabled: true
      serviceMonitorSelector:
        release: plateforme
```

if i look into targetAllocator jobs, i see this jobs for example : 
```
  "serviceMonitor/kube-metriques-plateforme/plateforme-stack-kubelet/0": {
    "_link": "/jobs/serviceMonitor%2Fkube-metriques-plateforme%2Fplateforme-stack-kubelet%2F0/targets"
  },

```

Now, i want to remove some metrics,  i triedto edit my prometheus receiver using this config but it doesn't seem to work 

```
           - job_name: kube-metriques-plateforme/plateforme-stack-kubelet/0
             metric_relabel_configs:
             - source_labels: [__name__]
               regex: container.*
               action: drop
```

How can i point on this job in my scape_configs to remove a specific metric ?
