### ISSUE TITLE
Env variable substitution not working when using target allocator and custom scrape-config

### ISSUE THREAD

**Issue by cmergenthaler** [open-telemetry/opentelemetry-operator#2257]
### Component(s)

collector, target allocator

## Description
When using target allocator together with custom scrape configs, env variable substitution on the collector does not seem to work properly. 

## Steps to Reproduce
- Having a remote prometheus metrics endpoint, which should be scraped by custom scrape-config
- Scrape target in otel-collector is configured using env variables
- Env variables are set on otel-collector and target-allocator

``` yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: remotepromendpoint
          scheme: https
          basic_auth:
            username: "${env::USER_ENV}"
            password_file: /etc/my-mounted-password
          tls_config:
            insecure_skip_verify: true
          static_configs:
            - targets: [ "${env::URL_ENV}" ]
```

## Expected Result
Env variables are substituted by otel-collector and/or target-allocator

## Actual Result
Otel-collector tries to scrape `https://${env::URL_ENV}/metrics`

### Kubernetes Version

1.26.6

### Operator version

0.85.0

### Collector version

0.85.0
