### ISSUE TITLE
Target Allocator showing complete list of scrape config but not showing corresponding jobs in /jobs endpoint

### ISSUE THREAD

**Issue by owaisrehman** [open-telemetry/opentelemetry-operator#2353]
### Component(s)

collector, target allocator

### Describe the issue you're reporting

Hi
I am facing problems while configuring target allocator for service discovery.

I've deployed otel operator using following command in K8s cluster:
```console
 helm install -n monitoring --set manager.featureGates=operator.collector.rewritetargetallocator --set admissionWebhooks.certManager.enabled=false --set admissionWebhooks.certManager.autoGenerateCert=true opentelemetry-operator open-telemetry/opentelemetry-operator
```

After this, I've deployed following OpenTelemetryCollector CR:
```YAML
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: metrics-collector
  namespace: monitoring
spec:
  mode: "statefulset"
  replicas: 1
  targetAllocator:
    enabled: true
    filterStrategy: relabel-config
    prometheusCR: 
      enabled: true
  config: |
    receivers:
      # Collect own metrics
      prometheus:
        config:
          global:
            scrape_interval: '10s'
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 10s
            static_configs:
            - targets: ['0.0.0.0:8888']
        target_allocator:
          endpoint: http://metrics-collector-targetallocator
          interval: 30s
          collector_id: "${POD_NAME}"
    exporters:
      debug:
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [debug]
```
Cluster Role and Cluster Role Binding used are as follows:
```YAML
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: target-allocator-manager-role
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs: ["get", "list", "watch"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```
```YAML
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: target-allocator-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: target-allocator-manager-role
subjects:
- kind: ServiceAccount
  name: metrics-collector-collector
  namespace: monitoring
```
There are Service Monitor and Pod Monitor available in multiple namespaces and they are picked up correctly by Target Allocator (I know this by sending HTTP request to /scrape_configs endpoint of target allocator)
But when I query /jobs endpoint of target allocator, I only see a single job (job that correspond to the configuration that I've given in OpenTelemetryCollector CR as shown below:

![image](https://github.com/open-telemetry/opentelemetry-operator/assets/96227601/3e736057-eb6b-4037-aeb1-82083cc26c57)
 
I'm not sure what I am doing wrong.
Let me know if you need more specific details.
