### ISSUE TITLE
[Bug operator] Opentelemetry agent network is not well configured when mode is daemonSet

### ISSUE THREAD

**Issue by fabMrc** [open-telemetry/opentelemetry-operator#2357]
### Component(s)

operator

### What happened?

HI

When using Operator and apply a Opentelemetry collector using mode=daemonSet, hostNetwork=true and dnsPolicy is ClusterFirst.
It does not allow correct dns resolution for all service and pod inside the cluster.
For example loki.svc.cluster.local can not be resolved because using this network configuration, it relies on the underlying resolv.conf host and it does not be able to resolve a internal cluster recordset dns.
when using hostNetwork true the dnsPolicy must be ClusterFirstWhenHostNet. Currently it is the operator that control the network configuration and set any pod attributes according to mode property value

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: log-collector
  namespace: opentelemetry
spec:
  mode: daemonset
  serviceAccount: collector
```

result in a daemonSet pod configured as bellow:

```
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: k8s-worker-default2-apps-int-lb.k8s-apps-int-lb.foo.net
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: collector
```

### Kubernetes Version

1.27.0

### Operator version

0.88.0

### Collector version

0.88.0

### Additional context

Use of Official Operator Helm chart (0.42.2) and images by default included : 
```
  image:
    repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
    tag: v0.88.0
  collectorImage:
    repository: otel/opentelemetry-collector-contrib
    tag: 0.88.0
```

**Comment by yuriolisa** [comment]
@fabMrc, could you please confirm your OpentTelemetryCollector manifest because I have tested it with the `hostNetwork=true` , `mode: DaemonSet` and I got a `dnsPolicy: ClusterFirstWithHostNet`. 

```bash
kubectl get daemonsets.apps daemonset-test-collector
NAME                       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset-test-collector   1         1         1       1            1           <none>          3m57s
```
```bash
kubectl get daemonsets.apps daemonset-test-collector -o yaml | grep dnsPolicy
      dnsPolicy: ClusterFirstWithHostNet
```
- collector.yaml
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: daemonset-test
spec:
  hostNetwork: true
  mode: daemonset
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  config: |
    receivers:
      jaeger:
        protocols:
          grpc:
    processors:
    exporters:
      debug:
    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: []
          exporters: [debug]

```
