### ISSUE TITLE
Nginx autoinstrument fails for nginx-ingress pod

### ISSUE THREAD

**Issue by djluck** [open-telemetry/opentelemetry-operator#2366]
### Component(s)

instrumentation

## Description
When using nginx auto-instrumentation with nginx, pods fail to create with this error:
```
conditions:
  - lastTransitionTime: "2023-11-16T19:59:24Z"
    message: 'Pod "ingress-nginx-internal-controller-5f98f56d9d-w8k4k" is invalid:
      spec.initContainers[0].lifecycle: Forbidden: may not be set for init containers'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
```

Seems this issue may be related to another issue previously reported: https://github.com/open-telemetry/opentelemetry-operator/issues/1820 

## Steps to Reproduce
- opentelemetry-operator helm chart 0.41.0
- Add `instrumentation.opentelemetry.io/inject-nginx: monitoring/demo-nginx-instrumentation` to the nginx ingress helm chart 

## Expected Result
Auto-instrumentation works

## Actual Result
Fails with above error.

### Kubernetes Version

1.26.3

### Operator version

0.41.0

### Collector version

NA

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
