### ISSUE TITLE
Create the permissions requested by the resourcedetection processor from the operator

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#2393]
### Component(s)

operator

### Is your feature request related to a problem? Please describe.

The `resourcedetection` processor needs some extra permissions when enabled. For instance, for OpenShift, those permissions are:
```yaml
kind: ClusterRole
metadata:
  name: otel-collector
rules:
- apiGroups: ["config.openshift.io"]
  resources: ["infrastructures", "infrastructures/status"]
  verbs: ["get", "watch", "list"]
```

### Describe the solution you'd like

It would be great if we can create them automatically from the operator.
