### ISSUE TITLE
Introduce TargetAllocator CRD

### ISSUE THREAD

**Issue by swiatekm** [open-telemetry/opentelemetry-operator#2422]
### Component(s)

target allocator

### Describe the issue you're reporting

The Target Allocator subresource of the OpenTelemetryCollector CR has been growing in size over time, in particular due to various infrastructure-related attributes that users rightfully want to set for it. It’s time to split it into its own CRD, improving separation of concerns and reducing the size of the Collector CRD.

## Design

The TargetAllocator CRD should contain all the fields the Target Allocator subresource currently does, to begin with. We will later continue adding fields to it, while possibly deprecating some fields from the subresource. The subresource should always only contain a subset of the CRD fields. Internally, the operator will create a CRD based on the subresource, which is how we’ll maintain backwards compatibility.

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: TargetAllocator
metadata:
  name: example
spec:
  scrapeConfigs:
    - job_name: otel-collector
      scrape_interval: 10s
      static_configs:
      - targets:
        - 0.0.0.0:8888
        - 0.0.0.0:9999
  prometheusCR:
    enabled: true
  ..
```

### Relation to the Collector CR

A Collector can be configured to use a given target allocator by setting a label on the collector CR: 

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: TargetAllocator
metadata:
  name: example
  labels:
    opentelemetry.io/target-allocator: example
spec:
  config:
    receivers:
      prometheus:
  ...
```
Collectors and Target Allocators are independent, neither owns the other, and each can in principle run on their own. By establishing a connection between them, certain aspects of their configuration will change under the hood.

## Rollout

We should be able to roll out most of the necessary changes without any user-facing change:

1. Add the type definitions for the TargetAllocator CRD
2. Generate the TargetAllocator CR from the subresource
3. Use the generated TargetAllocator CR to generate target allocator manifests
4. Add webhooks for TargetAllocator without enabling them
5. Enable the webhooks and reconciliation for the TargetAllocator CR

**Comment by jaronoff97** [comment]
some thoughts:
* I think this should only be in v2 i.e. `apiVersion: opentelemetry.io/v1alpha2` This will let us take advantage of the work for #901 (embedding a common fields struct)
* Having this in v2 only would let us begin with some fields in the TA spec deprecated or removed
* I think there will need to be a reference from a target allocator to a collector. We should improve this not only for the TA but also for instrumentation by introducing a new type or field called "collectorRef" or something like that which the operator can validate and automatically set up the networking
* For the ownership of the CRD, I think we could set a controller reference from the collector to properly cascade a delete, what would happen if someone deletes their TA? 
* I don't think the relation needs to be bidirectional, it should be enough to infer the relationship from the TA to the collector by doing the validation i mentioned above. i.e. we get a request to reconcile a TA CRD at which point we validate the collector ref and then update the collector manifests (read: config) appropriately
* for the rollout plan, i blieve we would need to enable webhooks and reconciliation before we start generating the TA CR from the subresource, unless we wanted to support both the subresource and the CRD. I think we should only support one at a time so I think the rollout could go like this:

### Rollout
1. Add the type definitions for the TargetAllocator CRD
1. Use the generated TargetAllocator CR to generate target allocator manifests
1. Add webhooks for TargetAllocator without enabling them
1. Enable the webhooks and reconciliation for the TargetAllocator CR
1. Generate the TargetAllocator CR from the subresource

**Comment by pavolloffay** [comment]
> Wouldn't it be simpler to have an optional targetAllocatorRef field on the Collector CR

+1

**Comment by swiatekm-sumo** [comment]
I've thought about this a bit more, and I think I've arrived at a solution to the two-way binding problem. Our requirements are:
* The TargetAllocator CR should have some way of referring to a set of collector Pods
* The TargetAllocator should run even in the absence of said collectors, doing nothing
* It should be easy to have a TargetAllocator CR target Pods from a particular Collector CR

I propose that we use the standard label matching mechanism for this, and also provide a shortcut via an annotation.

To directly set a collector selector:

```yaml
apiVersion: opentelemetry.io/v1alpha2
kind: TargetAllocator
metadata:
  name: example
spec:
  collectorSelector:
    matchLabels:
      app.kubernetes.io/instance: example-collector
  ...
```

Or alternatively, via an annotation:

```yaml
apiVersion: opentelemetry.io/v1alpha2
kind: TargetAllocator
metadata:
  name: example
  annotations:
    targetallocator.opentelemetry.io/collector: "example-collector"
```
Then the resolution flow for the Collector CR with a TargetAllocator reference becomes:

1. Get the TargetAllocator resource based on the ref
2. Set the annotation on it, pointing to Collector CR
3. TargetAllocator reconciler picks up the change and sets the right selector on TargetAllocator CR
4. TargetAllocator is ready to allocate targets once Collector Pods become ready

The Collector CR depends on the TargetAllocator CR in this flow, but not vice versa.
