### ISSUE TITLE
There's no appProtocol for Opencensus receiver

### ISSUE THREAD

**Issue by husnialhamdani** [open-telemetry/opentelemetry-operator#2487]
### Component(s)

operator

## Description
There's no appProtocol for opencensus receiver in the OTEL Service object.

```
ports:
  - name: opencensus
    port: 55678
    protocol: TCP
    targetPort: 55678
  - appProtocol: grpc
    name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - appProtocol: http
    name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - appProtocol: http
    name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
```
## Steps to Reproduce

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
  namespace: some-namespace
spec:
  config: |
    receivers:
      opencensus:
        endpoint: 0.0.0.0:55678
      zipkin:
        endpoint: 0.0.0.0:9411
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      tail_sampling:
        policies:
          - name: drop_noisy_traces_url_user_agent
            type: string_attribute
            string_attribute:
              key: user_agent
              values:
                - Prometheus.*
              enabled_regex_matching: true
              invert_match: true
    exporters:
      logging:
        loglevel: info
      jaeger:
        endpoint: jaeger-collector.some-namespace:14250
        tls:
          insecure: true
    extensions:
      zpages:
        endpoint: 0.0.0.0:55679
    service:
      extensions:
        - zpages
      pipelines:
        traces:
          receivers:
            - zipkin
            - opencensus
            - otlp
          processors:
            - tail_sampling
          exporters:
            - logging
            - jaeger
  ingress:
    route: {}
  mode: deployment
  replicas: 1
  resources: {}
  targetAllocator:
    prometheusCR: {}
    resources: {}
  upgradeStrategy: automatic
```

### Kubernetes Version

v1.25.6

### Operator version

v0.81

### Collector version

v0.81

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
