### ISSUE TITLE
Issue with NestJs operator autoinstrumentation

### ISSUE THREAD

**Issue by f3l1x98** [open-telemetry/opentelemetry-operator#2510]
### Component(s)

operator, instrumentation

### Describe the issue you're reporting

I hope this is the correct place for the question and somebody can help me.

I am currently trying to setup tracing for an application which consists of four NestJs applications.
The traces are exported to a data-prepper instance which then sends them to OpenSearch.
I have gotten the opentelemetry operator and autoinstrumentation to work in the sense that everything deploys, starts and traces are collected/send.

## Issue
My issue now is that out of the four applications only two report traces from other instrumentations than the `@opentelemetry/instrumentation-fs` (like for example `@opentelemetry/instrumentation-http`).
The others only report fs traces (quite a lot of them), even though one of them is the main backend which calls the other applications.

I have also checked this with the `logging` exporter and got the same result so the issue should not be data-prepper/opensearch.

Used versions:
- OpenTelemetry Operator: 0.90.0 (and later tried 0.91.0)

## Configurations
``` yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector-sidecar-agent
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      otlp/data-prepper:
        endpoint: {{ .Values.dataprepper.host }}
        tls:
          insecure: true
          insecure_skip_verify: true
    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp/data-prepper]
```
``` yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ .Values.instrumentation.nodejs }}
spec:
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  nodejs:
```
``` yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  selector:
    tier: {{ .Chart.Name }}

  ports:
    - protocol: TCP
      port: 3001
      name: http
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      tier: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: backend
        tier: {{ .Chart.Name }}
      annotations:
        sidecar.opentelemetry.io/inject: "{{ .Values.opentelemetry.injectSidecar }}"
        instrumentation.opentelemetry.io/inject-nodejs: "{{ .Values.opentelemetry.autoInstrumentNodejs }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"

          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3001
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10

          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3001
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
```
