### ISSUE TITLE
Failed to select an OpenTelemetry Collector instance for pod's sidecar

### ISSUE THREAD

**Issue by gerijani** [open-telemetry/opentelemetry-operator#2546]
### Component(s)

operator

### Describe the issue you're reporting

We'd deployed recently OT into our AKS cluster and are now trying to use auto instrumentation but the operator always throws the below error:

```
{"level":"error","ts":"2024-01-19T10:32:29Z","msg":"failed to select an OpenTelemetry Collector instance for this pod's sidecar",
"namespace":"opentelemetry",
"name":"platform-samples-api-2",
"error":"no OpenTelemetry Collector instances available",
"stacktrace":
"github.com/open-telemetry/opentelemetry-operator/pkg/sidecar.(*sidecarPodMutator).Mutate
/home/runner/work/opentelemetry-operator/opentelemetry-operator/pkg/sidecar/podmutator.go:84\ngithub.com/open-telemetry/opentelemetry-operator/internal/webhook/podmutation.(*podMutationWebhook).Handle
/home/runner/work/opentelemetry-operator/opentelemetry-operator/internal/webhook/podmutation/webhookhandler.go:92\nsigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/webhook/admission/webhook.go:169\nsigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/webhook/admission/http.go:98\nsigs.k8s.io/controller-runtime/pkg/webhook/internal/metrics.InstrumentedHook.InstrumentHandlerInFlight.func1
/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.18.0/prometheus/promhttp/instrument_server.go:60\nnet/http.HandlerFunc.ServeHTTP
/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1
/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.18.0/prometheus/promhttp/instrument_server.go:147\nnet/http.HandlerFunc.ServeHTTP
/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2
/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.18.0/prometheus/promhttp/instrument_server.go:109\nnet/http.HandlerFunc.ServeHTTP
/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\nnet/http.(*ServeMux).ServeHTTP
/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2514\nnet/http.serverHandler.ServeHTTP
/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2938\nnet/http.(*conn).serve
/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2009"}
```

We used HELM chart 0.45.2 for the deployment with operator version 0.92.0. As we are in AKS we modified clusterrole.yaml template as  this was also needed, and added:
```
- apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
```
Value file was modified as below:
```
autoInstrumentationImage:
  python:
     repository: "otel/autoinstrumentation-python"
        tag: ""
  dotnet:
     repository: "otel/autoinstrumentation-dotnet"
        tag: ""

```
We created manually an instrumentation definition for .NET according https://opentelemetry.io/docs/kubernetes/operator/automatic/
```
 kubectl apply -n opentelemetry -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: demo-instrumentation
spec:
  exporter:
    endpoint: http://collector.opentelemetry.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
EOF
instrumentation.opentelemetry.io/demo-instrumentation created

```
