### ISSUE TITLE
Self-signed cert-manager Certificate will fail with current deployment

### ISSUE THREAD

**Issue by RichieSams** [open-telemetry/opentelemetry-operator#255]
With latest cert-manager, if you attempt to install opentelemetry-operator via the k8s manifest in the releases, all attempts to create a Collector will fail during webhook with:

```
x509: certificate signed by unknown authority
```

This is due to the self-signed Issuer creating a cert with an empty DN.
See this issue: https://github.com/jetstack/cert-manager/issues/3634

To fix this, we can add a dummy subject section to the Certificate. Current:

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: opentelemetry-operator-serving-cert
  namespace: opentelemetry-operator-system
spec:
  dnsNames:
    - opentelemetry-operator-webhook-service.opentelemetry-operator-system.svc
    - opentelemetry-operator-webhook-service.opentelemetry-operator-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: opentelemetry-operator-selfsigned-issuer
  secretName: opentelemetry-operator-controller-manager-service-cert
```

Fix

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: opentelemetry-operator-serving-cert
  namespace: opentelemetry-operator-system
spec:
  dnsNames:
    - opentelemetry-operator-webhook-service.opentelemetry-operator-system.svc
    - opentelemetry-operator-webhook-service.opentelemetry-operator-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: opentelemetry-operator-selfsigned-issuer
  secretName: opentelemetry-operator-controller-manager-service-cert
  subject:
    organizationalUnits:
      - "opentelemetry-operator"
```
