### ISSUE TITLE
Ability to disable Prometheus scrape annotations

### ISSUE THREAD

**Issue by GiorgioBullo** [open-telemetry/opentelemetry-operator#2554]
### Component(s)

Collector

### Is your feature request related to a problem? Please describe.

When creating an opentelemetry collector, I noticed that the operator always creates the deployments with the following annotations:

```
    prometheus.io/path: /metrics
    prometheus.io/port: '8888'
    prometheus.io/scrape: 'true' 
```

I had a look at the code, and it looked to me like they are hardcoded in `internal/manifests/collector/annotations.go`

In my environment, I am using a servicemonitor to scrape the collector, so I don't want to have those annotations, otherwise I will have 2 jobs scraping my pod.

I found a workaround to disable the annotations scraping. I am overriding the pod annotations using:

```
spec:
  podAnnotations:
    prometheus.io/scrape: "false"
```

This works, however it doesn't look clean because now annotations are inconsistent between deployment and pod:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8888"
    prometheus.io/scrape: "true"
 ...
spec:
  ...
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8888"
        prometheus.io/scrape: "false"
  ...
```

### Describe the solution you'd like

A flag in the collector spec should do the trick to eventually enable/disable these annotations.

### Describe alternatives you've considered

A more sophisticated solution would be to give the possibility to choose between these annotations or a servicemonitor created by the opentelemetry operator.

### Additional context

Please, ask if it is not clear
