### ISSUE TITLE
Updating the AutoScale/HPA causing the pods to redeploy

### ISSUE THREAD

**Issue by JustinMason** [open-telemetry/opentelemetry-operator#2585]
### Component(s)

operator

## Description

When updating the AutoScale HPA settings the containers are redeployed.

## Steps to Reproduce

Deploy Otel Collector with AutoScale set to min: 3
Validate that 3 replicas are running.
Update AutoScale to Min: 4
Observer that the deployment/statefulSet gets redeployed cause the running replicas to need to all be restarted.

## Expected Result
HPA CRD would be updated without recycling the deployment.

## Actual Result
All Replicas are restarted

### Kubernetes Version

v1.27.7-gke.1121000

### Operator version

v0.92.1

### Collector version

v0.92.0

## Environment
GKE

### Additional context

Ideally an UPDATE to an existing HPA would only update the HPA so that running instances are not restarted.
When a system is under heavy load there may be a need to increase the Max Replicas.
Restarting all the containers causes a huge backlog as the replicas come back online.
If the goal was to mitigate load by increasing replicas this behavior makes it much worse before it can use the new HPA.

**Comment by changexd** [comment]
Hi, Is it possible for you to provide configurations of otelcol with before and after modifications?
As I've tried only editing `autoscaler.minReplicas` in the otelcol resource with the steps you mentioned, it did not redeploy/restart pods

**Comment by yuriolisa** [comment]
@JustinMason, could you please provide the manifests you applied in order to try to reproduce the error?

**Comment by yuriolisa** [comment]
@JustinMason, did you have the opportunity to check it out?

**Comment by JustinMason** [comment]
Sorry for the delay, I have stopped using the autoscale for the persistent collector because it was not helping our use case.

This was the section I had been using:
```yaml
autoscaler:
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilization: 60
  targetMemoryUtilization: 80
  behavior:
    scaleDown:
      policies:
        - periodSeconds: 120
          type: 'Pods'
          value: 1
      selectPolicy: 'Max'
      stabilizationWindowSeconds: 400
    scaleUp:
      policies:
        - periodSeconds: 15
          type: 'Pods'
          value: 2
      selectPolicy: 'Max'
      stabilizationWindowSeconds: 60
```
