### ISSUE TITLE
Warning of missing Cluster Roles for Target Allocator despite them being present

### ISSUE THREAD

**Issue by avillela** [open-telemetry/opentelemetry-operator#2685]
### Component(s)

target allocator

## Description

Getting a warning after applying the `OpenTelemetryCollector` CR with TargetAllocator enabled, in spite of having created the appropriate `ServiceAccount`, `ClusterRole`, and `ClusterRoleBinding` for the TA based on the documentation [here](https://github.com/open-telemetry/opentelemetry-operator/blob/d44f71db4f53963b9349fd6119e416775298c4f9/cmd/otel-allocator/README.md#rbac). See warning message below.

## Steps to Reproduce

Create `ServiceAccount`, `RoleBinding`, and `ClusterRoleBinding` as follows:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-targetallocator-sa
  namespace: opentelemetry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-targetallocator-role
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  - podmonitors
  verbs:
  - '*'
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs: ["get", "list", "watch"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-targetallocator-rb
subjects:
  - kind: ServiceAccount
    name: opentelemetry-targetallocator-sa
    namespace: opentelemetry
roleRef:
  kind: ClusterRole
  name: opentelemetry-targetallocator-role
  apiGroup: rbac.authorization.k8s.io
```

Create the following `OpenTelemetryCollector` CR using the `ServiceAccount` defined above:

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otelcol
  namespace: opentelemetry
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    serviceAccount: opentelemetry-targetallocator-sa
    prometheusCR:
      enabled: true
      serviceMonitorSelector:
        app: my-app
  config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 30s
            static_configs:
            - targets: [ '0.0.0.0:8888' ]
        target_allocator:
          endpoint: http://otelcol-targetallocator.opentelemetry.svc.cluster.local
          interval: 30s
          collector_id: "${POD_NAME}"

    exporters:
      logging:
        verbosity: detailed

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [logging]
```

## Expected Result

I should not be seeing the warning below.

## Actual Result

The following warning comes up after I apply the OpenTelemetryCollector CR. Note that this is non-blocking - my code is working; however, the warning is misleading.

```text
Warning: missing the following rules for namespaces: [get,list,watch]
Warning: missing the following rules for networking.k8s.io/ingresses: [get,list,watch]
Warning: missing the following rules for nonResourceURL: /metrics: [get]
Warning: missing the following rules for monitoring.coreos.com/podmonitors: [*]
Warning: missing the following rules for nodes: [get,list,watch]
Warning: missing the following rules for services: [get,list,watch]
Warning: missing the following rules for endpoints: [get,list,watch]
Warning: missing the following rules for pods: [get,list,watch]
Warning: missing the following rules for configmaps: [get]
Warning: missing the following rules for discovery.k8s.io/endpointslices: [get,list,watch]
Warning: missing the following rules for monitoring.coreos.com/servicemonitors: [*]
Warning: missing the following rules for nodes/metrics: [get,list,watch]
opentelemetrycollector.opentelemetry.io/otelcol created
```

### Kubernetes Version

1.27.3

### Operator version

0.94.0

### Collector version

0.94.0

## Environment
OS: MacOS Sonoma 14.1.1 (also got the same result in GH codespaces)
Compiler(if manually compiled): N/A
