### ISSUE TITLE
nodeSelector from collector spec ends up in container args if using operator v0.94.0

### ISSUE THREAD

**Issue by zumic96** [open-telemetry/opentelemetry-operator#2689]
### Component(s)

collector

## Description

When using operator v0.94.0 node selector from collector definition ends up appended to container args which makes it fail at startup.
Works properly with v0.93.0 operator.
I am suspecting this line but I didn't go to deep in the code https://github.com/open-telemetry/opentelemetry-operator/blob/1e80370ec4ad2483681777662fbe275b49353593/internal/api/convert/v1alpha.go#L43

## Steps to Reproduce

Run operator v0.94.0 and create OpenTelemetryCollector that has some values in spec.nodeSelector.

## Expected Result

Args should not have node selector appended to them and collector container should start.
Collector pod definition:
```
-----ommited-----
containers:
    - name: otc-container
      image: otel/opentelemetry-collector-contrib:0.94.0
      args:
        - '--config=/conf/collector.yaml'
-----ommited-----
nodeSelector:
    iaac: 'true'
    kubernetes.io/arch: arm64
-----ommited-----
```

## Actual Result

Node selector gets appended to collector container args and fails startup.
Collector pod definition:
```
-----ommited-----
containers:
    - name: otc-container
      image: otel/opentelemetry-collector-contrib:0.94.0
      args:
        - '--config=/conf/collector.yaml'
        - '--iaac=true'
        - '--kubernetes.io/arch=arm64'
-----ommited-----
nodeSelector:
    iaac: 'true'
    kubernetes.io/arch: arm64
-----ommited-----
```

### Kubernetes Version

1.28.0

### Operator version

0.94.0

### Collector version

0.94.0

### Environment information

Installed operator with helm-chart to EKS.

### Log output

```shell
Error: unknown flag: --iaac
2024/02/29 12:28:25 collector server run finished with error: unknown flag: --iaac
```
