### ISSUE TITLE
Support for adding custom Java extensions

### ISSUE THREAD

**Issue by crossoverJie** [open-telemetry/opentelemetry-operator#2719]
### Component(s)

instrumentation

### Is your feature request related to a problem? Please describe.

Similar to these issues: #1135 #1758 , it is not possible to add custom extensions.

### Describe the solution you'd like

```dockerfile
FROM busybox


ADD open-telemetry/opentelemetry-javaagent.jar /javaagent.jar

# Copy extensions to specify a path.
ADD open-telemetry/extensions/ext-1.0.0.jar /extensions/ext-1.0.0.jar

RUN chmod -R go+r /javaagent.jar
RUN chmod -R go+r /extensions/otel-extensions-pulsar-client-metrics-1.0.0.jar
```
---

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  java:
    image: custom-image:1.0.0
    extensions: /extensions
    env:
    # If extension.jar already exists in the container, you can only specify a specific path with this environment variable.
      - name: OTEL_EXTENSIONS_DIR
        value: /custom-dir
```

We can copy `extension.jar` to the specified directory in a custom image, and Operator will copy jars from the `${java.extensions}` directory to `/otel-auto-instrumentation/extension`.

JVM parameters will also be added to the `JAVA_TOOL_OPTIONS` environment variable: `-Dotel.javaagent.extensions=/otel-auto-instrumentation/extensions/extension.jar`.

At the same time, add an environment variable `OTEL_EXTENSIONS_DIR`, the default value of which can be `/otel-auto-instrumentation/extensions`.

If `extension.jar` already exists in the container, we can only specify a specific path with this environment variable.

### Describe alternatives you've considered

These are just my personal thoughts; are there any other better solutions?
