### ISSUE TITLE
Python auto-instrumentation returns failed traces

### ISSUE THREAD

**Issue by muandane** [open-telemetry/opentelemetry-operator#2721]
### Component(s)

instrumentation

### Describe the issue you're reporting

I have a couple of python containers running on kubernetes, that use Pika mainly and do some exchange with a minio service and a rabbitmq service, i do recover some of the traces correctly but i get spammed with Erroring traces from Urllib3 that tries to connect to port 42699 on local host (i dont have nor did i configure anything that uses urllib)

this is my instrumentation configuration as of now:

```yaml
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python-traces
  namespace: caas-apps
spec:
  exporter:
    endpoint: http://caas-collector.caas-infra.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: '1'
  python:
    env:
      - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
        value: "urllib3,urllib,flask"
```

i get alot of these error traces that say the same thing
![image](https://github.com/open-telemetry/opentelemetry-operator/assets/114167214/34e8513a-0baf-4565-a374-241fd6ad1dc9)

![trace-error](https://github.com/open-telemetry/opentelemetry-operator/assets/114167214/e5e75fa2-32cf-4a83-b358-540c53b55f75)

![image](https://github.com/open-telemetry/opentelemetry-operator/assets/114167214/b581a1eb-778a-4e9c-b0b9-440dd013586e)

i'm running other language instrumentations using different instrumentation definitions for java and nodejs and both of them work flawlessly.
