### ISSUE TITLE
Remove support for collector v1alpha1 CRD version

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#2727]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

https://github.com/open-telemetry/opentelemetry-operator/issues/2620 introduced collector `v1beta1` CRD and deprecated `v1alpha1`.  The support for `v1alpha1`  should be removed at some point after all existing objects are migrated to `v1beta1`. 

Only a single version is stored in `etcd`.  However, the old stored versions are not automatically migrated to new versions see https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#upgrade-existing-objects-to-a-new-stored-version:

After the installation of the operator that supports both versions:
```
 k get crd opentelemetrycollectors.opentelemetry.io -o yaml
status:
  acceptedNames:
    kind: OpenTelemetryCollector
    listKind: OpenTelemetryCollectorList
    plural: opentelemetrycollectors
    shortNames:
    - otelcol
    - otelcols
    singular: opentelemetrycollector
  conditions:
  - lastTransitionTime: "2024-03-07T09:55:31Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-03-07T09:55:31Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
  - v1beta1
```

The collector status field shows both `storedVersions` (assuming `v1alpha` objects were present in the cluster before). After migrating all `v1alpha1` let's disable it from the CRD status:

```
kubectl patch customresourcedefinitions opentelemetrycollectors.opentelemetry.io  --subresource='status' --type='merge' -p '{"status":{"storedVersions":["v1beta1"]}}'  
---
status:
  acceptedNames:
    kind: OpenTelemetryCollector
    listKind: OpenTelemetryCollectorList
    plural: opentelemetrycollectors
    shortNames:
    - otelcol
    - otelcols
    singular: opentelemetrycollector
  conditions:
  - lastTransitionTime: "2024-03-07T09:55:31Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-03-07T09:55:31Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
```

### Describe the solution you'd like

Proposed deprecation workflow

1. release CRD with `v1beta1` and deprecated `v1alpha`
2. leave time for users to migrate to `v1beta1` https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#upgrade-existing-objects-to-a-new-stored-version 
3. change the `v1alpha1` to `served: false` 
4. remove `v1alpha1`

We should investigate if steps 3 and 4 could be done at once.
