### ISSUE TITLE
Inject the K8S_NODE_NAME environment variable when using the kubeletstatsreceiver and serviceAccount authentication

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#2779]
### Is your feature request related to a problem? Please describe.

One of the methods to authenticate with the API for the `kubeletstatsreceiver` needs the node name. The documentation explains how to do it: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/README.md#service-account-authentication-example

### Describe the solution you'd like

It would be nice to inject the environment variable automatically from the operator.

**Comment by jvoravong** [comment]
You can use the `OTEL_RESOURCE_ATTRIBUTES_NODE_NAME` environment variable injected by the operator to configure the receiver.

Example:
```yaml
receivers:
  kubeletstats:
    collection_interval: 20s
    auth_type: "serviceAccount"
    endpoint: "https://${env:OTEL_RESOURCE_ATTRIBUTES_NODE_NAME}:10250"
    insecure_skip_verify: true
```
