### ISSUE TITLE
Unable to use nodeSelector from v0.94.0

### ISSUE THREAD

**Issue by mchahar** [open-telemetry/opentelemetry-operator#2783]
### Component(s)

collector

## Steps to Reproduce

Deploy Opentelemetry operator version v0.94.0
`helm upgrade -i opentelemetry-operator --version 0.46.0 open-telemetry/opentelemetry-operator`

Create a test OpenTelemetryCollector using a nodeSelector

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: test
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.93.0
  nodeSelector:
    agentpool: test
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
```

## Expected Result
The opentelemetry collector should run on node with labels agentpool: test

## Actual Result
Pod does have nodeselector defined correctly and assigned to correct node pool, however, pod is crashing with below error 

```
Error: unknown flag: --agentpool
2024/03/25 05:55:28 collector server run finished with error: unknown flag: --agentpool
```

### Kubernetes Version

1.26.10

### Operator version

v0.94.0

### Collector version

v0.93.0

## Environment
AKS 1.26
