### ISSUE TITLE
Failed to watch *v1.ReplicaSet and Failed to list *v1.ReplicaSet

### ISSUE THREAD

**Issue by thefirstofthe300** [open-telemetry/opentelemetry-operator#2823]
## Description

Given the OpenTelemetryCollector configuration:

```
  config: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    processors:
      k8sattributes: {}
      batch: {}
    exporters:
      datadog:
        api:
          site: datadoghq.com
          key: ${env:DD_API_KEY}
    service:
      pipelines:
        metrics:
          receivers:
            - otlp
          processors:
            - k8sattributes
            - batch
          exporters:
            - datadog
```

The otelcol throws the error:
```
W0405 22:24:51.394408       1 reflector.go:539] k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: failed to list *v1.ReplicaSet: replicasets.apps is forbidden: User "system:serviceaccount:observability-system:opentelemetry-collector" cannot list resource "replicasets" in API group "apps" at the cluster scope
E0405 22:24:51.394454       1 reflector.go:147] k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: Failed to watch *v1.ReplicaSet: failed to list *v1.ReplicaSet: replicasets.apps is forbidden: User "system:serviceaccount:observability-system:opentelemetry-collector" cannot list resource "replicasets" in API group "apps" at the cluster scope
```
over and over again.

## Steps to Reproduce
Deploy the above provided configuration

## Expected Result
No errors

## Actual Result
Errors due to missing rbac permissions

### Kubernetes Version

1.28.3

### Operator version

0.97.1

### Collector version

0.97.0
