### ISSUE TITLE
failed to create objects for otel: clusterroles.rbac.authorization.k8s.io

### ISSUE THREAD

**Issue by jicki** [open-telemetry/opentelemetry-operator#2824]
## Description

{"level":"debug","ts":"2024-04-07T06:21:49.787324529Z","logger":"events","msg":"failed to create objects for otel: clusterroles.rbac.authorization.k8s.io \"otel-opentelemetry-cluster-role\" is forbidden: user \"system:serviceaccount:opentelemetry:opentelemetry-operator-controller-manager\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:opentelemetry\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"\"], Resources:[\"namespaces\"], Verbs:[\"get\"]}\nclusterroles.rbac.authorization.k8s.io \"otel-opentelemetry-cluster-role\" not found","type":"Warning","object":{"kind":"OpenTelemetryCollector","namespace":"opentelemetry","name":"otel","uid":"e1fb0104-da56-491e-ab30-d994704aa810","apiVersion":"opentelemetry.io/v1alpha1","resourceVersion":"570258110"},"reason":"Error"}

## Steps to Reproduce

update opentelemetry-operator v0.97.1 

set  - --create-rbac-permissions

### Kubernetes Version

1.23.11

### Operator version

v0.97.1

### Collector version

v0.97.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by zarbis** [comment]
I've patched `opentelemetry-operator-manager` `ClusterRole` with those:
```yaml
### ADDED ON TOP OF CHART
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  verbs:
  - get
  - list
  - watch
### END OF ADDITION
- apiGroups:
  - apps
  - extensions ### ADDED ON TOP OF CHART
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
  ```
  and it helped.
  
  Ultimately this needs to land into chart [here](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/templates/clusterrole.yaml).
