### ISSUE TITLE
Helm template to deploy otel collector

### ISSUE THREAD

**Issue by PandeoF1** [open-telemetry/opentelemetry-operator#2865]
### Component(s)

collector

## Description
Im trying to deploy the otel collector using helm template.
It create the "OpentelemetryCollector" deployment but it doesn't deploy the pod.

## Steps to Reproduce
```yaml
{{ if .Values.otel.enabled }} # This value is by default to True
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: cos-collector
  labels:
    app.kubernetes.io/name: otel
    app.kubernetes.io/component: otel-collector
spec:
  mode: deployment
  hostNetwork: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      otlp:
        endpoint: {{ .Values.otel.endpoint }}
        tls:
          insecure: {{ .Values.otel.insecure | default "false" }}
    processors:
      batch:
    service:
      pipelines:
      {{ if .Values.otel.traces }}
        traces:
          receivers: [otlp]
          processors: [batch]
         exporters: [otlp]
      {{ end }}
     {{ if .Values.otel.metrics }}
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
      {{ end }}
      {{ if .Values.otel.logs }}
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
      {{ end }}
{{ end }}
```

## Expected Result
Deploy otel collector

## Actual Result
Doesn't deploy the collector

![Screenshot from 2024-04-17 11-04-46](https://github.com/open-telemetry/opentelemetry-operator/assets/58373303/4dfd8cd6-a2cf-46a7-993c-e4d7967e2e11)

Note: 
When i deploy the template using kubectl apply it work :/

### Kubernetes Version

v1.27.11+k3s1

### Operator version

v0.98.0

### Collector version

latest ?

## Environment
OS: Pop!_OS 22.04 LTS
Kube: K3s

### Log output

```shell
There is no warning / error provided in the helm install
```

### Additional context

The problem is only when i try to deploy the collector using  helm. When i use kubectl i have no problem (but same yaml).

**Comment by suyash-811** [comment]
What command did you use for deploying the manifest with helm?

**Comment by PandeoF1** [comment]
> What helm chart are you using?

The helm chart that i use is our application. And we want to have the collector+ instrumentation inside the templates to deploy it if we want.
But it doesn't create the pod (the operator is deployed)

**Comment by jaronoff97** [comment]
Any logs from the operator?

**Comment by PandeoF1** [comment]
> Any logs from the operator?

{"level":"error","ts":"2024-04-18T08:41:42Z","msg":"Reconciler error","controller":"opentelemetrycollector","controllerGroup":"opentelemetry.io","controllerKind":"OpenTelemetryCollector","OpenTelemetryCollector":{"name":"test","namespace":"test"},"namespace":"test","name":"test","reconcileID":"9d1df754-9e8f-4aa2-9aac-ed7a6984728f","error":"failed to convert to v1beta1: could not convert config json to v1beta1.Config","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}

**Comment by swiatekm-sumo** [comment]
Could you also post the fully templated Collector resource that you're applying to the cluster? Basically, the output of `helm template`. It looks like your configuration is malformed in some way, but it's hard to tell how exactly.

**Comment by PandeoF1** [comment]
> Could you also post the fully templated Collector resource that you're applying to the cluster? Basically, the output of `helm template`. It looks like your configuration is malformed in some way, but it's hard to tell how exactly.

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: test-instrumentation
  labels:
    app.kubernetes.io/name: otel
    app.kubernetes.io/component: otel-instrumentation
spec:
  java:
    image: registry.custom_registry.com/opentelemetry/autoinstrumentation-java:2.3.0
  exporter:
    endpoint: http://test-collector:4317
  propagators:
    - tracecontext
    - baggage
    - jaeger
  sampler:
    type: parentbased_traceidratio
    argument: "1"
---
# Source: test/templates/otel-collector.yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: test # Otel add -collector to the name
  labels:
    app.kubernetes.io/name: otel
    app.kubernetes.io/component: otel-collector
spec:
  mode: deployment
#  hostNetwork: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      otlp:
        endpoint: 
        tls:
          insecure: false
    processors:
      batch:
    service:
      pipelines:
      
        traces:
          receivers: [otlp]
          processors: [batch]
         exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]     
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
```
The thing weird is that when i take the template and remove every thing that are from helm templating and just kubectl apply -f file.yaml it work :/

**Comment by swiatekm-sumo** [comment]
```
        traces:
          receivers: [otlp]
          processors: [batch]
         exporters: [otlp]
```
`exporters` is misaligned here. Unfortunately yaml is whitespace-sensitive. :unamused:
