### ISSUE TITLE
Missing notation for Services broke integration with ServiceMonitor

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#2877]
### Component(s)

collector

## Description
When we create a collector instance with `prometheus` exporter, the created `ServiceMonitor` requires the following label selectors:
```yaml
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/instance: chainsaw-otlp-metrics.cluster-collector
      app.kubernetes.io/managed-by: opentelemetry-operator
      app.kubernetes.io/part-of: opentelemetry
      operator.opentelemetry.io/collector-monitoring-service: Exists
```

The label ` operator.opentelemetry.io/collector-monitoring-service: Exists` is available in the `Monitoring` service but not in the `collector` nor `collector-headless` services. Due to that, the `ServiceMonitor` cannot match the `Service` for the OTEL Collector and scrape the metrics from the Prometheus exporter.

### Kubernetes Version

.

### Operator version

.

### Collector version

.

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
