### ISSUE TITLE
TargetAllocator-managed Prometheus configuration using custom resources does not perform metricRelabelings using `__` prefixed metrics

### ISSUE THREAD

**Issue by thefirstofthe300** [open-telemetry/opentelemetry-operator#2891]
### Component(s)

otel-collector
otel-targetallocator

## Description

I am attempting to configure a ServiceMonitor to monitor a cluster autoscaler. I would like to add the value of the `app.kubernetes.io/instance` label as a metric label named `autoscaler_target`. I am using the following ServiceMonitor config:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: us-west-1-staging
    meta.helm.sh/release-namespace: clusters-system
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: us-west-1-staging
    helm.toolkit.fluxcd.io/namespace: clusters-system
    release: prometheus-operator
  name: us-west-1-staging-clusterapi-cluster-autoscaler
  namespace: observability-system
spec:
  endpoints:
  - interval: 10s
    metricRelabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_label_app_kubernetes_io_instance
      targetLabel: autoscaler_target
    path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - clusters-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: us-west-1-staging
      app.kubernetes.io/name: clusterapi-cluster-autoscaler
```
If I change `metricRelabelings` to `relabelings`, everything functions properly. If create a temporarly label using `relabelings` named `_tmp_autoscaler_target` and relabel that using metricRelabelings, everything functions appropriately.

It almost feels like the `__` prefixed metrics are dropped before `metricRelabelings` rules are processed. My understanding and (albeit old) experience with Prometheus was that `__` prefixed metrics are dropped after `metric_relabel_configs` are processed. Is that not the case here?

### Kubernetes Version

1.28.3

### Operator version

0.97.1

### Collector version

0.97.0
