### ISSUE TITLE
Not able to pass custom config to the opentelemetry-collector using "args"

### ISSUE THREAD

**Issue by abvaidya** [open-telemetry/opentelemetry-operator#2897]
### Component(s)

collector

## Description
I am specifying a configmap which contains the collector config and would like to pass it to the collector.
## Steps to Reproduce
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
spec:
  mode: deployment
  image: collector-image
  configmaps:
    - name: mycm
      mountpath: mypath
  args:
    config: /var/conf/mypath/configmap-mycm/config.yaml
```
## Expected Result
Collector is started with ( omitted other fields )
```
    spec:
      containers:
      - args:
        - --config=/var/conf/mypath/configmap-mycm/config.yaml
```
## Actual Result
( omitted other fields )
```
    spec:
      containers:
      - args:
        - --config=/conf/collector.yaml
```

Am I missing something or configuring the `args` in incorrect way? 

I do see the config from confimap mounted correctly at the above location.

Thank you for viewing this.

### Kubernetes Version

1.29.0

### Operator version

v0.95.0

### Collector version

v0.97.0

## Environment
EKS
