### ISSUE TITLE
Problems using some extensions

### ISSUE THREAD

**Issue by lsergio** [open-telemetry/opentelemetry-operator#2963]
### Component(s)

collector

### Describe the issue you're reporting

Hi, I have installed the OTLP Operator as described at https://github.com/open-telemetry/opentelemetry-operator and have been able to use it with the default exporters.
Now I'm trying to configure loadbalancing as described at https://opentelemetry.io/docs/collector/scaling/.
My otelcollector is defined as:

```
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: loadbalancer
  namespace: collector
spec:
  replicas: 1
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      loadbalancing:
        protocol:
          otlp: {}
        resolver:
          dns:
            hostname: otelcol.collector.svc.cluster.local

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [loadbalancing]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [loadbalancing]
```

After applying it, I see and error at the collector log:

```
* error decoding 'exporters': unknown type: "loadbalancing" for id: "loadbalancing" (valid values: [logging otlphttp opencensus prometheus debug otlp file kafka prometheusremotewrite zipkin nop])
```
I see the collector deployment is using image 0.99.00.

Could someone give some hint on how to enable this and other extensions using the operator?

Thanks
