### ISSUE TITLE
unknown type of exporters and processors in the latest version of otel operator

### ISSUE THREAD

**Issue by hzhang4-sc** [open-telemetry/opentelemetry-operator#2979]
### Component(s)

collector

### Describe the issue you're reporting

I'm running otel operator with latest version 0.100.0, but it seems like the collector in the operator only supports a very limited set of exporters and processors, see below error message

```
Error: failed to get config: cannot unmarshal the configuration: 2 error(s) decoding:

* error decoding 'exporters': unknown type: "googlemanagedprometheus" for id: "googlemanagedprometheus" (valid values: [logging nop file kafka opencensus prometheusremotewrite zipkin debug otlp otlphttp prometheus])
* error decoding 'processors': unknown type: "transforms" for id: "transforms" (valid values: [filter batch memory_limiter attributes resource span probabilistic_sampler])
2024/05/20 23:39:42 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 2 error(s) decoding:

* error decoding 'exporters': unknown type: "googlemanagedprometheus" for id: "googlemanagedprometheus" (valid values: [logging nop file kafka opencensus prometheusremotewrite zipkin debug otlp otlphttp prometheus])
* error decoding 'processors': unknown type: "transforms" for id: "transforms" (valid values: [filter batch memory_limiter attributes resource span probabilistic_sampler])
```

And below is my collector manifest

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default:collector-with-ta
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default:collector-with-ta
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default:collector-with-ta
subjects:
  - kind: ServiceAccount
    namespace: default
    name: collector-with-ta-targetallocator
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: collector-with-ta
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
  config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-test'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [ __meta_kubernetes_pod_label_app_kubernetes_io_name ]
                  action: keep
                  regex: prom-example
                - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_path ]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                - source_labels: [ __address__, __meta_kubernetes_pod_annotation_prometheus_io_port ]
                  action: replace
                  regex: (.+):(?:\d+);(\d+)
                  replacement: $1:$2
                  target_label: __address__
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)

    exporters:
      googlemanagedprometheus: {}
    processors:
      resourcedetection:
        detectors: [ gcp ]
        timeout: 10s

      transforms:
        # "location", "cluster", "namespace", "job", "instance", and "project_id" are reserved, and
        # metrics containing these labels will be rejected.  Prefix them with exported_ to prevent this.
        metric_statements:
          - context: datapoint
            statements:
              - set(attributes["exported_location"], attributes["location"])
              - delete_key(attributes, "location")
              - set(attributes["exported_cluster"], attributes["cluster"])
              - delete_key(attributes, "cluster")
              - set(attributes["exported_namespace"], attributes["namespace"])
              - delete_key(attributes, "namespace")
              - set(attributes["exported_job"], attributes["job"])
              - delete_key(attributes, "job")
              - set(attributes["exported_instance"], attributes["instance"])
              - delete_key(attributes, "instance")
              - set(attributes["exported_project_id"], attributes["project_id"])
              - delete_key(attributes, "project_id")

      batch:
        # batch metrics before sending to reduce API usage
        send_batch_max_size: 200
        send_batch_size: 200
        timeout: 5s

      memory_limiter:
        # drop metrics if memory usage gets too high
        check_interval: 1s
        limit_percentage: 65
        spike_limit_percentage: 20

    service:
      pipelines:
        metrics:
          receivers: [ prometheus ]
          processors: [ batch, memory_limiter, resource, transform ]
          exporters: [ googlemanagedprometheus ]
```
And I checked the collector deploy manifest, it is running the latest version as well, which is ``ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.100.0``. I'm wondering is this because not all exporters and processors are supported in otel operator?
