### ISSUE TITLE
Default v1beta1 embedded target allocator does not scrape any target

### ISSUE THREAD

**Issue by mikel-jason** [open-telemetry/opentelemetry-operator#2993]
### Component(s)

target allocator

## Description

Deploying a `prometheusreceiver` with a target allocator with no specific filtering for servicemonitors/podmonitors detects no jobs and scrapes no targets.

<details>
<summary>OTelCol manifest</summary>

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-metrics
  finalizers:
    - opentelemetrycollector.opentelemetry.io/finalizer
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/initialized
                operator: In
                values:
                  - 'true'
          - matchExpressions:
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                  - fargate
  config:
    exporters:
      prometheusremotewrite:
        add_metric_suffixes: false
        endpoint: <REDACTED>
        headers:
          X-Scope-OrgID: <REDACTED>
    extensions:
      health_check:
        check_collector_pipeline:
          enabled: false
          exporter_failure_threshold: 5
          interval: 5m
        endpoint: '0.0.0.0:13133'
        path: /
    processors: <REDACTED>
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: dummy
        target_allocator:
          collector_id: '${POD_NAME}'
          endpoint: 'http://otel-metrics-targetallocator:80'
          http_sd_config:
            refresh_interval: 60s
          interval: 30s
    service:
      extensions:
        - health_check
      pipelines:
        metrics:
          exporters:
            - prometheusremotewrite
          processors: <REDACTED>
          receivers:
            - prometheus
      telemetry:
        logs:
          encoding: json
          level: info
        metrics:
          address: '0.0.0.0:8888'
          level: basic
  env:
    - name: KUBE_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
  image: <PRIVATE_REGISTRY>/otel/collector:v0.99.0-pr210
  imagePullPolicy: IfNotPresent
  mode: daemonset
  podDisruptionBudget:
    maxUnavailable: 1
  podSecurityContext:
    fsGroup: 65532
    runAsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532
  priorityClassName: system-node-critical
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 20m
      memory: 256Mi
  securityContext:
    capabilities:
      drop:
        - ALL
        - CAP_NET_RAW
    readOnlyRootFilesystem: true
  targetAllocator:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels: <REDACTED>
              topologyKey: topology.kubernetes.io/zone
            weight: 100
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels: <REDACTED>
            topologyKey: kubernetes.io/hostname
    allocationStrategy: per-node
    enabled: true
    filterStrategy: relabel-config
    image: <PRIVATE_REGISTRY>/otel/target-allocator:v0.100.1
    prometheusCR:
      enabled: true
      scrapeInterval: 30s
    replicas: 3
    resources:
      limits:
        memory: 7Gi
      requests:
        cpu: 20m
        memory: 7Gi
    topologySpreadConstraints:
      - labelSelector:
          matchLabels: <REDACTED>
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
  tolerations:
    - effect: NoSchedule
      operator: Exists

```
</details>

<details>
<summary>Generated TA configmap (data block)</summary>

```yaml
 data:                                                                           
   targetallocator.yaml: |                                                       
     allocation_strategy: per-node                                               
     collector_selector:                                                         
       matchlabels:                                                              
         app.kubernetes.io/component: opentelemetry-collector                    
         app.kubernetes.io/instance: <REDACTED>           
         app.kubernetes.io/managed-by: opentelemetry-operator                    
         app.kubernetes.io/part-of: opentelemetry                                
       matchexpressions: []                                                      
     config:                                                                     
       scrape_configs:                                                           
       - job_name: dummy                                                         
     filter_strategy: relabel-config                                             
     prometheus_cr:                                                              
       pod_monitor_selector: null                                                
       scrape_interval: 30s                                                      
       service_monitor_selector: null

```
</details>

## Steps to Reproduce

You can deploy a OTelCol CR with default monitorSelectors, but no need to. I actually want to talk about the expectations (documented as tests), see below.

## Expected Result

Everything is scraped, just as it was the case with v1alpha1.

## Actual Result

Nothing is scraped. When I port-forward to the TA and query `/jobs`, it's empty. That's not the case with v1alpha1.

## Investigation

From v1alpha1 to v1beta1, the configuration of the target allocator's configuration to select specific servicemonitors/podmonitors has changed. It was a `map[string]string` and was changed to a `metav1.LabelSelector`

https://github.com/open-telemetry/opentelemetry-operator/blob/542e67df8fa23f3c1cd013a723d843e929dfb730/apis/v1alpha1/opentelemetrycollector_types.go#L392-L403

https://github.com/open-telemetry/opentelemetry-operator/blob/542e67df8fa23f3c1cd013a723d843e929dfb730/apis/v1beta1/targetallocator_types.go#L33-L42

This changed the meaning of an null, but present configuration. This is stated in the conversion func: `prometheus_cr.pod_monitor_selector shouldn't be nil when selector is empty`

https://github.com/open-telemetry/opentelemetry-operator/blob/542e67df8fa23f3c1cd013a723d843e929dfb730/apis/v1alpha1/convert.go#L182-L188

This change was not properly propagated to the creation of the target allocator's config map:

https://github.com/open-telemetry/opentelemetry-operator/blob/542e67df8fa23f3c1cd013a723d843e929dfb730/internal/manifests/targetallocator/configmap.go#L56-L66

This snippet will write `service_monitor_selector` and `pod_monitor_selector` in all cases. This is only relevant when deploying v1beta1 resources directly and not using the auto-conversion. With no selector set here, we get `null` in the TA's configmap. We write `null` to the map two times, so it's never empty. With this, the TA will not recognize any job. I think the relevant code change is https://github.com/open-telemetry/opentelemetry-operator/commit/c79f185e9492e02f0e340afa94d58439a4a69850, therefore pinging @swiatekm-sumo. The interesting part is that even the tests expect the TA's configmap to hold `null` values:

https://github.com/open-telemetry/opentelemetry-operator/blob/542e67df8fa23f3c1cd013a723d843e929dfb730/internal/manifests/targetallocator/configmap_test.go#L61-L63

This was not the case with v1alpha1. With no selectors, those values were simply not present in the configmap. I was unable to track down why the TA reacts to explicit `null` and not present differently. I coded a fix to not write explicit `null`s and deployed it in my cluster, works fine again.

https://github.com/open-telemetry/opentelemetry-operator/compare/main...mikel-jason:opentelemetry-operator:fix/ta-configmap-monitor-selector?expand=1

So I think the expectation and the tests are wrong. We must not write explicit `null`s.

Please comment and tell me if you want my proposed fix as PR.

I also tried adding `matchLabels: {}`, but we deploy via ArgoCD and it worked, but ArgoCD does not like it. I think it's kubernetes-internal auto-conversion of type `labelSelector`, but not sure. If this is the intended behavior, it's a problem for us.

![image](https://github.com/open-telemetry/opentelemetry-operator/assets/52131954/aa1b3c1a-a151-4633-a18a-44a72b2f0f3c)

### Kubernetes Version

1.29

### Operator version

v0.100.1

### Collector version

-

## Environment
Target Allocator v0.100.1
