### ISSUE TITLE
TargetAllocator return scrape_configs but no jobs

### ISSUE THREAD

**Issue by andresrsanchez** [open-telemetry/opentelemetry-operator#3011]
### Component(s)

target allocator

## Description
Target allocator service on `/jobs` return an empty list but an expected `scrape_configs`.

## Steps to Reproduce
```yml
targetAllocator:
  allocationStrategy: consistent-hashing
  enabled: true
  filterStrategy: relabel-config
  observability:
    metrics: {}
  podDisruptionBudget:
    maxUnavailable: 1
  prometheusCR:
    enabled: true
    scrapeInterval: 30s
    serviceMonitorSelector: {}
  replicas: 1
  resources: {}
  serviceAccount: xxxxxxxx`
---
receivers:
  prometheus:
    config:
      scrape_configs: []
    target_allocator:
      collector_id: ${POD_NAME}
      endpoint: >-
        http://xxxxx.yyyyy.svc:80
      http_sd_config:
        refresh_interval: 60s
      interval: 30s 
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: argo-rollouts-metrics
    release: prometheus
  name: argocd-metrics
spec:
  endpoints:
    - honorLabels: true
      path: /metrics
      port: metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - argo-rollouts
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts

```

## Expected Result

With 0.80 collector version (0.33.0 operator helm chart) it returned the expected in allocator service `/job` -> `serviceMonitor/argo-rollouts/argocd-metrics/0`. 

## Actual Result

No errors in targetAllocator pod logs.

```json
/jobs -> {}
/scrape_configs -> {
  "serviceMonitor/argo-rollouts/argocd-metrics/0": {
    "enable_compression": true,
    "enable_http2": true,
    "follow_redirects": true,
    "honor_timestamps": true,
    "job_name": "serviceMonitor/argo-rollouts/argocd-metrics/0",
    "metric_relabel_configs": [
      {
        "action": "keep",
        "regex": "(metricxxx)",
        "replacement": "$1",
        "separator": ";"
      }
    ],
    "metrics_path": "/metrics",
    "scheme": "http",
    "scrape_interval": "1m",
    "scrape_protocols": [
      "OpenMetricsText1.0.0",
      "OpenMetricsText0.0.1",
      "PrometheusText0.0.4"
    ],
    "scrape_timeout": "10s",
    "track_timestamps_staleness": false
  }
}
```

### Kubernetes Version

1.29.3

### Operator version

v0.61.0 helm chart

### Collector version

v0.101.0

### Log output

```shell
Logs in collector pod.

info	prometheusreceiver@v0.101.0/metrics_receiver.go:253	Scrape job added	{"kind": "receiver", "name": "prometheus", "data_type": "metrics", "jobName": "serviceMonitor/argo-rollouts/argocd-metrics/0"}
```

**Comment by andresrsanchez** [comment]
> that is a very old version of the operator? is that the helm chart version or the actual operator version?

the [helm chart version](https://github.com/open-telemetry/opentelemetry-helm-charts/releases/tag/opentelemetry-operator-0.61.0) sorry. We have reverted to 0.33.0 chart version and everything is working as expected with a default scrape_config

**Comment by jaronoff97** [comment]
Definitely something we should look into, if you could make a minimal repro for us to go off of that is close to your initial configuration that would be very helpful! Thank you :bow:

**Comment by andresrsanchez** [comment]
Here is the repro:

opentelemetry operator/collector version: 0.101.0
opentelemetry operator helm chart version: 0.61.0

With namespaces, just in case
`
kubectl create namespace temp && kubectl create sa everything-prometheus-operator-needs -n temp
`
```yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-targetallocator-role
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs: ["get", "list", "watch"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  - podmonitors
  verbs:
  - '*'
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-targetallocator-rolebinding
subjects:
  - kind: ServiceAccount
    name: everything-prometheus-operator-needs
    namespace: temp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentelemetry-targetallocator-role
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector-with-ta-prometheus-cr
  namespace: temp
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    serviceAccount: everything-prometheus-operator-needs
    prometheusCR:
      enabled: true
      serviceMonitorSelector: {}
      podMonitorSelector: {}
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
              - targets: [ '0.0.0.0:8888' ]

    exporters:
      debug: {}

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [debug]
---
```
```json
/jobs -> {
   "otel-collector":{"_link":"/jobs/otel-collector/targets"}
}
/scrape_configs -> {
  "serviceMonitor/argo-rollouts/argocd-metrics/0": {
    "enable_compression": true,
    "enable_http2": true,
    "follow_redirects": true,
    "honor_timestamps": true,
    "job_name": "serviceMonitor/argo-rollouts/argocd-metrics/0",
    "metric_relabel_configs": [
      {
        "action": "keep",
        "regex": "(metricxxx)",
        "replacement": "$1",
        "separator": ";"
      }
    ],
    "metrics_path": "/metrics",
    "scheme": "http",
    "scrape_interval": "1m",
    "scrape_protocols": [
      "OpenMetricsText1.0.0",
      "OpenMetricsText0.0.1",
      "PrometheusText0.0.4"
    ],
    "scrape_timeout": "10s",
    "track_timestamps_staleness": false
  }
}
```
No relevant errors in the pod operator or targetallocator pod.
_Collector logs_
`
info	prometheusreceiver@v0.101.0/metrics_receiver.go:253	Scrape job added	{"kind": "receiver", "name": "prometheus", "data_type": "metrics", "jobName": "serviceMonitor/argo-rollouts/argocd-metrics/0"}
`
