### ISSUE TITLE
Allow usage of kubernetes secrets for storing receiver / exporter credentials

### ISSUE THREAD

**Issue by Christian-Schmid** [open-telemetry/opentelemetry-operator#3016]
### Component(s)

collector

Hi,

we're using the Operator to deploy a OpenTelemetryCollector instance publishing data to a Kafka topic. 
The configuration looks like this:

```
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name:otel-exporter
spec:
  config:
    [...]
    exporters:
      kafka:
        protocol_version: 2.0.0
        brokers: ['our-kafka-cluster.confluent.cloud:9092']
        topic: "my.topic"
        encoding: otlp_json
        client_id: "otel-exporter"
        auth:
          plain_text: 
            username: "my-username"
            password: "my-password"
          tls:
              include_system_ca_certs_pool: true
```

We use git ops with [argo cd ](https://argo-cd.readthedocs.io/en/stable/) and [external secrets ](https://external-secrets.io/latest/) to deploy our configuration to the kubernetes cluster. 

We don't want to have the credentials for our Kafka cluster (obviously)  in the git repository.

### Describe the solution you'd like

It would be nice if we could reference a Kubernetes secret to get the actual value for the password. This would work nice together with our external secrets configuration. 

Thanks a lot!
Cheers Chris

**Comment by swiatekm-sumo** [comment]
Would mounting the values from your Secrets as env variables using [envFrom](https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollectorspecenvfromindex), and then referencing those variable in Otel config, work?

**Comment by Christian-Schmid** [comment]
Hi, 

thanks for the hint. Works like a charm :-)

For anyone else having the same question, my config now looks like this:

Kubernetes Secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: otel-collector-kafka-secret
  namespace: my-namespace
data:
  KAFKA_API_KEY: <MySecret>
  KAFKA_API_SECRET: <MySecret>
```

Otel Collector config:
```
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector
  namespace: opentelemetry
spec:
  envFrom:
    - secretRef:
        name: otel-collector-kafka-secret
        
  config:
    receivers:
      kafka:
        protocol_version: 2.0.0
        brokers: ["my.broker.cloud:9092"]
        topic: "opentelemetry.traces"
        group_id: "opentelemetry.collector"
        client_id: "opentelemetry.collector"
        auth:
          plain_text: 
            username: "${env:KAFKA_API_KEY}"
            password: "${env:KAFKA_API_SECRET}"
          tls:
              include_system_ca_certs_pool: true

```

Thanks again!
Chris
