### ISSUE TITLE
Nested env variables not resolved, unable to use downward API

### ISSUE THREAD

**Issue by tiithansen** [open-telemetry/opentelemetry-operator#3022]
### Component(s)

auto-instrumentation

## Description

We wan't traces to be exporter to OTEL collector running on the same host/node. For that purpose we use downward API to get `status.hostIP` and reference it in `OTEL_EXPORTER_OTLP_ENDPOINT` end, but OTEL operator does not resolve it and exporter gets invalid IP.

## Steps to Reproduce

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
spec:
  propagators:
  - tracecontext
  - baggage
  sampler:
    type: parentbased_traceidratio
    argument: {{ .Values.instrumentation.sampler.parentbased_traceidratio | quote }}
  env:
  - name: OTEL_BSP_MAX_EXPORT_BATCH_SIZE
    value: "512"
  - name: OTEL_EXPORTER_HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  nodejs:
    env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://$(OTEL_EXPORTER_HOST_IP):4317"
```

## Expected Result

Env `OTEL_EXPORTER_OTLP_ENDPOINT` should contain correct address with host ip.

## Actual Result

Env `OTEL_EXPORTER_OTLP_ENDPOINT` contains string as `http://$(OTEL_EXPORTER_HOST_IP):4317` instead which is not resolved.

### Kubernetes Version

1.28

### Operator version

version: 0.47.0 appVersion: 0.93.0

### Collector version

Custom
