### ISSUE TITLE
regex wildcards via target allocator not matching

### ISSUE THREAD

**Issue by fredrikgh** [open-telemetry/opentelemetry-operator#3051]
### Component(s)

collector, target allocator

## Description

There appears to be discrepancy between how the otel-collector eventually filter Prometheus metrics based on a `ServiceMonitor` via Target allocator (TA), compared to a vanilla Prometheus instance. Truthfully, I don't know if this issue belongs here or in the collector, more in additional context below.

## Steps to Reproduce

1. Set up a workload to monitor, in my case Mimir.
2. Set up a simple `ServiceMonitor`, and specify a `drop` action using wildcards e.g:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mimir-service-monitor
spec:
  endpoints:
    - interval: 30s
      port: http
      path: /metrics
      metricRelabelings:
        - action: drop
          sourceLabels: [__name__]
          regex: .*bucket.*
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
```
3. Set up two Prometheus instances:
    A: being written to by an otel-collector fetching targets from above `ServiceMonitor` using TA.
    B: fetching targets from the `ServiceMonitor` using the `serviceMonitorSelector` field of the `Prometheus` CRD, disabled `remoteWriteReceiver`.
5. Enter the Prometheus UI of both, and search for `cortex_bucket`.
6. Compare results.

## Expected Result

![image](https://github.com/open-telemetry/opentelemetry-operator/assets/7817071/270bfb75-3551-42d2-9a89-b7e772647e3d)

This is the result I'm getting from B, i.e. no metrics containing `bucket` were fetched.

## Actual Result

![image](https://github.com/open-telemetry/opentelemetry-operator/assets/7817071/95059d14-87e3-4807-b6b0-3c554d897c50)

This is the result I'm getting from A, i.e. all metrics were fetched.

### Kubernetes Version

v1.29.2

### Operator version

v0.102.0

### Collector version

v0.102.1

## Environment
OS: (e.g., "Ubuntu 22.04")

### Additional context

Some additional notes:

1. TA appears to respond with the correct values on `/scrape_configs`, so it may be that any error happens after that point.

![image](https://github.com/open-telemetry/opentelemetry-operator/assets/7817071/1c835570-fe68-4c9a-bbdf-60b5a52e712b)

2. We see other RegEx wildcards working, which is especially odd. E.g. this does correctly keep `kube_daemonset.*` metrics:

![image](https://github.com/open-telemetry/opentelemetry-operator/assets/7817071/9f934e61-ca35-445f-8f42-ffa01cd50739)
