### ISSUE TITLE
v1beta1: operator forces processor configuration

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-operator#3081]
### Component(s)

collector

## Description

I tried to create a simple opentelemetry collector receiving `otlp/gRPC` and `otlp/http` signals and forward them to a `debug` exporter.

### Config
```yaml
kind: OpenTelemetryCollector
apiVersion: opentelemetry.io/v1beta1
metadata:
  name: gateway
  namespace: edge-observability
spec:
  config:
    exporters:
      debug: {}
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    service:
      pipelines:
        traces:
          exporters:
            - debug
          receivers:
            - otlp
```
### apply
```
$ kubectl apply -f gateway.yaml 
The OpenTelemetryCollector "gateway" is invalid: spec.config.service.pipelines.traces.processors: Invalid value: "null": spec.config.service.pipelines.traces.processors in body must be of type array: "null"
```

## Expected Result

Collector will be created.

## Actual Result

Webhook blocks creation.

### Kubernetes Version

v1.28.7+c1f5b34 (OpenShift 4.15.9)

### Operator version

v0.102.0  (upstream)

### Collector version

v0.102.0  (upstream)

## Environment
Installed via operator hub
