### ISSUE TITLE
Provide secrets in config scopes

### ISSUE THREAD

**Issue by PandeoF1** [open-telemetry/opentelemetry-operator#3085]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

My problem is that i can't put secrets in the `config` scopes of my collector.

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: cos # Otel add -collector to the name
  labels:
    app.kubernetes.io/name: otel
    app.kubernetes.io/component: otel-collector
spec:
  mode: deployment
  serviceAccount: opentelemetry-operator
  config:
[...]
    extensions:
      basicauth/client:
        client_auth:
          password: my-incredible-password
          username: admin
[...]
```
I want to provide a secrets to the key `password`, because i don't want to have a clear password in my deployment.
We can't use the valuesFrom / passwordFrom because the key are directly passed into the configuration of the collector

### Describe the solution you'd like

I want to have a way to provide secrets to this key (or to any key that exist).

### Describe alternatives you've considered

Have a clear password in the deployment ( :( )

### Additional context

I have made some research and test a lot of way to put the secrets. It's really possible that there is already a way to put the secrets in this fields but i didn't find it..
