### ISSUE TITLE
When using multiple collector instances, it's impossible to collect self metrics from all collectors.

### ISSUE THREAD

**Issue by lzpfmh** [open-telemetry/opentelemetry-operator#3099]
### Component(s)

target allocator

## Description
When configuring multiple collectors in a K8s cluster, with the following configurations, in practice, metrics can only be collected from only one collector node.
## Steps to Reproduce

>   config: |
    extensions:
      pprof:    
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'nonk8s-otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets: ['0.0.0.0:8888']

the  target 0.0.0.0:8888 will be assigned to only one collector node, other collector nodes do not gather their own metrics.

## Expected Result
To get metric data exposed by all collectors on port 8888.
## Actual Result
Metrics from only one collector can be obtained.

### Kubernetes Version

1.26

### Operator version

v0.104.0

### Collector version

v0.104.0

## Environment
OS: Linux master1 5.15.13-1.el7.elrepo.x86_64 #1 SMP Tue Jan 4 17:33:28 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jlcrow** [comment]
@lzpfmh I just expose the metrics and then annotate the pod to allow them to be collected via scrape
In the OpenTelemetryCollector spec
```
  podAnnotations:
    sidecar.istio.io/inject: "false"
    prometheus.io/scrape: "true"
    promethios.io/port: "8888"
```    
In the spec.config
```
    service:
      telemetry:
        metrics:
          address: "${MY_POD_IP}:8888"
          level: basic    
        logs:
          level: "warn"  
```
The prometheus kubernetes-pods scrape job, which you probably have already
```
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:               
            - action: keep
              regex: true
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            - action: replace
              regex: (.+)
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
              target_label: __metrics_path__
            - action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $$1:$$2
              source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: node
            - action: drop
              regex: Pending|Succeeded|Failed
              source_labels:
              - __meta_kubernetes_pod_phase 
```
Pod IP is coming from here
``` 
env: 
 - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
```
I don't know if I'm being naive here, but bind to the POD IP and expose the metrics to be scraped by whichever collector is scraping the pod metrics.
