### ISSUE TITLE
Conversion webhook namespace is not updated

### ISSUE THREAD

**Issue by aelmekeev** [open-telemetry/opentelemetry-operator#3110]
## Description

An attempt to upgrade from `0.96` to `0.102` has failed for us with:

```
or: "kubernetes/opentelemetry-operator": error when patching "kubernetes/opentelemetry-operator": conversion webhook for opentelemetry.io/v1alpha1, Kind=OpenTelemetryCollector failed: Post "[https://opentelemetry-operator-webhook-service.system.svc:443/convert?timeout=30s](https://opentelemetry-operator-webhook-service.system.svc/convert?timeout=30s)": service "opentelemetry-operator-webhook-service" not found
```

The issue is in fact that `opentelemetry-operator-webhook-service` is deployed in the `opentelemetry-operator-system` namespace rather than [`system` ](https://github.com/open-telemetry/opentelemetry-operator/blob/251de126e989d3a1e510694a8c008f68e4c50dcf/config/crd/patches/webhook_in_opentelemetrycollectors.yaml#L12).

My guess is that it's because of incorrect path [here](https://github.com/open-telemetry/opentelemetry-operator/blob/v0.102.0/config/crd/kustomizeconfig.yaml#L8) which should be `/spec/conversion/webhook/clientConfig/service/namespace` and indeed this custom patch resolved an issue for us:

```yaml
  - target:
      kind: CustomResourceDefinition
      name: opentelemetrycollectors.opentelemetry.io
    patch: |-
      - op: replace
        path: /spec/conversion/webhook/clientConfig/service/namespace
        value: opentelemetry-operator-system
```

## Steps to Reproduce

Upgrade otel collector operator from `0.96` to `0.102`. Although I don't quite understand yet why others did not complain.

## Expected Result

Successul upgrade.

## Actual Result

Kube apply fails with `conversion webhook for opentelemetry.io/v1alpha1, Kind=OpenTelemetryCollector failed`

### Kubernetes Version

1.29.4

### Operator version

0.102.0

### Collector version

0.102.0

## Environment
N/A

### Log output

```shell
or: "kubernetes/opentelemetry-operator": error when patching "kubernetes/opentelemetry-operator": conversion webhook for opentelemetry.io/v1alpha1, Kind=OpenTelemetryCollector failed: Post "[https://opentelemetry-operator-webhook-service.system.svc:443/convert?timeout=30s](https://opentelemetry-operator-webhook-service.system.svc/convert?timeout=30s)": service "opentelemetry-operator-webhook-service" not found
```
```


### Additional context

_No response_

**Comment by pavolloffay** [comment]
@aelmekeev how did you install the operator?

**Comment by aelmekeev** [comment]
@pavolloffay we are doing something like this:

crds

```yaml
commonLabels:
  app.kubernetes.io/name: opentelemetry-operator

resources:
  - https://github.com/open-telemetry/opentelemetry-operator//config/crd?ref=v0.102.0
```

operator itself applied after crds

```yaml
namespace: opentelemetry-operator-system

resources:
  - https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.102.0/opentelemetry-operator.yaml
```
