### ISSUE TITLE
target allocator discover ignore the __address__ in prometheus receiver config

### ISSUE THREAD

**Issue by Tiremisu** [open-telemetry/opentelemetry-operator#3145]
### Component(s)

target allocator

## Description
target allocator discover ignore the __address__ in prometheus receiver config
## Steps to Reproduce
config the target  allocator with following
```
config:
  global:
    scrape_interval: 30
  scrape_configs: 
    ## scraping metrics basing on annotations:
    ##   - prometheus.io/scrape: true - to scrape metrics from the pod
    ##   - prometheus.io/path: /metrics - path which the metric should be scrape from
    ##   - prometheus.io/port: 9113 - port which the metric should be scrape from
    ## rel: https://github.com/prometheus-operator/kube-prometheus/pull/16#issuecomment-424318647
    - job_name: "pod-annotations"
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - source_labels: [__metrics_path__]
          separator: ;
          regex: (.*)
          target_label: endpoint
          replacement: $1
          action: replace
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: namespace
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_pod_name]
          separator: ;
          regex: (.*)
          target_label: pod
          replacement: $1
          action: replace
```
## Expected Result

TA will discover that targets with port in __meta_kubernetes_pod_annotation_prometheus_io_port, eg, 9113 instead of discover targets with ports expose by the container, like 8080

## Actual Result

it discover all targets with ports exposed by the container, eg, if the pod expose 14250, 4317, but the metric port is 9113,
targets discover are:

1.  pod_ip:14250
2. pot_ip:4317

### Kubernetes Version

1.28.7

### Operator version

0.49.0/

### Collector version

adot-operator-targetallocator:0.94.1

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell
A bunch of warn log in the collector side:

Failed to scrape prometheus endpoint....
```

### Additional context

We deployed two operators,  one is adot-operator and the other one is opentelemetry-operator, current using is opentelemetry-operator with aws images...

**Comment by Tiremisu** [comment]
/job:
![image](https://github.com/user-attachments/assets/7abe3616-f695-4acd-ada8-31d35c80ad2b)

targets discover:
![image](https://github.com/user-attachments/assets/f92d6e5b-f0ff-4c00-994d-354317ab5ba0)

target allocator logs (no errors)
...successfully started a collector pod watcher
...successfully started a collector pod watcher
...successfully started a collector pod watcher
```


Collector logs:
![image](https://github.com/user-attachments/assets/01597ffc-6d8e-49ee-b82c-3e4d8f06029e)

**Comment by jaronoff97** [comment]
This is expected as the TA is not returning the relabel config in its response to the collector (though we internally may run the relabel config) so it's expected for the collector to do this itself. Are you seeing the collector failing to scrape the expected targets?

**Comment by Tiremisu** [comment]
@jaronoff97  I mean the TA does not discover the correct port/endpoint!  Let's say in the screenshot above, the TA should discover endpoint 10.12.195.160:**9091** instead of  10.12.195.160:_9900_. We expose /metrics at 9091. So when the TA pass this wrong endpoint to metric collector, it says failed to the prometheus endpoint. 

 Target discover should find the correct prometheus endpoint, right?

**Comment by swiatekm** [comment]
> @jaronoff97 I mean the TA does not discover the correct port/endpoint! Let's say in the screenshot above, the TA should discover endpoint 10.12.195.160:**9091** instead of 10.12.195.160:_9900_. We expose /metrics at 9091. So when the TA pass this wrong endpoint to metric collector, it says failed to the prometheus endpoint.
> 
> Target discover should find the correct prometheus endpoint, right?

It does discover the correct port and endpoint. You later want to modify what it discovered, and use the port from the annotation instead of the port exposed by the container. **This is currently not done by the target allocator, but rather the collector.** The collector will get the target labels as exposed by the target allocator, apply your relabelling steps, and then actually scrape the target.

Unless the collector is not actually scraping the correct targets, this is working as intended.

As an aside, we would like to make the target allocator work the way you expect it to, but this is unfortunately more complicated than one would naively expect.

**Comment by Tiremisu** [comment]
@swiatekm Thanks for the explanation. Will try to add relabeling steps.  Could you also link me the guide?

**Comment by jaronoff97** [comment]
the collector should already be doing the relabel config you have provided, i know you linked the target allocator config above, but could you also link the collector CRD you are using?

**Comment by Tiremisu** [comment]
> the collector should already be doing the relabel config you have provided, i know you linked the target allocator config above, but could you also link the collector CRD you are using?

I am using opentelemetry-operator 0.98.0

**Comment by jaronoff97** [comment]
okay, can you also link the collector configuration?

**Comment by Tiremisu** [comment]
```
    exporters:
      otlphttp:
        disable_keep_alives: true
        endpoint: http://${METADATA_METRICS_SVC}.${NAMESPACE}.svc.cluster.local.:4318
        sending_queue:
          num_consumers: 10
          queue_size: 10000
          storage: file_storage
    extensions:
      file_storage:
        compaction:
          directory: /tmp
          on_rebound: true
        directory: /var/lib/storage/otc
        timeout: 10s
      health_check: {}
      pprof: {}
    processors:
      batch:
        send_batch_max_size: 2000
        send_batch_size: 1000
        timeout: 1s
      filter/drop_stale_datapoints:
        metrics:
          datapoint:
          - flags == FLAG_NO_RECORDED_VALUE
      transform/drop_unnecessary_attributes:
        error_mode: ignore
        metric_statements:
        - context: resource
          statements:
          - delete_key(attributes, "http.scheme")
          - delete_key(attributes, "net.host.name")
          - delete_key(attributes, "net.host.port")
          - delete_key(attributes, "service.instance.id")
          - delete_matching_keys(attributes, "k8s.*")
      transform/extract_sum_count_from_histograms:
        error_mode: ignore
        metric_statements:
        - context: metric
          statements:
          - extract_sum_metric(true) where IsMatch(name, "^(apiserver_request_duration_seconds|coredns_dns_request_duration_seconds|kubelet_runtime_operations_duration_seconds)$")
          - extract_count_metric(true) where IsMatch(name, "^(apiserver_request_duration_seconds|coredns_dns_request_duration_seconds|kubelet_runtime_operations_duration_seconds)$")
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: 30s
          scrape_configs:
          - job_name: pod-annotations
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - action: keep
              regex: true
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            - action: replace
              regex: (.+)
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
              target_label: __metrics_path__
            - action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
              target_label: __address__
            - action: replace
              regex: (.*)
              replacement: $1
              separator: ;
              source_labels:
              - __metrics_path__
              target_label: endpoint
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: namespace
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              regex: (.*)
              replacement: $1
              separator: ;
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: pod
          - authorization:
              credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            honor_labels: true
            job_name: kubelet
            kubernetes_sd_configs:
            - role: node
            metric_relabel_configs:
            - action: keep
              regex: (?:kubelet_docker_operations_errors(?:|_total)|kubelet_(?:docker|runtime)_operations_duration_seconds_(?:count|sum)|kubelet_running_(?:container|pod)(?:_count|s)|kubelet_(:?docker|runtime)_operations_latency_microseconds(?:|_count|_sum))
              source_labels:
              - __name__
            - action: labeldrop
              regex: id
            relabel_configs:
            - source_labels:
              - __meta_kubernetes_node_name
              target_label: node
            - replacement: https-metrics
              target_label: endpoint
            - action: replace
              source_labels:
              - __metrics_path__
              target_label: metrics_path
            - action: replace
              source_labels:
              - __address__
              target_label: instance
            scheme: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
          - authorization:
              credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            honor_labels: true
            job_name: cadvisor
            kubernetes_sd_configs:
            - role: node
            metric_relabel_configs:
            - action: replace
              regex: .*
              replacement: kubelet
              source_labels:
              - __name__
              target_label: job
            - action: keep
              regex: (?:container_cpu_usage_seconds_total|container_memory_working_set_bytes|container_fs_usage_bytes|container_fs_limit_bytes|container_cpu_cfs_throttled_seconds_total|container_network_receive_bytes_total|container_network_transmit_bytes_total)
              source_labels:
              - __name__
            - action: drop
              regex: (?:container_cpu_usage_seconds_total|container_memory_working_set_bytes|container_fs_usage_bytes|container_fs_limit_bytes);$
              source_labels:
              - __name__
              - container
            - action: labelmap
              regex: container_name
              replacement: container
            - action: drop
              regex: POD
              source_labels:
              - container
            - action: labeldrop
              regex: (id|name)
            metrics_path: /metrics/cadvisor
            relabel_configs:
            - replacement: https-metrics
              target_label: endpoint
            - action: replace
              source_labels:
              - __metrics_path__
              target_label: metrics_path
            - action: replace
              source_labels:
              - __address__
              target_label: instance
            scheme: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
    service:
      extensions:
      - health_check
      - pprof
      - file_storage
      pipelines:
        metrics:
          exporters:
          - otlphttp
          processors:
          - batch
          - filter/drop_stale_datapoints
          - transform/extract_sum_count_from_histograms
          - transform/drop_unnecessary_attributes
          receivers:
          - prometheus
      telemetry:
        logs:
          level: info
        metrics:
          address: 0.0.0.0:8888
```
