### ISSUE TITLE
Don't reformat OTEL Collector configuration

### ISSUE THREAD

**Issue by flux-ricky** [open-telemetry/opentelemetry-operator#3162]
### Describe the issue you're reporting

I am using the opentelemetry-operator-0.64.4 Helm chart and it appears that the OTEL Collector config in the field `spec.config` is being reformatted when accepted into the cluster.

We are using ArgoCD which compares the state of the a git repository against the resource in the cluster, and it detects formatting differences. Maintaining this ordering is a pain to do manually, and also I would prefer to order my configuration in a more meaningful way than what the auto formatting does (receivers, processors, exporter, in that order), could this formatting be disabled or made configurable?

If it exists for good reason, can the formatting please be described so that we can lint our configuration before submitting to the cluster.

Given this config:

```yaml
receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}
  zipkin: {}

processors:
  batch: {}

exporters:
  otlphttp:
    endpoint: https://example.com:8080

extensions:
  health_check: {}

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
```

it is reformatted and seen in the cluster as:

```yaml
receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}
  zipkin: {}
exporters:
  otlphttp:
    endpoint: https://example.com:8080
processors:
  batch: {}
extensions:
  health_check: {}
service:
  extensions:
    - health_check
  pipelines:
    traces:
      exporters:
        - otlphttp
      processors:
        - batch
      receivers:
        - otlp
```

ArgoCD then thinks the resource is out of sync and patches it repeatedly as it never reaches the desired state. This is a screenshot from ArgoCD:

<img width="1049" alt="image" src="https://github.com/user-attachments/assets/5231758b-128f-4d73-b9db-af3f0c7f3c66">
