### ISSUE TITLE
Allow overriding the default collector's image entrypoint

### ISSUE THREAD

**Issue by rogercoll** [open-telemetry/opentelemetry-operator#3188]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

The current API provides a configuration option to specify a custom collector's image, but it assumes that the entrypoint of the container will be the actual collector binary and it cannot be overwritten. That is the case of the OpenTelemetry collector images (core, contrib and k8s), but for distributions or extended images the entrypoint of the container might be different. For example, to launch the binary collector within the `elastic-agent`, an `otel` subcommand mode must be provided: `./elastic-agent otel --config otel.yml`.

This not an issue with the OpenTelemetry Helm as the container's entrypoint can be configured with the `command` value: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml#L180

We use the upstream Helm charts with the following values:

```yaml
image:
  repository: docker.elastic.co/beats/elastic-agent
  tag: 8.15.0-SNAPSHOT
command:
  name: "/usr/share/elastic-agent/elastic-agent"
  extraArgs: ["otel"]
  ```
  
The `command` config option is not availble in the operator, thus we cannot launch the Elastic distribution with the current container's entrypoint. (see also https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/)

### Describe the solution you'd like

Ability to override the container's command:

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: daemonset
spec:
  mode: daemonset
  hostNetwork: true
  image: docker.elastic.co/beats/elastic-agent:8.15.0-SNAPSHOT
  command:
    - /usr/share/elastic-agent/elastic-agent
    - otel
  ```
