### ISSUE TITLE
metricstransform Regexp Config Causes Startup Failure in v0.107.0

### ISSUE THREAD

**Issue by Zurvarian** [open-telemetry/opentelemetry-operator#3262]
**Describe the bug**

Same as with https://github.com/open-telemetry/opentelemetry-collector/issues/10585 but I'm reproducing the issue with version v0.107.0 which supposedly has a fix for it.

Something to notice is that I'm running the Collector as a SideCar created with the Operator, not sure if that affects it somehow.

**Steps to reproduce**

Create a sidecar with the Operator with a config that has variable replacement of a regexp.

**What did you expect to see?**

The variable is replaced correctly

**What did you see instead?**

An error like `cannot resolve the configuration: environment variable "1" has invalid name: must match regex ^[a-zA-Z_][a-zA-Z0-9_]*$`

**What version did you use?**

v0.107.0

**What config did you use?**

```
processors:
      metricstransform:
        transforms:
          - include: (.*)$$
            match_type: regexp
            action: update
            new_name: knative.dev_eventing.$${1}
```

**Environment**

Linux in GCP.

**Additional context**
