### ISSUE TITLE
Support for ingress, endpoints, endpointslice, node discovery for target allocator

### ISSUE THREAD

**Issue by maokitty** [open-telemetry/opentelemetry-operator#3276]
### Component(s)

otel-allocator

### Is your feature request related to a problem? Please describe.

There are multiple role in [kubernetes_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config):
- node
- service
- pod
- endpoints
- endpointslice
- ingress

Target allocator supports service and pod now, is there any plan to support others ?

### Describe the solution you'd like

Support target discovery by node,endpoint,endpointslice,ingress

**Comment by maokitty** [comment]
I'm afraid this is not my original request. 


1. serviceMonitor and podMonitor are selectors that select resources in service or pod dimensions, not endpoints.
2. I believe here can write kubernetes_sd_configs without using either serviceMonitor or podMonitor, but with prometheusreceiver int OTel, only [http_sd](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/targetallocator/manager.go#L140) will be used, so it can not be handled with kubernetes_sd_configs

My request is to use the distribution power of OTel allocator, send different endpoint config to different OTel agent running on k8s node, and scrape the metric in endpoint dimension just like writing kubernetes_sd_config with role endpoint.

By the way, would it be better that OTel allocator respond the instance:port which is behind [endpoints](https://kubernetes.io/docs/concepts/services-networking/service/#endpoints)?

please correct me if i am wrong

**Comment by jaronoff97** [comment]
The http sd config is the rewriting we do so the collector queries the target allocator instead of what was originally configured. The target allocator will still do the service discovery with whatever you set. 

Can you give me an example of what you are expecting the target allocator to do? Im not sure I understand the request unfortunately.

**Comment by maokitty** [comment]
Sure. Let's say I have an endpoint. 
```
apiVersion: v1
kind: Endpoints
metadata:
  name: my-prometheus-endpoint
  labels:
    app: my-app
subsets:
  - addresses:
      - ip: "192.0.2.1"  
      - ip: "192.0.2.2" 
    ports:
      - name: http
        port: 8080  # Prometheus port
```
I could write scrape config like this in OTel allocator
```
scrape_configs:
  - job_name: 'kubernetes-endpoints'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_name]
        action: keep
        regex: my-prometheus-endpoint 
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: default 
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: http  
```
Then when I use the Prometheus receiver in OTel
```
receivers:
  prometheus:
    target_allocator:
      endpoint: http://my-targetallocator-service
      interval: 30s
      collector_id: collector-1
```
Will the target allocator return 192.0.2.1:8080 as my metric target? and every thing works fine?
