### ISSUE TITLE
Wrong marshal for OpenTelemetryCollector

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#3281]
## Description
I'm working on something using the OpenTelemetry Collector API provided by this repository and I found some configuration fields were not marshaled properly.

So, for an OpenTelemetry Collector like this:
```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: instance
  namespace: open-cluster-management-observability
spec:
  config:
    exporters:
      debug:
    processors:
    receivers:
      jaeger:
        protocols:
            grpc:
      otlp:
        protocols:
          grpc:
          http:
    service:
      pipelines:
        traces:
          exporters:
            - debug
          processors: []
          receivers:
            - otlp
            - jaeger
  mode: deployment
```

I can see the `protocols` field from the `otlp` receiver is dropped.

If we try directly in a script, it doesn't reproduce. But it can be reproduced by creating the resource first in Kubernetes, retrieving it, and doing the marshaling.

This seems to be expected from the changes introduced in https://github.com/open-telemetry/opentelemetry-operator/pull/2444
