### ISSUE TITLE
Operator won't allow adding topologySpreadConstraints to otelcol's spec

### ISSUE THREAD

**Issue by douglasqsantosaudibene** [open-telemetry/opentelemetry-operator#3304]
### Component(s)

collector

## Description

When are we trying to apply a patch or a new object with topologySpreadConstraints it fails.

```bash
Error from server (BadRequest): error when creating "~/Downloads/otel-sampler.yaml": OpenTelemetryCollector in version "v1beta1" cannot be handled as a OpenTelemetryCollector: strict decoding error: unknown field "spec.topologySpreadConstraints.labelSelector", unknown field "spec.topologySpreadConstraints.maxSkew", unknown field "spec.topologySpreadConstraints.topologyKey", unknown field "spec.topologySpreadConstraints.whenUnsatisfiable"
```

But we can explain the object, and we have support for it.

```bash
k explain OpenTelemetryCollector.spec.topologySpreadConstraints
GROUP:      opentelemetry.io
KIND:       OpenTelemetryCollector
VERSION:    v1beta1

FIELD: topologySpreadConstraints <[]Object>


DESCRIPTION:
    <empty>
FIELDS:
  labelSelector	<Object>
    <no description>

  matchLabelKeys	<[]string>
    <no description>

  maxSkew	<integer> -required-
    <no description>

  minDomains	<integer>
    <no description>

  nodeAffinityPolicy	<string>
    <no description>

  nodeTaintsPolicy	<string>
    <no description>

  topologyKey	<string> -required-
    <no description>

  whenUnsatisfiable	<string> -required-
    <no description>
```

## Steps to Reproduce

We are using the following YAML file.

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-sampler
  namespace: kube-system
spec:
  config: |
    "exporters":
      "logging":
        "verbosity": "basic"
      "otlp/newrelic":
        "compression": "gzip"
        "endpoint": "otlp.nr-data.net:9999"
        "headers":
          "api-key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    "extensions":
      "health_check": null
      "pprof":
        "endpoint": "0.0.0.0:1777"
      "zpages": null
    "processors":
      "batch":
        "send_batch_size": 10000
        "timeout": "10s"
      "batch/sampled":
        "send_batch_size": 10000
        "timeout": "10s"
      "filter/newrelic_and_otel":
        "error_mode": "ignore"
        "traces":
          "span":
          - "name == \"TokenLinkingSubscriber.withNRToken\""
      "memory_limiter":
        "check_interval": "5s"
        "limit_mib": 3800
        "spike_limit_mib": 1000
      "resourcedetection/system":
        "detectors":
        - "env"
        - "system"
        "override": false
        "timeout": "2s"
      "tail_sampling":
        "decision_wait": "60s"
        "expected_new_traces_per_sec": 10000
        "num_traces": 50000000
        "policies":
        - "name": "always_sample_error"
          "status_code":
            "status_codes":
            - "ERROR"
          "type": "status_code"
        - "and":
            "and_sub_policy":
            - "name": "routes"
              "string_attribute":
                "enabled_regex_matching": true
                "key": "http.route"
                "values":
                - "/health"
                - "/(actuator|sys)/health"
              "type": "string_attribute"
            - "name": "probabilistic-policy"
              "probabilistic":
                "sampling_percentage": 0.1
              "type": "probabilistic"
          "name": "health_endpoints"
          "type": "and"
        - "name": "sample_10_percent"
          "probabilistic":
            "sampling_percentage": 10
          "type": "probabilistic"
        - "latency":
            "threshold_ms": 3000
          "name": "slow-requests"
          "type": "latency"
    "receivers":
      "otlp":
        "protocols":
          "grpc": null
          "http": null
    "service":
      "extensions":
      - "zpages"
      - "health_check"
      - "pprof"
      "pipelines":
        "logs/1":
          "exporters":
          - "otlp/newrelic"
          "processors":
          - "resourcedetection/system"
          - "batch"
          "receivers":
          - "otlp"
        "metrics/1":
          "exporters":
          - "otlp/newrelic"
          - "logging"
          "processors":
          - "resourcedetection/system"
          - "batch"
          "receivers":
          - "otlp"
        "traces/1":
          "exporters":
          - "otlp/newrelic"
          - "logging"
          "processors":
          - "filter/newrelic_and_otel"
          - "resourcedetection/system"
          - "tail_sampling"
          - "batch/sampled"
          "receivers":
          - "otlp"
      "telemetry":
        "metrics":
          "address": "0.0.0.0:8888"
  env:
  - name: GOMEMLIMIT
    value: 3200MiB
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.109.0
  mode: statefulset
  podDisruptionBudget:
    maxUnavailable: 1
  replicas: 7
  resources:
    limits:
      cpu: "4"
      memory: 5000Mi
    requests:
      cpu: 100m
      memory: 4000Mi
  topologySpreadConstraints:
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: otel-sampler-collector
    maxSkew: 2
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
```

## Expected Result

We expect to be able to add the topology spread support to our environment.

## Actual Result

```bash
 k create -f ~/Downloads/otel-sampler.yaml
Error from server (BadRequest): error when creating "~/Downloads/otel-sampler.yaml": OpenTelemetryCollector in version "v1beta1" cannot be handled as a OpenTelemetryCollector: strict decoding error: unknown field "spec.topologySpreadConstraints.labelSelector", unknown field "spec.topologySpreadConstraints.maxSkew", unknown field "spec.topologySpreadConstraints.topologyKey", unknown field "spec.topologySpreadConstraints.whenUnsatisfiable"
```

### Kubernetes Version

1.29

### Operator version

v0.109.0

### Collector version

-

## Environment

We are running on EKS with Opentelemetry default images.
