### ISSUE TITLE
Add support for persistentVolumeClaimRetentionPolicy field in statefulset mode

### ISSUE THREAD

**Issue by dferrochio** [open-telemetry/opentelemetry-operator#3305]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

I'm not able to change the persistentVolumeClaimRetentionPolicy field in statefulset mode. I need to change the default policy to delete the PVC's when the statefulset is scaled.

### Describe the solution you'd like

Solution might be an optional configuration section for the statefulset specs like this:

```
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
spec:
  mode: statefulset
  statefulset:
    spec:
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Delete
```

**Comment by davidhaja** [comment]
I am happy to help with this.
How about instead of adding `statefulset.spec.persistentVolumeClaimRetentionPolicy` to the opentelemetrycollector CRD, the `persistentVolumeClaimRetentionPolicy` would be a just separate field(object) like:
```
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
spec:
  mode: statefulset
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Delete
```
