### ISSUE TITLE
Cannot drop service on Prometheus receiver scraping

### ISSUE THREAD

**Issue by flenoir** [open-telemetry/opentelemetry-operator#3314]
### Component(s)

collector

### Describe the issue you're reporting

Hi, i'm trying to configure prometheus receiver in my collector.
On my collector i activated targetAllocators. i get this error message :
`"│ 2024-09-30T11:55:51.603Z    warn    internal/transaction.go:173    failed to add datapoint    {"kind": "receiver", "name": "prometheus", "data_type": "metrics", "error": "inconsistent timestamps on metric points for metric container_processes", "metric_name": "container_processes", "labels": "{__name__=\"container_processes\", endpoint=\"https-metrics\", instance=\"10.201.1.16:10250\", job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", node=\"y1-dev-workers-az1-7ee7961b-xj8sp\", service=\"operator-stack-kubelet\"}"} "`

i added a config to drop  the service "operator-stack-kubelet"
my config is :

```
  config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 10s
            static_configs:
              - targets: ['0.0.0.0:8888']
          - job_name: apiserver
            authorization:
              credentials_file: "/var/run/secrets/kubernetes.io/serviceaccount/token"
              type: Bearer
            honor_labels: true
            honor_timestamps: true
            kubernetes_sd_configs:
            - follow_redirects: true
              kubeconfig_file: ''
              role: endpoints
            metrics_path: "/metrics"
            follow_redirects: true
            relabel_configs:
            - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
              separator: ;
              regex: default;kubernetes;https
              replacement: $$1
              action: keep
            - source_labels: [__meta_kubernetes_service_name]
              regex: "operator-stack-kubelet"
              action: drop
            scheme: https
            scrape_interval: 20s
            scrape_timeout: 10s
            tls_config:
              ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
              insecure_skip_verify: true
```
 The error message is still present after applying config, what am i doing wrong here ?
