### ISSUE TITLE
[Otel-Operator] Target Allocator is not running as nonroot

### ISSUE THREAD

**Issue by toporek3112** [open-telemetry/opentelemetry-operator#3378]
### Component(s)

target allocator

### Describe the issue you're reporting

When testing the otel-operator setup on an RKE cluster I stumbled upon `Error: container has runAsNonRoot and image will run as root (pod: "otel-targetallocator-78cd5444fc-f5fqh_monitoring(1207-4994-9ce5-fb97246690a4)", container: ta-container)` 

otel-operator helm chart values snipped:
```yaml
                    image:
                      repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
                      tag: 0.108.0
                    collectorImage:
                      repository: "otel/opentelemetry-collector-contrib"
                      tag: 0.108.0
                    targetAllocatorImage:
                      repository: ghcr.io/open-telemetry/opentelemetry-operator/target-allocator
                      tag: 0.108.0
```

If this is intended I will use a custom image. Please let me know.
