### ISSUE TITLE
Support defining auto-instrumentation configuration in configmap, secret for all key-value pairs

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#3392]
### Is your feature request related to a problem? Please describe.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables

```
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: registry.k8s.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: special-config
  restartPolicy: Never
```

The above configuration mounts all configmap/secret keys as env vars to pod. The OTEL operator's pod webhook does not know which keys are mounted and therefore it will not respect them (e.g. `OTEL_` ) or it can even crash the app (it overrides `JAVA_TOOL_OPTIONS`).

The current behavior of the operator is:
* `OTEL_` env vars - it respects what user configures in pod spec
* runtime config e.g. `JAVA_TOOL_OPTIONS` it appends required config by the operator.

### Describe the solution you'd like

There are a couple of possible solutions 

### Read configmap and secret in pod webhook 
https://github.com/open-telemetry/opentelemetry-operator/pull/3373

The most simple implementation could read just the keys of the configmaps/secretes that are mounted as `envFrom.configMapRef` without the key. The operator could put all the keys in a map and if they env var needs to be modified, modify it with new env var and substitution e.g. `JAVA_TOOL_OPTIONS: $(JAVA_TOOL_OPTIONS) new-val`

The downside of this approach is per impact on the webhook - it will make additional API calls during the pod startup. 

### Use custom env vars
We could build custom agents or extension modules that would accept a config file or custom env vars set by the operator and do the resolution at runtime. 

### Additional context

It was discussed at SIG meeting https://docs.google.com/document/d/1Unbs2qp_j5kp8FfL_lRH-ld7i5EOQpsq0I4djkOOSL4/edit?tab=t.0#heading=h.j3a542wavlt6
