### ISSUE TITLE
Upgrade operator, the default auto-instrumentation image in Instrumentation has not been upgraded

### ISSUE THREAD

**Issue by chinaran** [open-telemetry/opentelemetry-operator#3468]
### Component(s)

auto-instrumentation

## Description

Upgrade operator, the default auto-instrumentation image in Instrumentation has not been upgraded

## Steps to Reproduce

operator v0.107.0 was deployed using helm chart, to be migrated to OLM deployment and upgraded to v0.113.0.
Also, the default-auto-instrumentation-java-image version should be upgraded.
When v0.113.0 was deployed after removing v0.107.0, the mutate webhook failed during the [upgrade of Instrumentation](https://github.com/open-telemetry/opentelemetry-operator/blob/main/pkg/instrumentation/upgrade/upgrade.go#L93) because the service was not ready.
As a result, auto-instrumentation-java-image was not upgraded.

## Expected Result

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  annotations:
    instrumentation.opentelemetry.io/default-auto-instrumentation-java-image: xxx-v2
spec:
  java:
    image: xxx-v2
```

## Actual Result

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  annotations:
    instrumentation.opentelemetry.io/default-auto-instrumentation-java-image: xxx-v1
spec:
  java:
    image: xxx-v1
```

### Kubernetes Version

v1.29.2

### Operator version

v0.113.0

### Collector version

v0.108.1

### Log output

```shell
{"level":"ERROR","timestamp":"2024-11-17T03:30:27.899239101Z","logger":"instrumentation-upgrade","message":"failed to apply changes to instance","name":"xxx-java","namespace":"cpaas-system","error":"Internal error occurred: failed calling webhook \"minstrumentation.kb.io\": failed to call webhook: Post \"https://opentelemetry-operator-controller-manager-service.xxx-ns.svc:443/mutate-opentelemetry-io-v1alpha1-instrumentation?timeout=10s\": dial tcp xxx.xxx.xxx.xxx:443: connect: connection refused","stacktrace":
"github.com/open-telemetry/opentelemetry-operator/pkg/instrumentation/upgrade.(*InstrumentationUpgrade).ManagedInstances
/workspace/source/pkg/instrumentation/upgrade/upgrade.go:99
main.addDependencies.func2
/workspace/source/main.go:473
sigs.k8s.io/controller-runtime/pkg/manager.RunnableFunc.Start
/workspace/cache/gomod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/manager/manager.go:307
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1
/workspace/cache/gomod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/manager/runnable_group.go:226"}
```

### Additional context

Should I add retry logic to upgrade Instrumentation?
