### ISSUE TITLE
How to Ignore Internal Spans in OpenTelemetry Instrumentation with Auto-Instrumentation?

### ISSUE THREAD

**Issue by qgervacio** [open-telemetry/opentelemetry-operator#3505]
### Component(s)

auto-instrumentation

### Describe the issue you're reporting

I'm using the OpenTelemetry Operator to configure auto-instrumentation for my Kubernetes application.

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: a-name
spec:
  exporter:
    endpoint: ...
  propagators:
    - tracecontext
    - baggage
    - b3
  nodejs:
    image: ...
    volumeLimitSize: 300Mi

```

I want to ignore internal spans `span.kind: internal` without breaking the relationship. I tried `filter` processor but this creates orphaned spans.

Any guidance or examples would be greatly appreciated. Thanks in advance!

**Comment by jaronoff97** [comment]
Are you referring to a specific instrumentation's internal spans, or _all_ internal spans?

**Comment by qgervacio** [comment]
Hi @jaronoff97. all internal spans

**Comment by jaronoff97** [comment]
I'm not positive there's a way to do this from the instrumentation, i _think_ this may be possible with the [tailsamplingprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor) but i'm not positive. i'm going to ask in slack and see what others think.

**Comment by frzifus** [comment]
The `tailsamplingprocessor` should only help you to select if an entire trace should be sampled or not. I think in that case the [filterprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/421d710d3d8ceb28e375f57109ae976423713f9d/processor/filterprocessor/README.md#dropping-http-spans) might help. But not at the instrumentation level.

```yaml
processors:
  filter:
    error_mode: ignore
    traces:
      span:
        - kind.string == "internal"
```

In principle, spans could be filtered in the code by implementing a [span processor](https://github.com/open-telemetry/opentelemetry-go/blob/ac386f383cdfc14f546b4e55e8726a0a45e8a409/sdk/trace/span_processor.go#L15). Not sure if there is an option to configure some kind of processor to exclude data based on some rules configured as env variable.

Maybe @TylerHelmuth knows something about it?
