### ISSUE TITLE
Environment variable expansion in `spec.config.service.telemetry.metrics.address` doesn't work

### ISSUE THREAD

**Issue by douglascamata** [open-telemetry/opentelemetry-operator#3513]
### Component(s)

collector

## Description

Looks like the shell environment variable expansion breaks config validation when used in  `spec.config.service.telemetry.metrics.address`.

It doesn't break the config validation when used in other places, like `spec.config.receivers.otlp.protocols.grpc.endpoint`.

## Steps to Reproduce

1. Install cert manager operator (optional)
2. Install OTEL operator v0.114.0
3. Try to deploy a collector using the manifest below:

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:POD_IP}:4317
          http:
            endpoint: ${env:POD_IP}:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
    exporters:
      debug: {}
    service:
      telemetry:
        metrics:
          address: ${env:POD_IP}:8888
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
```

## Expected Result

The Collector is created.

## Actual Result

It returns the error `Error from server (Forbidden): error when creating "collector_crd.yaml": admission webhook "mopentelemetrycollectorbeta.kb.io" denied the request: address ${env:POD_IP}:8888: too many colons in address`

### Kubernetes Version

1.31.2

### Operator version

0.114.0

### Collector version

0.114.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Additional context

According to https://github.com/open-telemetry/opentelemetry-helm-charts/blob/831603f1351049a65550ec3211d8e3a44a0c5a2a/charts/opentelemetry-collector/UPGRADING.md#0782-to-0783, it would be a good idea to update all the examples to use `${env:POD_IP}` instead of listening on `0.0.0.0`.

**Comment by PePoDev** [comment]
mine workaround

```yaml
manager:
  env:
    ENABLE_WEBHOOKS: "false"
```
