### ISSUE TITLE
Can't Find Examples Dir Mentioned in README

### ISSUE THREAD

**Issue by brianpham** [open-telemetry/opentelemetry-operator#352]
Hi,

I am looking at various ways to deploy OpenTelemetryCollector and in the README it mentions to take a look at`examples/daemonset.yaml` but I don't see it it in this repo. 

https://github.com/open-telemetry/opentelemetry-operator#deployment-modes

**Comment by VineethReddy02** [comment]
Hi @brianpham 

Thanks for pointing this out it looks like while restructuring the repo, we dropped this file and forgot to update the docs. 

I will update the docs accordingly.

To run collector as daemonset, all you have to configure is:

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: daemonset-collector
spec:
  mode: daemonset
config: |
...
```
