### ISSUE TITLE
OpenTelemetryCollector v1beta1, nulls get dropped

### ISSUE THREAD

**Issue by NickLarsenNZ** [open-telemetry/opentelemetry-operator#3543]
### Component(s)

collector

## Description

The collector fails to start when migrating from `v1alpha1` to `v1beta1` using the following procedure:
- Change the `apiVersion` to `opentelemetry.io/v1beta1`.
- Remove the `|` from `spec.config`, turning the value from a string to an object.

## Steps to Reproduce

```yml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: kubernetes-events
spec:
  config:
    receivers:
      # without {}, as per most examples
      k8s_events:

    exporters:
      debug: {}

    service:
      pipelines:
        logs:
          receivers: [k8s_events]
          exporters: [debug]
```

## Expected Result

The collector should start up, and its ConfigMap should show the receivers (and other things enabled without additional config)

```yml
apiVersion: v1
kind: ConfigMap
data:
  collector.yaml: |
    receivers:
      k8s_events: {}
...
```

Or, I'd expect the webhook to tell my the configuration is invalid.

## Actual Result

The collector fails to start with: "no receiver configuration specified in config". The webhooks doesn't pick this up.

The generated ConfigMap ends up with an empty `receivers` section:

```yml
apiVersion: v1
kind: ConfigMap
data:
  collector.yaml: |
    receivers: {}
...
```

### Kubernetes Version

1.31.0

### Operator version

0.114.1

### Collector version

0.114.0 (otel/opentelemetry-collector-k8s:0.114.0)

## Environment
OS: Nixos

### Log output

```shell
Error: invalid configuration: no receiver configuration specified in config
2024/12/12 17:14:36 collector server run finished with error: invalid configuration: no receiver configuration specified in config
Stream closed EOF for default/local-kubernetes-events-collector-7bddd5d6bb-7mhjb (otc-container)
```

### Additional context

It works if I change the `spec.config` to a string config, and use `v1alpha`.
It also works if I add `{}` so that the `k8s_events` receiver doesn't default to null.
