### ISSUE TITLE
Pod is not created with Apache auto-instrumentation

### ISSUE THREAD

**Issue by L3o-pold** [open-telemetry/opentelemetry-operator#3547]
### Component(s)

auto-instrumentation

## Description

Pod is not created with Apache auto-instrumentation

## Steps to Reproduce

k3s cluster v1.31.3+k3s1

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x
  labels:
    app.kubernetes.io/name: x
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: x
  template:
    metadata:
      labels:
        app.kubernetes.io/name: x
      annotations:
        sidecar.opentelemetry.io/inject: 'true'
        instrumentation.opentelemetry.io/inject-apache-httpd: "true"
        instrumentation.opentelemetry.io/apache-httpd-container-names: "apache"
    spec:
      containers:
        - image: x
          imagePullPolicy: IfNotPresent
          name: apache
          readinessProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          lifecycle:
            preStop:
              exec:
                command: [ "apachectl", "-k", "graceful-stop" ]
```

## Expected Result

Pod creating successfully 

## Actual Result

Pod are never created with the following error:

`Error creating: Pod "x-6c4dfc6c6c-t9p24" is invalid: spec.initContainers[1].lifecycle: Forbidden: may not be set for init containers without restartPolicy=Always`

### Kubernetes Version

v1.31.3+k3s1

### Operator version

0.114.1

### Collector version

0.115.1

## Environment

OS: Ubuntu 22.04.5 LTS

### Additional context

It worked with Nginx auto-instrumentation but not with Apache
