### ISSUE TITLE
failed to mount volume for mtls cert for target allocator

### ISSUE THREAD

**Issue by travisghansen** [open-telemetry/opentelemetry-operator#3563]
### Component(s)

collector, target allocator

## Description

When mtls support is enabled in the operator deployments that do *not* have target allocator enabled are failing because the secret does not exist:

`MountVolume.SetUp failed for volume "default-ta-client-cert" : secret "default-ta-client-cert" not found`

The secret isn't being created (presumably) because target allocator isn't enabled on the CR but the `deployment` is still requiring the mount. 

## Steps to Reproduce

Enable mtls for TA. Deploy a collector without TA enabled.

## Expected Result

No mtls secrets are created, no secrets are required to start the collector.

## Actual Result

TLS secrets are not created (as expected when TA is disabled), secret is required by the collector pod to start.

### Kubernetes Version

1.31

### Operator version

ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:0.114.1

### Collector version

otel/opentelemetry-collector-k8s:0.114.0

### Additional context

https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1469

**Comment by mtthwcmpbll** [comment]
I've run into this too.  It seems like enabling the mtls feature flag to support mTLS for OtelCollectors with Target Allocator enabled _also_ forces all OtelCollector resources to also have the targetAllocator enabled.  I have a Collector resource deployed that explictly sets:
```
spec:
  targetAllocator:
    enabled: false
```

The Collector's pod fails to initialize because the expected secret volume mount doesn't exist, and describing the OtelCollector resource I see the following:
```
spec
  targetAllocator:
    allocationStrategy: consistent-hashing
    filterStrategy: relabel-config
    observability:
      metrics: {}
    prometheusCR:
      scrapeInterval: 30s
    resources: {}
```
