### ISSUE TITLE
[instrumentation] Support setting image pull policy for agent images

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-operator#3575]
### Component(s)

auto-instrumentation

### Is your feature request related to a problem? Please describe.

The current setup relies on the default behavior of kubernetes imagePullPolicy as it is not set explicitly.

### Describe the solution you'd like

Add a field to the instrumentation CRDs and config flags to support setting image pull policies globally or per instrumentation.

**Comment by swiatekm** [comment]
:+1: I'm in favor of adding this.

**Comment by yuriolisa** [comment]
Would the idea be like the following?

```yaml
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  imagePullPolicy: Always
  python:
    imagePullPolicy: IfNotPresent
    env:
      # Required if endpoint is set to 4317.
      # Python autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4317.
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318
```

If so, would you have interest to send a PR or can I work on this one?
