### ISSUE TITLE
Simplify Instrumentation exporter endpoint configuration

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#3658]
### Component(s)

auto-instrumentation

### Is your feature request related to a problem? Please describe.

The instrumentation CR exporter endpoint 
```
spec:
  exporter:
    endpoint: http://otel-collector:4317
```

can take both gRPC (4317) and HTTP (4318) OTLP endpoints. Some instrumentation implementations default to grpc (java 1.x, node). Which is confusing because a single instrumentation CR can be used for all instrumentation at one and therefore users have to override the endpoint via an env variable:

```yaml
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  python:
    env:
      # Required if endpoint is set to 4317.
      # Python autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4317.
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318
  dotnet:
    env:
      # Required if endpoint is set to 4317.
      # Dotnet autoinstrumentation uses http/proto by default
      # See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/888e2cd216c77d12e56b54ee91dafbc4e7452a52/docs/config.md#otlp
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318
  go:
    env:
      # Required if endpoint is set to 4317.
      # Go autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4317.
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318
EOF
```

### Describe the solution you'd like

Make the exporter endpoint protocol aware e.g. 

```yaml
spec:
  exporter:
    // deprecated
    endpoint:
    otlpHTTP: http://otel-collector:4318
    otlpGRPC: http://otel-collector:4317
```
