### ISSUE TITLE
Support specifying `otel-python-platform` per container

### ISSUE THREAD

**Issue by mindw** [open-telemetry/opentelemetry-operator#3685]
### Component(s)

auto-instrumentation

### Is your feature request related to a problem? Please describe.

Multi container pods with mixed python platforms cannot be instrumented.

### Describe the solution you'd like

if `enable-multi-instrumentation` is enabled,
`otel-python-platform-container-<platform>: <container>[,container]*` where `platform` is one of the supported platforms - currently `glibc` and `musl`
If the above is omitted for a container then value of `otel-python-platform` is used for all containers.
for example:
```
annotations:

  instrumentation.opentelemetry.io/inject-python: "true"
  instrumentation.opentelemetry.io/python-container-names: "myapp2,myapp3"
  instrumentation.opentelemetry.io/otel-python-platform-container-musl: "myapp3"
```

### Additional context

Support for musl annotations was introduced in https://github.com/open-telemetry/opentelemetry-operator/pull/3332
