### ISSUE TITLE
`health_check` doesn't work

### ISSUE THREAD

**Issue by JorTurFer** [open-telemetry/opentelemetry-operator#3688]
### Component(s)

collector

## Description

Upgrading the operator I have noticed that since v0.104.0, the extension `health_check` doesn't work because the probes fail all the time

## Steps to Reproduce

1. Install the operator v0.117.0 (but this happens since v0.104.0)
2. deploy this yaml (just copied from the readme and added the health-check extension)
```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector-with-ta
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
  config:
    extensions:
      health_check: {}
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 10s
            static_configs:
            - targets: [ '0.0.0.0:8888' ]
            metric_relabel_configs:
            - action: labeldrop
              regex: (id|name)
            - action: labelmap
              regex: label_(.+)
              replacement: $$1
    exporters:
      debug: {}
    service:
      extensions:
        - health_check
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [debug]
```

## Expected Result
The collector starts

## Actual Result
The collector doesn't start because the probes return 502

### Kubernetes Version

1.29 and 1.31

### Operator version

0.104.0

### Collector version

0.104.0

### Log output

```shell
Pod logs:


Pods
13 items
Namespaces: nginx, autoinstrumentation-nginx, opentelemetry-operator, opentelemetry-collector, default
Search Pods...
opentelemetry-targetallocator-7d5854b7f5-lpbrx
opentelemetry-collector
0
ReplicaSet
shoot--be6a452d50--idp-ske-tst-system-z3-8475c-5c7kt
Burstable
2m3s
Running
opentelemetry-collector-1
opentelemetry-collector
2
StatefulSet
shoot--be6a452d50--idp-ske-tst-system-z1-57d9d-8r6br
Burstable
2m17s
Running
collector-with-ta-collector-0
default
4
StatefulSet
shoot--be6a452d50--idp-ske-tst-system-z1-57d9d-8r6br
BestEffort
2m18s
Running
opentelemetry-targetallocator-7d5854b7f5-xv76m
opentelemetry-collector
0
ReplicaSet
shoot--be6a452d50--idp-ske-tst-system-z1-57d9d-8r6br
Burstable
2m18s
Running
collector-with-ta-targetallocator-b89ccdb5-r8nsf
default
0
ReplicaSet
shoot--be6a452d50--idp-ske-tst-system-z1-57d9d-8r6br
BestEffort
2m19s
Running
opentelemetry-operator-657694c64f-7pdpt
opentelemetry-operator
0
ReplicaSet
shoot--be6a452d50--idp-ske-tst-system-z3-8475c-5c7kt
Burstable
4m43s
Running
opentelemetry-operator-657694c64f-h5q78
opentelemetry-operator
0
ReplicaSet
shoot--be6a452d50--idp-ske-tst-system-z1-57d9d-8r6br
Burstable
4m53s
Running
opentelemetry-collector-0
opentelemetry-collector
0
StatefulSet
shoot--be6a452d50--idp-ske-tst-system-z2-7d587-r5g4v
Burstable
4m58s
Running
autoinstrumentation-nginx-ingress-nginx-controller-5fdc46btkhkt
autoinstrumentation-nginx
0
ReplicaSet
shoot--be6a452d50--idp-ske-tst-app-z1-859c9-vrhjw
Burstable
84m
Running
autoinstrumentation-nginx-ingress-nginx-controller-5fdc46bwm49j
autoinstrumentation-nginx
0
ReplicaSet
shoot--be6a452d50--idp-ske-tst-app-z3-76749-6qrsm
Burstable
85m
Running
ingress-nginx-controller-bc47fb9f4-42c48
nginx
1
ReplicaSet
shoot--be6a452d50--idp-ske-tst-app-z2-5b67d-5qwh9
Burstable
5d1h
Running
ingress-nginx-controller-bc47fb9f4-xsqqw
nginx
0
ReplicaSet
shoot--be6a452d50--idp-ske-tst-app-z3-76749-6qrsm
Burstable
5d1h
Running
smtp-mock-68f8958c5f-kv5pl
default
0
ReplicaSet
shoot--be6a452d50--idp-ske-tst-system-z2-7d587-r5g4v
BestEffort
10d
Running
Namespace
default
Owner
StatefulSet collector-with-ta-collector
Pod
collector-with-ta-collector-0
Container
otc-container
Search...
2025-02-03T13:50:15.076Z	info	service@v0.104.0/service.go:115	Setting up own telemetry...
2025-02-03T13:50:15.076Z	info	service@v0.104.0/telemetry.go:96	Serving metrics	{"address": "0.0.0.0:8888", "level": "Normal"}
2025-02-03T13:50:15.076Z	info	exporter@v0.104.0/exporter.go:280	Development component. May change in the future.	{"kind": "exporter", "data_type": "metrics", "name": "debug"}
2025-02-03T13:50:15.078Z	info	service@v0.104.0/service.go:193	Starting otelcol-contrib...	{"Version": "0.104.0", "NumCPU": 4}
2025-02-03T13:50:15.078Z	info	extensions/extensions.go:34	Starting extensions...
2025-02-03T13:50:15.078Z	info	extensions/extensions.go:37	Extension is starting...	{"kind": "extension", "name": "health_check"}
2025-02-03T13:50:15.078Z	info	healthcheckextension@v0.104.0/healthcheckextension.go:32	Starting health_check extension	{"kind": "extension", "name": "health_check", "config": {"Endpoint":"localhost:13133","TLSSetting":null,"CORS":null,"Auth":null,"MaxRequestBodySize":0,"IncludeMetadata":false,"ResponseHeaders":null,"CompressionAlgorithms":null,"Path":"/","ResponseBody":null,"CheckCollectorPipeline":{"Enabled":false,"Interval":"5m","ExporterFailureThreshold":5}}}
2025-02-03T13:50:15.079Z	info	extensions/extensions.go:52	Extension started.	{"kind": "extension", "name": "health_check"}
2025-02-03T13:50:15.080Z	info	prometheusreceiver@v0.104.0/metrics_receiver.go:279	Starting discovery manager	{"kind": "receiver", "name": "prometheus", "data_type": "metrics"}
2025-02-03T13:50:15.080Z	info	prometheusreceiver@v0.104.0/metrics_receiver.go:121	Starting target allocator discovery	{"kind": "receiver", "name": "prometheus", "data_type": "metrics"}
2025-02-03T13:50:15.083Z	info	prometheusreceiver@v0.104.0/metrics_receiver.go:257	Scrape job added	{"kind": "receiver", "name": "prometheus", "data_type": "metrics", "jobName": "otel-collector"}
2025-02-03T13:50:15.083Z	info	healthcheck/handler.go:132	Health Check state change	{"kind": "extension", "name": "health_check", "status": "ready"}
2025-02-03T13:50:15.084Z	info	service@v0.104.0/service.go:219	Everything is ready. Begin running and processing data.
2025-02-03T13:50:15.083Z	info	prometheusreceiver@v0.104.0/metrics_receiver.go:344	Starting scrape manager	{"kind": "receiver", "name": "prometheus", "data_type": "metrics"}


Events:

Liveness probe failed: Get "http://10.96.7.107:13133/": dial tcp 10.96.7.107:13133: connect: connection refused
```
