### ISSUE TITLE
Add `protocol: TCP` value under `ports` key to avoid the known limitation for Kubernetes 1.19

### ISSUE THREAD

**Issue by Saber-W** [open-telemetry/opentelemetry-operator#370]
**Is your feature request related to a problem? Please describe.**

The Operator supports Kubernetes 1.19, but an error will occur if we apply the Operator manifest with `--server-side` option on Kubernetes 1.19. The error is:

```console
Error from server: failed to create typed patch object: .spec.ports: element 0: associative list with keys has an element that omits key field "protocol" (and doesn't have default value)
```

This error is caused by the fact that we omit the `protocol` option under `ports` key. This problem is a known limitation as in this [issue](https://github.com/kubernetes-sigs/structured-merge-diff/issues/130), which is resolved after Kubernetes 1.20.

**Describe the solution you'd like**

The solution is very straightforward - just add `protocol: TCP` value under the `ports` key explicitly. There are three manifests we need to change: the two services and the `kube-rbac-proxy` container of Deployment. For example, the controller-manager service configuration would look like:

```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: controller-manager
  name: opentelemetry-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
    protocol: TCP # This line was omitted by us because the default value is TCP.
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
```

**Describe alternatives you've considered**

An alternative would be that we do not support Kubernetes 1.19, which is not what we want IMO.

**Additional context**

The known limitation for Kubernetes 1.19: https://github.com/kubernetes-sigs/structured-merge-diff/issues/130

cc @alolita @jpkrohling
