### ISSUE TITLE
Allow `instrumentation.spec.exporter` to reference an `opentelemetrycollector` resource

### ISSUE THREAD

**Issue by cskinfill** [open-telemetry/opentelemetry-operator#3715]
### Component(s)

auto-instrumentation

### Is your feature request related to a problem? Please describe.

Currently, to configure the exporter for an `Instrumentation`, the full URL is needed.  For an`OpenTelemetryCollector` in the same kubernetes cluster, this means deploying it and then determining what the DNS entry is, along with the port.

### Describe the solution you'd like

Instead of the setting the URL, support referencing a Kubernetes `OpenTelemetryCollector` resource similar to below
```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: test
spec:
  exporter:
    ref:
      apiVersion: opentelemetry.io/v1beta1 (optional?)
      kind: OpenTelemetryCollector (optional?)
      name: mycollector
      namespace: myapp
...
```
The operator/webhook would use the information from the `OpenTelemetryCollector` to inject the exporter endpoint to be used for the pod being instrumented.
