### ISSUE TITLE
Collector unable to use TLS Config from Target Allocator with ScrapeConfig

### ISSUE THREAD

**Issue by CharlieTLe** [open-telemetry/opentelemetry-operator#3724]
### Component(s)

collector, target allocator

## Description
The OpenTelemetry Collector is unable to use the TLS Configuration values that are specified in a ScrapeConfig CR from the Target Allocator.

## Steps to Reproduce

1. Setup OTel Operator with PrometheusCR to have a collector and target allocator setup.
2. Specify a ScrapeConfig to scrape the nodes in the cluster

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: scrape-config
spec:
  scheme: HTTPS
  kubernetesSDConfigs:
    - role: Node
  authorization:
    type: Bearer
    credentials:
      key: "token"
      name: "opentelemetry-collector"
  tlsConfig:
    ca:
      secret:
        key: "ca.crt"
        name: "opentelemetry-collector"
    insecureSkipVerify: false
```

## Expected Result

Successful scraping of the Kubernetes node.

## Actual Result

Error while reading CA certificate needed to verify communication with Kubernetes node.

### Kubernetes Version

1.31.0

### Operator version

0.118.0

### Collector version

0.118.0

### Environment information

The operator is configured with `--feature-gates=operator.targetallocator.mtls` to allow for the collector to get secret information from the target allocator.

### Log output

```shell
The collector logs this error:


error creating HTTP client: unable to read CA cert: unable to read file /etc/prometheus/certs/opentelemetry-collector_ca.crt: open /etc/prometheus/certs/opentelemetry-collector_ca.crt: no such file or directory
```

### Additional context

The scrape config from the Target Allocator looks something like this.

```
curl -s localhost:8080/scrape_configs | jq
{
  "scrapeConfig/static-config": {
    "authorization": {
      "credentials": "<secret>",
      "type": "Bearer"
    },
    "job_name": "scrapeConfig/static-config",
    "kubernetes_sd_configs": [
      {
        "role": "node"
      }
    ],
    "metrics_path": "/metrics",
    "scheme": "https",
    "tls_config": {
      "ca_file": "/etc/prometheus/certs/opentelemetry-collector_ca.crt",
      "insecure_skip_verify": false
    },
    "track_timestamps_staleness": false
  }
}
```
