### ISSUE TITLE
Failed pod creating nginx instrumentation

### ISSUE THREAD

**Issue by Faig92** [open-telemetry/opentelemetry-operator#3729]
### Component(s)

auto-instrumentation

### What happened?

While trying use nginx autoinstrumentation this error occurs:

Error creating: Pod app is invalid: spec.initContainers[1].resizePolicy: Invalid value: []core.ContainerResizePolicy{core.ContainerResizePolicy{ResourceName:"cpu", RestartPolicy:"NotRequired"}, core.ContainerResizePolicy{ResourceName:"memory", RestartPolicy:"NotRequired"}}: must not be set for init containers
```
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      name: app
      labels:
        123: xxx
      annotations:
        vault.hashicorp.com/agent-cache-enable: 'false'
        vault.hashicorp.com/agent-image: myimage
        vault.hashicorp.com/agent-init-first: 'true'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        instrumentation.opentelemetry.io/inject-nginx: 'instrumentation'
        instrumentation.opentelemetry.io/container-names: 'app'
   spec:
      containers:
        - name: app
          image: myimage
          resources:
            limits:
              cpu: xxx
              ephemeral-storage: xxx
              memory: xxx
            requests:
              cpu: xxx
              ephemeral-storage: xxx
              memory: xxx  
          livenessProbe:
          readinessProbe:
          imagePullPolicy: Always
```

### Kubernetes Version

1.27

### Operator version

0.117.0

### Collector version

0.119.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell

```
