### ISSUE TITLE
Operator does not respect new metrics readers, favors deprecated address

### ISSUE THREAD

**Issue by csatib02** [open-telemetry/opentelemetry-operator#3730]
### Component(s)

collector

## Description

Although `service::telemetry::metrics::address` field was deprecated in https://github.com/open-telemetry/opentelemetry-collector/pull/11205 starting from `v0.111.0`, an address defaulting was implemented in https://github.com/open-telemetry/opentelemetry-operator/pull/3361.

This can lead to issues:

* When using opentelemetry-operator, with a contrib distro collector, setting the telemetry like this:

```yaml
  telemetry:
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: ""
                port: 8888
```

gets omitted completly:

```yaml
      Telemetry:
        Metrics:
          Address:  0.0.0.0:8888
``` 
 
* On our custom otel-collector distribution, where we set readers through our operator, it also sets the deprecated address:

### Before deploying

```yaml
  telemetry:
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: ""
                port: 8888
```

### After deploying

```yaml
  telemetry:
    metrics:
      address: 0.0.0.0:8888
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: ""
                port: 8888
```

Which can cause the collector to crash:

```sh
Error: failed to create SDK: binding address 0.0.0.0:8888 for Prometheus exporter: listen tcp 0.0.0.0:8888: bind: address already in use
2025/02/20 10:38:05 collector server run finished with error: failed to create SDK: binding address 0.0.0.0:8888 for Prometheus exporter: listen tcp 0.0.0.0:8888: bind: address already in use
stream closed EOF for collector/otelcollector-example-collector-dh7qv (otc-container)
```

## Steps to Reproduce

1. Set a reader in a collector's config as suggested in the deprecation notice: https://github.com/open-telemetry/opentelemetry-collector/pull/11205
2. Deploy the collector.
3. Eventually it will omit the set telemetry configuration or the collector crashes.

## Expected Result

The operator should respect the deprecation and not set a default address, instead it should support and default to setting a reader.

## Actual Result

The operator omits the telemetry config and sets the deprecated default, or it crashes.

### Kubernetes Version

v1.31.2

### Operator version

v0.117.0

### Collector version

v0.120.0

## Environment
OS: Ubuntu 20.04

### Log output

```shell
Error: failed to create SDK: binding address 0.0.0.0:8888 for Prometheus exporter: listen tcp 0.0.0.0:8888: bind: address already in use
2025/02/20 10:38:05 collector server run finished with error: failed to create SDK: binding address 0.0.0.0:8888 for Prometheus exporter: listen tcp 0.0.0.0:8888: bind: address already in use
stream closed EOF for collector/otelcollector-example-collector-dh7qv (otc-container)
```

**Comment by shuheiktgw** [comment]
Let me fix this issue 🙏

**Comment by ChrisMcD1** [comment]
This also impacts users of the new 

```
telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                without_type_suffix: false
```
and `without_units` and `without_scope_info`. As far as I can tell there is no way to change those settings without _also_ changing the port, since it will conflict with the default that has already bound to port 8888
