### ISSUE TITLE
Prometheus Receiver Fails to Read CA Cert in OpenTelemetry Collector

### ISSUE THREAD

**Issue by hmsayem** [open-telemetry/opentelemetry-operator#3741]
### What happened?

The OpenTelemetry Collector fails to scrape metrics from a ServiceMonitor with TLS configuration due to a missing CA certificate file. The collector logs the following error:  

```
error creating HTTP client: unable to read CA cert: unable to read file /etc/prometheus/certs/0_kubeops_kube-ui-server-apiserver-cert_ca.crt: open /etc/prometheus/certs/0_kubeops_kube-ui-server-apiserver-cert_ca.crt: no such file or directory
```

#### Steps to Reproduce  
1. Deploy OpenTelemetry Collector with Prometheus receiver configured.  
2. Deploy a ServiceMonitor with `tlsConfig.ca.secret` pointing to a Kubernetes Secret.  
3. Observe the OpenTelemetry Collector logs for the above error.  

#### Expected Behavior  
The collector should successfully read the CA certificate from the Secret and scrape metrics from the ServiceMonitor.  

#### OpenTelemetryCollector YAML  
```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-kube-stack-agent
  namespace: monitoring
spec:
  config:
    exporters:
      debug: {}
      otlp:
        endpoint: opentelemetry-kube-stack-gateway-collector:4317
        tls:
          insecure: true
    processors:
      ...
    receivers:
      ...
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs: []
    service:
      pipelines:
        logs:
          exporters:
          - otlp
          processors:
          - resourcedetection/env
          - batch
          receivers:
          - otlp
          - filelog
        metrics:
          exporters:
          - otlp
          processors:
          - resourcedetection/env
          - batch
          receivers:
          - prometheus
  configVersions: 3
  targetAllocator:
    allocationStrategy: per-node
    enabled: true
    filterStrategy: relabel-config
    image: ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:main
    observability:
      metrics: {}
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      scrapeInterval: 30s
      serviceMonitorSelector: {}
    resources: {}
    serviceAccount: opentelemetry-targetallocator-sa
```

#### ServiceMonitor YAML  
```yaml
kind: ServiceMonitor
metadata:
  name: kube-ui-server
  namespace: kubeops
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 10s
    port: api
    scheme: https
    tlsConfig:
      ca:
        secret:
          key: ca.crt
          name: kube-ui-server-apiserver-cert
      serverName: kube-ui-server.kubeops.svc
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 10s
    port: telemetry
    scheme: http
  namespaceSelector:
    matchNames:
    - kubeops
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-ui-server
      app.kubernetes.io/name: kube-ui-server
```

### Kubernetes Version

v1.31.5+k3s1

### Operator version

0.110.0

### Collector version

0.110.0
