### ISSUE TITLE
Collector service selector wrong when using sidecar mode

### ISSUE THREAD

**Issue by jochenseeber** [open-telemetry/opentelemetry-operator#3779]
### Component(s)

collector

## Description

When using the operator to inject a collector sidecar, the operator also creates services for the collector. However, the selector used in these services is the "default" selector for non-sidecar mode, leading to unusable services.

### Example

Selector in service created by the operator:

```yaml
selector:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: myapp-system.myapp
    app.kubernetes.io/managed-by: opentelemetry-operator
    app.kubernetes.io/part-of: opentelemetry
```

Labels used in the pod where the sidecar is injected:

```yaml
labels:
    app.kubernetes.io/component: mycomponent
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/name: myapp
```

## Steps to Reproduce

* Create a sidecar `OpenTelemetryCollector` resource
* Start a pod that uses this collector
* Inspect created services

## Expected Result

The operator should either use a selector that correctly selects pods where the sidecar was injected (probably not ease to automate), or allow manual specification of the service selector, or provide an option to not create the services at all in the `OpenTelemetryCollector` resource.

## Actual Result

The operator creates unusable services

### Kubernetes Version

v1.28.5

### Operator version

0.119.0

### Collector version

0.121.0

## Environment
OS: Ubuntu Noble

### Log output

```shell

```
