### ISSUE TITLE
Upgrade prometheus and prometheus-operator dependencies to latest

### ISSUE THREAD

**Issue by swiatekm** [open-telemetry/opentelemetry-operator#3782]
### Component(s)

target allocator

### Describe the issue you're reporting

There are currently several issues blocking us from upgrading to the latest version of prometheus dependencies:

- [x] Some changes to logging that we should be able to easily make.
- [x] Prometheus-operator now generates Prometheus config a bit differently, and we'll need to clean up our handling of namespace selectors in target allocator to be compatible.
- [ ] Prometheus 0.300.0 includes a breaking change to default scrape protocols, and this change is supported by the Otel collector starting in version 0.120.0. We need to account for this in the configurations generated by target allocator and think about when and how we want to introduce the breaking change.

**Comment by oldium** [comment]
Is it planned to fix the following config or should I create a separate issue for it?

```
    service:
      telemetry:
        metrics:
          level: detailed
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: '0.0.0.0'
                    port: 8888
 ```

This creates an “address already in use” Collector startup error, because OTEL K8s Operator adds a default `service.telemetry.metrics.address=0.0.0.0:8888`, which conflicts with custom `service.telemetry.metrics.readers` config.
