### ISSUE TITLE
Optimistically map /var/log to Collector when deployed with container filelog receiver.

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-operator#3791]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

The `container` filelog parser is very convenient! It'd be even more convenient if we automatically mounted `/var/log` into the Collector so that it would work out of the box.

### Describe the solution you'd like

Automatically map in `/var/log` when we see an appropriate config block.

Something like this should trigger it --

```
filelog:
        include_file_path: true
        exclude:
          - /var/log/pods/*collector*/*collector*/*.log
        include:
          - /var/log/pods/*/*/*.log
        operators:
          - id: container-parser
            type: container
```
