### ISSUE TITLE
Operator exports seeing connection reset by peer failure.

### ISSUE THREAD

**Issue by GreenAlex96** [open-telemetry/opentelemetry-operator#3793]
### Component(s)

collector

### Describe the issue you're reporting

I'm trying to get the collector up and running in our AKS cluster but it is failing when trying to export to Grafana Tempo:

> info	internal/retry_sender.go:126	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "traces", "name": "otlp", "error": "rpc error: code = Unavailable desc = connection error: desc = \"error reading server preface: read tcp 172.22.5.120:54336->10.0.20.28:4137: read: connection reset by peer\"", "interval": "34.705444539s"}

This behavior is has only shown itself when running the operator in the cluster (installed via helm chart). Running the collector locally, both directly and in a docker container, have been fine. I'm also able to send traces to Tempo from another pod using telemetrygen. This leads me to believe this is an issue on the collector's side, rather than on Tempo.

Here is the collector configuration:

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: simplest
  namespace: test
spec:
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      otlp:
        endpoint: tempo.tempo.svc.cluster.local:4137
        timeout: 60s
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]
```

And the helm configuration just uses some recommended defaults:

```yaml
admissionWebhooks:
  certManager:
    enabled: true
manager:
  collectorImage:
    repository: otel/opentelemetry-collector-k8s
```
