### ISSUE TITLE
using targetallocator to scrape authenticated endpoints via servicemonitor

### ISSUE THREAD

**Issue by rakesh-p** [open-telemetry/opentelemetry-operator#3811]
I am trying to use otel collector with target allocator enabled to scrap endpoint that needs authentication.  The servicemon is picked by target allocator and i can see the scraping configs when i go to http://localhost:8080/scrape_configs (after kubectl port-forward services/collector-with-ta-targetallocator 8080:80). But the collector logs show unauthorized error as below.

```
Scrape failed	{"otelcol.component.id": "prometheus", "otelcol.component.kind": "Receiver", "otelcol.signal": "metrics", 
"scrape_pool": "serviceMonitor/awx-prod/controller-manager-metrics-monitor/0", 
"target": "http://192.168.72.62:8052/api/v2/metrics", 
"err": "server returned HTTP status 401 Unauthorized"}

```

Service monitor config:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/part-of: awx-prod
  name: controller-manager-metrics-monitor
spec:
  endpoints:
    - path: /api/v2/metrics
      port: http
      scheme: http
      authorization:
        credentials:
          name: prometheus-awx-token
          key: token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/part-of: awx-prod
```
I know the credentials in servicemonitor is correct because kube-prometheus is able to scrap the target. Also the following worked when running from within a curlpod 
```
curl -L -H "Authorization: Bearer my_token_redacted" http://awx-prod-service/api/v2/metrics
``` 

OpenTelemetryCollector CRD:
```
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector-with-ta
spec:
  mode: statefulset
  serviceAccount: otel-target-allocator-sa
  targetAllocator:
    enabled: true
    serviceAccount: otel-target-allocator-sa
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: 
          matchLabels: 
              app.kubernetes.io/part-of: awx-prod
  config: 
    receivers:
      prometheus:
        config:         
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 10s
            tls_config:
              insecure_skip_verify: true	            
            metric_relabel_configs:
            - action: labeldrop
              regex: (id|name)
              replacement: $$1
            - action: labelmap
              regex: label_(.+)
              replacement: $$1
    exporters:
      debug: {}

    service:
      telemetry:
        logs:
          level: "DEBUG"
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [debug]

```
The service account `otel-target-allocator-sa` has required permissions to read the secret as shown below.

```
kubectl auth can-i get secret/prometheus-awx-token -n awx-prod --as=system:serviceaccount:awx-prod:otel-target-allocator-sa
yes
```
there are no k8s network polices to restrict access. Looking for ideas to troubleshoot further or do you see any issues with my above config please. thanks!

**Comment by rakesh-p** [comment]
One thing i noticed is that in the localhost:8080/scrape_configs, the value for credentials is <secret> instead of actual credentials. I guess this is ok. 

![Image](https://github.com/user-attachments/assets/339f2154-0835-431b-b048-0f17f6e6550e)

**Comment by rakesh-p** [comment]
Also here https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator#service--pod-monitor-endpoint-credentials it is mentioned the following but i cannot see any example of configuring this.  :(

> If your service or pod monitor endpoints require authentication (such as bearer tokens, basic auth, OAuth2, etc.), you must ensure that the collector has access to these credentials.

**Comment by jan-machacek-kosik** [comment]
I have the same problem. When I direct the PodMonitor using a selector to a debug pod that prints everything sent to it, I see that in the header, instead of the token, there's just <secret>. I think this is the reason why the secure metric point returns a 404 error.

```
    "headers": {
        "host": "10.110.3.57:8080",
        "user-agent": "otelcol-contrib/0.120.1",
        "accept": "application/openmetrics-text;version=1.0.0;escaping=allow-utf-8;q=0.6,application/openmetrics-text;version=0.0.1;escaping=allow-utf-8;q=0.5,text/plain;version=0.0.4;escaping=allow-utf-8;q=0.4,*/*;q=0.3",
        "accept-encoding": "gzip",
        "authorization": "Bearer <secret>",
        "x-prometheus-scrape-timeout-seconds": "10"
    }
```

**Comment by rakesh-p** [comment]
Thanks @jan-machacek-kosik for the input. Did it ever work for you before please i,e, scraping authenticated endpoints ?. 

I am using the latest version 0.120.0 

- ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:0.120.0
- ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:0.120.0
- docker.io/otel/opentelemetry-collector-k8s:0.120.0

May be it could be regression because i think this is common requirement to scrape authenticated endpoints. Let me try with the previous version 0.119.0

**Comment by rakesh-p** [comment]
same issue with versio  0.119.0..

**Comment by jan-machacek-kosik** [comment]
@rakesh-p  It has never worked for me; this is a new functionality I'm trying out. I've tried it on versions 0.120.0 and 0.119.0. Both have the same problem.

**Comment by rakesh-p** [comment]
Hi @CharlieTLe I noticed that you have worked on issues (example: #3724) similar to this. I am wondering if you can offer any help on this issue please. Thanks

**Comment by ItielOlenick** [comment]
Can you please elaborate on how you deployed the target allocator and collector? Did you go through the required steps to enable mTLS as described in https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator#service--pod-monitor-endpoint-credentials ?
Can you please provide the target allocator's startup logs?

**Comment by rakesh-p** [comment]
Hi @ItielOlenick thanks for your comments. Here is the requested info. 

- Installed otel operator using helm charts command below.

`❯ helm install opentelemetry-operator open-telemetry/opentelemetry-operator --namespace awx-prod -f custom-values.yaml
`

- contents of custom-values.yaml

```
manager:
  collectorImage:
    repository: "otel/opentelemetry-collector-k8s"
    tag: 0.120.0

  featureGatesMap:
    operator.targetallocator.mtls: true
```

- target-allocator logs

```
❯ k logs -f collector-with-ta-targetallocator-69df6785cf-ds4d6 
{"level":"info","ts":"2025-03-20T09:39:33Z","msg":"Starting the Target Allocator"}
{"level":"info","ts":"2025-03-20T09:39:33Z","msg":"Waiting for caches to sync for namespace"}
{"level":"info","ts":"2025-03-20T09:39:33Z","logger":"allocator","msg":"Starting server..."}
{"level":"info","ts":"2025-03-20T09:39:33Z","msg":"Caches are synced for namespace"}
{"level":"info","ts":"2025-03-20T09:39:33Z","msg":"Waiting for caches to sync for podmonitors"}
{"level":"info","ts":"2025-03-20T09:39:33Z","msg":"Caches are synced for podmonitors"}
{"level":"info","ts":"2025-03-20T09:39:33Z","msg":"Waiting for caches to sync for probes"}
{"level":"info","ts":"2025-03-20T09:39:33Z","msg":"Caches are synced for probes"}
{"level":"info","ts":"2025-03-20T09:39:33Z","msg":"Waiting for caches to sync for scrapeconfigs"}
{"level":"info","ts":"2025-03-20T09:39:33Z","msg":"Caches are synced for scrapeconfigs"}
{"level":"info","ts":"2025-03-20T09:39:33Z","msg":"Waiting for caches to sync for servicemonitors"}
{"level":"info","ts":"2025-03-20T09:39:33Z","msg":"Caches are synced for servicemonitors"}
{"level":"info","ts":"2025-03-20T09:39:38Z","logger":"allocator","msg":"Service Discovery watch event received","targets groups":1}
{"level":"info","ts":"2025-03-20T09:39:43Z","logger":"allocator","msg":"Service Discovery watch event received","targets groups":2}
{"level":"info","ts":"2025-03-20T09:39:53Z","logger":"allocator","msg":"Service Discovery watch event received","targets groups":2}

```
- otel collector logs snippet
```
{"level":"INFO","timestamp":"2025-03-20T09:25:33Z","message":"Starting EventSource","controller":"targetallocator","controllerGroup":"opentelemetry.io","controllerKind":"TargetAllocator","source":"kind source: *v1beta1.OpenTelemetryCollector"}
{"level":"INFO","timestamp":"2025-03-20T09:25:33Z","logger":"instrumentation-upgrade","message":"no instances to upgrade"}
{"level":"INFO","timestamp":"2025-03-20T09:25:33Z","logger":"collector-upgrade","message":"no instances to upgrade"}
{"level":"INFO","timestamp":"2025-03-20T09:25:33Z","message":"Starting Controller","controller":"opampbridge","controllerGroup":"opentelemetry.io","controllerKind":"OpAMPBridge"}
{"level":"INFO","timestamp":"2025-03-20T09:25:33Z","message":"Starting workers","controller":"opampbridge","controllerGroup":"opentelemetry.io","controllerKind":"OpAMPBridge","worker count":1}
{"level":"INFO","timestamp":"2025-03-20T09:25:33Z","message":"Starting Controller","controller":"targetallocator","controllerGroup":"opentelemetry.io","controllerKind":"TargetAllocator"}
{"level":"INFO","timestamp":"2025-03-20T09:25:33Z","message":"Starting workers","controller":"targetallocator","controllerGroup":"opentelemetry.io","controllerKind":"TargetAllocator","worker count":1}
{"level":"INFO","timestamp":"2025-03-20T09:25:33Z","message":"Starting Controller","controller":"opentelemetrycollector","controllerGroup":"opentelemetry.io","controllerKind":"OpenTelemetryCollector"}
{"level":"INFO","timestamp":"2025-03-20T09:25:33Z","message":"Starting workers","controller":"opentelemetrycollector","controllerGroup":"opentelemetry.io","controllerKind":"OpenTelemetryCollector","worker count":1}
{"level":"INFO","timestamp":"2025-03-20T09:39:27Z","logger":"controllers.OpenTelemetryCollector","message":"pdb field is unset in Spec, creating default"}

```

**Comment by ItielOlenick** [comment]
Looks like not all of the requirements for running the operator with mTLS between the TA and the Collector are in place, causing the HTTPS server to not start.
Can you please also share the operator startup logs? (you can restart the operator to get them if they are long gone).

**Comment by rakesh-p** [comment]
the cert-manager runs in a different namespace in the cluster.. 

```
> k get po
NAME                                       READY   STATUS    RESTARTS      AGE
cert-manager-69b845dfdb-w55mk              1/1     Running   8             127d
cert-manager-cainjector-655979545b-9rvb6   1/1     Running   8 (35d ago)   127d
cert-manager-webhook-749679df98-pz9sx      1/1     Running   1 (35d ago)   127d
```

**Comment by ItielOlenick** [comment]
So as expected, the operator doesn't have the right RBAC permissions to create cert manager resources.
Please follow https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator#service--pod-monitor-endpoint-credentials

**Comment by rakesh-p** [comment]
I did follow the instructions.. I have the following clusterrole permissions which is bound to a service account `otel-target-allocator-sa' and both the operator and TA uses this service account 

ClusterRole permissions:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-target-allocator-role
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
    verbs: ["get"]
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics", "/metrics/cadvisor", "/metrics/probes"]
    verbs: ["get"]
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
      - podmonitors
      - probes
      - scrapeconfigs
    verbs:
      - "*"
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - cert-manager.io
    resources:
      - issuers
      - certificaterequests
      - certificates
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete

```

the spec for `OpenTelemetryCollector` referring to the same SA for TA and OpenTelemetryCollector

```
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector-with-ta
spec:
  mode: statefulset
  serviceAccount: otel-target-allocator-sa
  targetAllocator:
    enabled: true
    serviceAccount: otel-target-allocator-sa
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: 
          matchLabels: 
              app.kubernetes.io/part-of: awx-prod
```

**Comment by rakesh-p** [comment]
ok i think i understood the problem. there are two SA.. one i created and one `opentelemetry-operator` created as part of operator installation i believe. 

```
opentelemetry-operator            0         5m5s
otel-target-allocator-sa          0         5d18h

```
I will create a cluster role binding for `opentelemetry-operator` SA and will try again.

**Comment by rakesh-p** [comment]
digging deeper, look like helm charts already created the necessary CR and CRB for the service account `opentelemetry-operator`. This means i dont need to do anything. 

CR (created by helm chart):
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: opentelemetry-operator
    meta.helm.sh/release-namespace: awx-prod
  creationTimestamp: "2025-03-20T10:53:21Z"
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: opentelemetry-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opentelemetry-operator
    app.kubernetes.io/part-of: opentelemetry-operator
    app.kubernetes.io/version: 0.120.0
    helm.sh/chart: opentelemetry-operator-0.83.0
  name: opentelemetry-operator-manager
  resourceVersion: "58682576"
  uid: 12c6cda7-a6ea-4356-acd0-ef15ab935973
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  - infrastructures/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opentelemetry.io
  resources:
  - instrumentations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opentelemetry.io
  resources:
  - opampbridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opentelemetry.io
  resources:
  - opampbridges/finalizers
  verbs:
  - update
- apiGroups:
  - opentelemetry.io
  resources:
  - opampbridges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opentelemetry.io
  resources:
  - opentelemetrycollectors
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opentelemetry.io
  resources:
  - opentelemetrycollectors/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opentelemetry.io
  resources:
  - opentelemetrycollectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opentelemetry.io
  resources:
  - targetallocators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opentelemetry.io
  resources:
  - targetallocators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  - certificaterequests
  - certificates
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

```

CRB
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: opentelemetry-operator
    meta.helm.sh/release-namespace: awx-prod
  creationTimestamp: "2025-03-20T10:53:21Z"
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: opentelemetry-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opentelemetry-operator
    app.kubernetes.io/part-of: opentelemetry-operator
    app.kubernetes.io/version: 0.120.0
    helm.sh/chart: opentelemetry-operator-0.83.0
  name: opentelemetry-operator-manager
  resourceVersion: "58682578"
  uid: 0dc96b98-a6e6-432f-bad9-3ff157d99301
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentelemetry-operator-manager
subjects:
- kind: ServiceAccount
  name: opentelemetry-operator
  namespace: awx-prod

```

**Comment by ItielOlenick** [comment]
But it is still not working?

**Comment by ItielOlenick** [comment]
Lowering the debug level by adding `--zap-log-level=2` to the operators deployment will log additional logs:
```
...
{"level":"LEVEL(-2)","timestamp":"2025-03-20T12:42:47Z","logger":"config","message":"the cert manager crd and permissions are not set for the operator","reason":"not possible to check RBAC rules: SERVICE_ACCOUNT_NAME env variable not found"}
{"level":"LEVEL(-2)","timestamp":"2025-03-20T12:42:47Z","logger":"config","message":"the cert manager crd and permissions are set for the operator","availability":"NotAvailable"}
...
```

looks like the helm chart is missing some environment variables which are present in the manifest for the operator.
namely - 
```yaml
        env:
          - name: SERVICE_ACCOUNT_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
```
adding them solves the issue.
Ill open a MR for fixing that in the operators helm chart.
In the meanwhile you can add this env var manually to solve the issue

**Comment by ItielOlenick** [comment]
Created https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1588

**Comment by rakesh-p** [comment]
Thanks a lot @ItielOlenick I can confirm the scraping is successful now. no more unauthorized error. Also for others, it is expected to see credentials as `<secret>` in the scrape_configs. see images above.

helm chart values that woroked. @jan-machacek-kosik for info.
```
manager:
  collectorImage:
    repository: "otel/opentelemetry-collector-k8s"
    tag: 0.120.0

  featureGatesMap:
    operator.targetallocator.mtls: true
    
  createRbacPermissions: true
```
