### ISSUE TITLE
[operator] Declare only autoinstrumentation image repository

### ISSUE THREAD

**Issue by davgia** [open-telemetry/opentelemetry-operator#3828]
### Component(s)

auto-instrumentation

### Is your feature request related to a problem? Please describe.

My goal is to pull all images from a k8s cluster using a pull through cache strategy. To do that I need to change all the deployed helm charts.
Relative to this chart, I would like to define default auto-instrumentation images repository **without** specifying the tag. I would like the operator to take care of the tag (so it is still updated when necessary). Those are my values for the `opentelemetry-operator` chart (version: `0.83.0`):

``` yaml
# NB: I am in terraform, so ${image_registry} is substituted with my private oci registry url
manager:
  image:
    repository: "${image_registry}/ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator"
  collectorImage:
    repository: "${image_registry}/docker.io/otel/opentelemetry-collector-contrib"
  autoInstrumentationImage:
    dotnet:
      repository: "${image_registry}/ghcr.io/open-telemetry/autoinstrumentation-dotnet"
      tag: "1.2.0" # it should not be required (or should be defined in the helm chart default values), the operator should take care of this
    java:
      repository: "${image_registry}/ghcr.io/open-telemetry/autoinstrumentation-java"
      tag: "1.33.6" # it should not be required (or should be defined in the helm chart default values), the operator should take care of this
    python:
      repository: "${image_registry}/ghcr.io/open-telemetry/autoinstrumentation-python"
      tag: "0.51b0" # it should not be required (or should be defined in the helm chart default values), the operator should take care of this
```

### Describe the solution you'd like

The chart currently renders the container cli parameter only if both repository and tag are specified. This forces me to hardcode the tag. I don't know if the tag is strictly required but it would be nice if the auto instrumentation tag was defined in the default values of the helm chart operator (and updated with each release; just like the collector image tag) or if it was not necessary at all (but managed by the operator in some way).

### Describe alternatives you've considered

The alternative is to hardcode the tag, but I don't like this approach because I may forget to update it (and it may be necessary in order to function properly).
