### ISSUE TITLE
Collector issue when service account specific

### ISSUE THREAD

**Issue by trahim** [open-telemetry/opentelemetry-operator#3849]
### Component(s)

collector

## Description

When creating a collector with service account specified, deployments fail to create as no service account is created. When not specified this creates as expected. Also weirdly if managed separately which matches what it expects as a default it will delete that service account if the value is added later.

## Steps to Reproduce

kubectl apply the below
```
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-gateway-test
spec:
  autoscaler:                                                                     
    maxReplicas: 3
    minReplicas: 1
    targetCPUUtilization: 90
  mode: deployment
  replicas: 1
  image: otel/opentelemetry-collector-contrib:0.120.0
  serviceAccount: opentelemetry-gateway-test-collector
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    exporters:
      loadbalancing:
        protocol:
          otlp:
            tls:
              insecure: true
        resolver:
          dns:
            hostname: collectors.example.com

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [loadbalancing]
```

## Expected Result

All pods in the deployment to start up.

## Actual Result

Pods can't start as they don't have the service account they need

### Kubernetes Version

1.30

### Operator version

0.120.0

### Collector version

0.120.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell
message: 'Error creating: pods "opentelemetry-gateway-test-collector-c5b9bdbd5-" is                                                                                                                                 forbidden: error looking up service account opentelemetry/opentelemetry-gateway-test-collector:                                                                                                                   serviceaccount "opentelemetry-gateway-test-collector" not found'
```
