### ISSUE TITLE
What does `interval` mean in the `target_allocator` section created by the operator?

### ISSUE THREAD

**Issue by bohub12** [open-telemetry/opentelemetry-operator#3864]
### Component(s)

target allocator

### Describe the issue you're reporting

When deploying an `OpenTelemetryCollector CRD`, I understand that if I give `targetAllocator` a value of `enabled` to true, the `operator` will modify the `config` as shown below.

```yaml
receivers:
  prometheus:
    target_allocator:
      endpoint: http://collector-with-ta-targetallocator:80
      interval: 30s
      collector_id: $POD_NAME
```

What does `interval` mean in the `target_allocator` section created by the operator?
- Is it correct that the interval at which the otel collector scrapes the metrics targets is irrelevant?
- For example, if I define scrape_interval as 10s in the receiver of an otel collector, and the interval within the target_allocator section is 30s, will that affect the metric-resolution?

**Comment by jaronoff97** [comment]
this would be an issue for the prometheus receiver, but happy to answer it here. The interval there is [how frequently the collector](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/targetallocator/manager.go#L76) should query the target allocator for new jobs as part of its own configuration.

**Comment by bohub12** [comment]
@jaronoff97, Thank you for your kind response! I see that it was the interval that the otel collector queries the target allocator to see if there is a new job to scrape. 

However, I still have a question: when writing the OpenTelemetryCollector CRD spec, is there any way to specify that interval as well? I'm asking because when I look at the [OpenTelemetryCollector CRD API](https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api/opentelemetrycollectors.md) and [TargetAllocator CRD API](https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api/targetallocators.md), there doesn't seem to be any configuration to specify that interval.

**Comment by jaronoff97** [comment]
because this is part of the prometheus receiver, you'll just set it in there. example code:
```
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: stateful
spec:
  config:
    receivers:
      jaeger:
          protocols:
            grpc: {}

      # Collect own metrics
      prometheus:
        target_allocator:
          endpoint: http://collector-with-ta-targetallocator:80
          interval: 30s
          collector_id: $POD_NAME
```

We actually do this by default for you when enable the target allocator in the [CRD](https://github.com/open-telemetry/opentelemetry-operator/blob/3fcd369b3e7069c1d6724948778e74115dd83034/tests/e2e-openshift/must-gather/install-target-allocator.yaml#L68-L70), but if you wanted to override it you can do the above and change it to your whim.
