### ISSUE TITLE
[Operator] No automatic rolling update of an auto-instrumented pod occurs after changes to the Instrumentation object

### ISSUE THREAD

**Issue by sswieton** [open-telemetry/opentelemetry-operator#3868]
### Component(s)

auto-instrumentation

## Description

After changes in Instrumentation Object, No automatic rolling update of the auto-instrumented pod occurs.

## Steps to Reproduce

1) The OpenTelemetry operator is deployed in a Kubernetes cluster.
2) An OpenTelemetry Collector instance is deployed.
3) An Instrumentation instance is deployed to send OTLP data to the collector instance.
4) An application is deployed using the OTLP SDK with instrumentation enabled.

At this point, the auto-instrumentation is working correctly, and the following environment variables have been added to my application:

```yaml
      OTEL_SERVICE_NAME:                   otel-test-app
      OTEL_EXPORTER_OTLP_ENDPOINT:         http://otelcol-central-collector-headless:4317
      OTEL_RESOURCE_ATTRIBUTES_POD_NAME:   otel-test-app-79cb7b4577-xfrq7 (v1:metadata.name)
      OTEL_RESOURCE_ATTRIBUTES_NODE_NAME:   (v1:spec.nodeName)
```

The concern is about the changes. 
I want to apply some modifications to the Instrumentation object, such as updating the collector endpoint.

## Expected Result

My expectation is that these changes will be detected by the controller, and a rolling update will be managed automatically for my application to reflect the new OpenTelemetry endpoint.
But this is not the case. 

Since this usecase seems to be a basic one, did I miss something?

What are the supported changes in the Instrumentation object that can trigger a rolling update of the instrumented pod?

Thanks for your support

## Actual Result

No rolling update is performed on my instrumented application, which continues to use the initial OTEL variables.

### Kubernetes Version

v1.31.6-gke.1020000

### Operator version

 0.120.0

### Collector version

contrib

## Environment

Chart : opentelemetry-operator-0.84.1  
Operator : 0.120.0

### Log output

```shell

```

### Additional context

OpenTelemetryCollector instance :

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otelcol-central
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib
  config:

    receivers:

      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318

    exporters:

      debug/verbose:
        verbosity: detailed

    service:
      pipelines:
        
        metrics:
          receivers:
            - otlp
          processors: []
          exporters: 
            - debug/verbose     

        logs:
          receivers:
            - otlp
          processors: []
          exporters: 
            - debug/verbose        

        traces:
          receivers: 
            - otlp
          processors: [] 
          exporters:
            - debug/verbose          
```

Instrumentation instance

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otelcol-instrumentation-grpc
spec:
  env: 
  exporter:
    endpoint: 'http://otelcol-central-collector-headless:4317'
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
```

Annotations setup in the instrumented application
  
```yaml 
annotations:
  instrumentation.opentelemetry.io/inject-sdk: 'otelcol-instrumentation-grpc'
```
