### ISSUE TITLE
Missing RBAC when using k8sattributes

### ISSUE THREAD

**Issue by trexx** [open-telemetry/opentelemetry-operator#3875]
### Component(s)

collector

## Description
When using k8sattributes, the collector pods are missing permissions to access pods and replicasets.

As I am installing the operator via the helm chart, `values.manager.createRbacPermissions` is `true` and I have verified the operator has permissions.

```yaml
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
```

## Steps to Reproduce
Minimal spec:

```yaml
spec:
  config:
    exporters:
      otlp/tempo:
        endpoint: tempo-distributor.tempo.svc.cluster.local:4317
        tls:
          insecure: true
    processors:
      k8sattributes: {}
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: '0.0.0.0:4317'
    service:
      pipelines:
        traces:
          exporters:
            - otlp/tempo
          processors:
            - k8sattributes
          receivers:
            - otlp
      telemetry:
        metrics:
          address: '0.0.0.0:8888'
  mode: deployment
  resources: {}
  podDnsConfig: {}
  managementState: managed
  upgradeStrategy: automatic
  ingress:
    route: {}
  daemonSetUpdateStrategy: {}
  targetAllocator:
    allocationStrategy: consistent-hashing
    filterStrategy: relabel-config
    observability:
      metrics: {}
    prometheusCR:
      scrapeInterval: 30s
    resources: {}
  image: 'otel/opentelemetry-collector-contrib:0.123.0'
  replicas: 2
  ipFamilyPolicy: SingleStack
  configVersions: 3
```

## Expected Result
No errors in the log

## Actual Result
Errors in the log suggesting the service account has no access

### Kubernetes Version

1.31

### Operator version

0.121.0

### Collector version

0.123.0

### Log output

```shell
"Unhandled Error" err="k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:observability:cluster-otel-collector\" cannot list resource \"pods\" in API group \"\" at the cluster scope" logger="UnhandledError"

"Unhandled Error" err="k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: Failed to watch *v1.ReplicaSet: failed to list *v1.ReplicaSet: replicasets.apps is forbidden: User \"system:serviceaccount:observability:cluster-otel-collector\" cannot list resource \"replicasets\" in API group \"apps\" at the cluster scope" logger="UnhandledError"
```

### Additional context

If I add my own clusterroles and bindings, the errors are fixed.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-k8sattributes
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - 'apps'
  resources:
    - replicasets
  verbs:
    - get
    - list
    - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: otel-collector-k8sattributes
subjects:
- kind: ServiceAccount
  name: cluster-otel-collector
  namespace: observability
roleRef:
  kind: ClusterRole
  name: otel-collector-k8sattributes
  apiGroup: "rbac.authorization.k8s.io"
```
