### ISSUE TITLE
operator does not support full targetallocator config schema (example: allocationFallbackStrategy)

### ISSUE THREAD

**Issue by aglarendil** [open-telemetry/opentelemetry-operator#3892]
## Description
I tried to use a field supported by TA and bumped into an issue of these values not being synchronized, so I cannot use a fallbackStrategy to query a couple of targets that are not bound to a "node" object (i.e. kube apiserver serviceMonitor)
i.e. here are the settings for opentelemetry-kube-stack where I create a target-allocator daemonset to collect metrics from various services.
It gets passed as is to the operator
```  
target-allocator:
    targetAllocator:
      allocationStrategy: per-node
      allocationFallbackStrategy: consistent-hashing
```
The flag, while it can be assumed to be valid, is not passed through the layers of helm -> operator -> collector
## Steps to Reproduce
set allocationFallbackStrategy (or any TA config option from the config.go schema converting it snake_case -> camelCase) 
## Expected Result
a correspondingly configured Collector object is created
## Actual Result
the field is dropped

### Kubernetes Version

1.31

### Operator version

0.120

### Collector version

0.123.0

## Environment
Ubuntu 24.04

### Log output

```shell

```
