### ISSUE TITLE
Service Monitor doesnt work

### ISSUE THREAD

**Issue by alexkorotysh** [open-telemetry/opentelemetry-operator#3897]
## Description
ServiceMonitor doesn't work out the box

<img width="2509" alt="Image" src="https://github.com/user-attachments/assets/979cf88e-12a2-4673-8946-412444feaf33" />

## Steps to Reproduce
Deploy Operator
```
  - name: opentelemetry-operator
    namespace: monitoring
    chart: open-telemetry/opentelemetry-operator
    version: 0.84.2
    # Ref: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/values.yaml
    values:
      - values.opentelemetry-operator.yml
```

values.opentelemetry-operator.yml:
```
manager:
  serviceMonitor:
    enabled: true
  collectorImage: 
    repository: "otel/opentelemetry-collector-k8s"
```

Deploy OpenTelemetryCollector

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-infra
  namespace: monitoring
spec:
  mode: deployment
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.123.1
  serviceAccount: otel-infra-collector
  securityContext:
    runAsUser: 1005
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL
  replicas: 1
  observability:
    metrics:
      enableMetrics: true
  config: |
    extensions:
      headers_setter:
        headers:
          - action: insert
            key: X-Scope-OrgID
            value: "1"
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      tail_sampling:
        decision_wait: 5s
        num_traces: 100
        policies:
          - name: drop_kube_probe
            type: string_attribute
            string_attribute:
              key: http.user_agent
              values: [kube-probe/.*]
              enabled_regex_matching: true
              invert_match: true
              
      filter/droptraces:
        error_mode: ignore
        traces:
          span: 
            - IsMatch(attributes["url.path"], "^/health$")
            - attributes["rpc.service"] == "grpc.health.v1.Health"
            - attributes["http.server_name"] == "_"

      k8sattributes:
        auth_type: serviceAccount
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.uid
            - k8s.container.name
            - k8s.pod.start_time
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: connection

      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 5000
        send_batch_max_size: 10000
        timeout: 10s

    connectors:
      spanmetrics:
        dimensions:
          - name: http.method
          - name: http.status_code
          - name: http.target
          - name: http.host

    exporters:
      otlp:
        endpoint: http://tempo-distributor.monitoring.svc.cluster.local:4317
        tls:
          insecure: true
      otlphttp:
        endpoint: http://loki.monitoring.svc.cluster.local:3100/otlp
        headers:
          X-Scope-OrgID: "1"
      prometheus:
        endpoint: "0.0.0.0:8889"

    service:
      extensions: [ headers_setter ]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [k8sattributes, filter/droptraces, tail_sampling,  memory_limiter, batch]
          exporters: [spanmetrics, otlp]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp]
        metrics:
          receivers: [spanmetrics]
          exporters: [prometheus]
      telemetry:
        logs:
          level: INFO
```

<img width="1182" alt="Image" src="https://github.com/user-attachments/assets/c35f6b71-382c-40fc-9873-e0429ff1d385" />
<img width="1117" alt="Image" src="https://github.com/user-attachments/assets/3fd1bf8c-f19e-473b-8f16-7f7aff911d25" />
<img width="1917" alt="Image" src="https://github.com/user-attachments/assets/f5404f96-89ed-49a7-9112-71a5a9df8e7d" />

## Expected Result
Autoscraping metrics
## Actual Result

self monitoring collector doesn't work

### Kubernetes Version

1.31

### Operator version

0.120.0

### Collector version

0.123.1

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell

```

**Comment by iblancasa** [comment]
Can you provide the generated `ServiceMonitor` and the `ConfigMap` with the configuration?

**Comment by alexkorotysh** [comment]
```
❯ kubectl describe servicemonitor otel-infra-monitoring-collector -n monitoring
Name:         otel-infra-monitoring-collector
Namespace:    monitoring
Labels:       app.kubernetes.io/component=opentelemetry-collector
              app.kubernetes.io/instance=monitoring.otel-infra
              app.kubernetes.io/managed-by=opentelemetry-operator
              app.kubernetes.io/name=otel-infra-monitoring-collector
              app.kubernetes.io/part-of=opentelemetry
              app.kubernetes.io/version=0.123.1
Annotations:  <none>
API Version:  monitoring.coreos.com/v1
Kind:         ServiceMonitor
Metadata:
  Creation Timestamp:  2025-04-11T06:06:03Z
  Generation:          1
  Owner References:
    API Version:           opentelemetry.io/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  OpenTelemetryCollector
    Name:                  otel-infra
    UID:                   486643d3-9e99-40d0-9e35-2099a9db6f25
  Resource Version:        12627268
  UID:                     b99c8bba-9cbc-4931-83f1-55ae1ec9d03c
Spec:
  Endpoints:
    Port:  monitoring
  Namespace Selector:
    Match Names:
      monitoring
  Selector:
    Match Labels:
      app.kubernetes.io/component:                       opentelemetry-collector
      app.kubernetes.io/instance:                        monitoring.otel-infra
      app.kubernetes.io/managed-by:                      opentelemetry-operator
      app.kubernetes.io/part-of:                         opentelemetry
      operator.opentelemetry.io/collector-service-type:  monitoring
Events:                                                  <none>
```
```
❯ kubectl describe servicemonitor otel-infra-collector -n monitoring
Name:         otel-infra-collector
Namespace:    monitoring
Labels:       app.kubernetes.io/component=opentelemetry-collector
              app.kubernetes.io/instance=monitoring.otel-infra
              app.kubernetes.io/managed-by=opentelemetry-operator
              app.kubernetes.io/name=otel-infra-collector
              app.kubernetes.io/part-of=opentelemetry
              app.kubernetes.io/version=0.123.1
Annotations:  <none>
API Version:  monitoring.coreos.com/v1
Kind:         ServiceMonitor
Metadata:
  Creation Timestamp:  2025-04-11T06:06:03Z
  Generation:          1
  Owner References:
    API Version:           opentelemetry.io/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  OpenTelemetryCollector
    Name:                  otel-infra
    UID:                   486643d3-9e99-40d0-9e35-2099a9db6f25
  Resource Version:        12627266
  UID:                     569eef6d-f67b-4547-b349-06986ad0ff03
Spec:
  Endpoints:
    Port:  prometheus
  Namespace Selector:
    Match Names:
      monitoring
  Selector:
    Match Labels:
      app.kubernetes.io/component:                       opentelemetry-collector
      app.kubernetes.io/instance:                        monitoring.otel-infra
      app.kubernetes.io/managed-by:                      opentelemetry-operator
      app.kubernetes.io/part-of:                         opentelemetry
      operator.opentelemetry.io/collector-service-type:  base
Events:                                                  <none>
```

**Comment by alexkorotysh** [comment]
```
kubectl describe deployment otel-infra-collector -n monitoring
Name:                   otel-infra-collector
Namespace:              monitoring
CreationTimestamp:      Mon, 07 Apr 2025 23:04:43 +0300
Labels:                 app.kubernetes.io/component=opentelemetry-collector
                        app.kubernetes.io/instance=monitoring.otel-infra
                        app.kubernetes.io/managed-by=opentelemetry-operator
                        app.kubernetes.io/name=otel-infra-collector
                        app.kubernetes.io/part-of=opentelemetry
                        app.kubernetes.io/version=0.123.1
Annotations:            deployment.kubernetes.io/revision: 58
                        meta.helm.sh/release-name: otel
                        meta.helm.sh/release-namespace: monitoring
Selector:               app.kubernetes.io/component=opentelemetry-collector,app.kubernetes.io/instance=monitoring.otel-infra,app.kubernetes.io/managed-by=opentelemetry-operator,app.kubernetes.io/part-of=opentelemetry
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/component=opentelemetry-collector
                    app.kubernetes.io/instance=monitoring.otel-infra
                    app.kubernetes.io/managed-by=opentelemetry-operator
                    app.kubernetes.io/name=otel-infra-collector
                    app.kubernetes.io/part-of=opentelemetry
                    app.kubernetes.io/version=0.123.1
  Annotations:      meta.helm.sh/release-name: otel
                    meta.helm.sh/release-namespace: monitoring
                    opentelemetry-operator-config/sha256: 216e72727e43a546128d58fa51987e945bb0954191492ecd057fd089d5358def
                    prometheus.io/path: /metrics
                    prometheus.io/port: 8888
                    prometheus.io/scrape: true
  Service Account:  otel-infra-collector
  Containers:
   otc-container:
    Image:           ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.123.1
    Ports:           8888/TCP, 4317/TCP, 4318/TCP, 8889/TCP
    Host Ports:      0/TCP, 0/TCP, 0/TCP, 0/TCP
    SeccompProfile:  RuntimeDefault
    Args:
      --config=/conf/collector.yaml
    Environment:
      POD_NAME:   (v1:metadata.name)
    Mounts:
      /conf from otc-internal (rw)
  Volumes:
   otc-internal:
    Type:          ConfigMap (a volume populated by a ConfigMap)
    Name:          otel-infra-collector-216e7272
    Optional:      false
  Node-Selectors:  <none>
  Tolerations:     <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  otel-infra-collector-665db48c68 (0/0 replicas created), otel-infra-collector-7767dbbf76 (0/0 replicas created), otel-infra-collector-9589b4bd5 (0/0 replicas created), otel-infra-collector-74fddfbccf (0/0 replicas created), otel-infra-collector-548f965f5f (0/0 replicas created), otel-infra-collector-85c5cf7c9 (0/0 replicas created), otel-infra-collector-f897b9554 (0/0 replicas created), otel-infra-collector-7d8986d498 (0/0 replicas created), otel-infra-collector-844b9bc578 (0/0 replicas created), otel-infra-collector-6d4f864d76 (0/0 replicas created)
NewReplicaSet:   otel-infra-collector-578bd55689 (1/1 replicas created)
Events:          <none>
```

**Comment by alexkorotysh** [comment]
```
kubectl describe configmap otel-infra-collector-216e7272 -n monitoring
Name:         otel-infra-collector-216e7272
Namespace:    monitoring
Labels:       app.kubernetes.io/component=opentelemetry-collector
              app.kubernetes.io/instance=monitoring.otel-infra
              app.kubernetes.io/managed-by=opentelemetry-operator
              app.kubernetes.io/name=otel-infra-collector
              app.kubernetes.io/part-of=opentelemetry
              app.kubernetes.io/version=0.123.1
Annotations:  meta.helm.sh/release-name: otel
              meta.helm.sh/release-namespace: monitoring

Data
====
collector.yaml:
----
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  otlp:
    endpoint: http://tempo-distributor.monitoring.svc.cluster.local:4317
    tls:
      insecure: true
  otlphttp:
    endpoint: http://loki.monitoring.svc.cluster.local:3100/otlp
    headers:
      X-Scope-OrgID: "1"
  prometheus:
    endpoint: 0.0.0.0:8889
processors:
  batch:
    send_batch_max_size: 10000
    send_batch_size: 5000
    timeout: 10s
  filter/droptraces:
    error_mode: ignore
    traces:
      span:
        - IsMatch(attributes["url.path"], "^/health$")
        - attributes["http.host"] == "grafana.XXXXXXXX"
        - attributes["http.host"] == "sso.XXXXXXXX"
        - attributes["http.host"] == "pwd.XXXXXXXX"
        - attributes["http.host"] == "argocd.XXXXXXXX"
        - attributes["http.host"] == "coreXXXXXXXX"
        - attributes["rpc.service"] == "grpc.health.v1.Health"
        - attributes["http.server_name"] == "_"
  k8sattributes:
    auth_type: serviceAccount
    extract:
      metadata:
        - k8s.pod.name
        - k8s.namespace.name
        - k8s.node.name
        - k8s.pod.uid
        - k8s.container.name
        - k8s.pod.start_time
    passthrough: false
    pod_association:
      - sources:
          - from: resource_attribute
            name: k8s.pod.ip
      - sources:
          - from: connection
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
  tail_sampling:
    decision_wait: 5s
    num_traces: 100
    policies:
      - name: drop_kube_probe
        string_attribute:
          enabled_regex_matching: true
          invert_match: true
          key: http.user_agent
          values:
            - kube-probe/.*
        type: string_attribute
connectors:
  spanmetrics:
    dimensions:
      - name: http.method
      - name: http.status_code
      - name: http.target
      - name: http.host
extensions:
  headers_setter:
    headers:
      - action: insert
        key: X-Scope-OrgID
        value: "1"
service:
  extensions:
    - headers_setter
  telemetry:
    logs:
      level: INFO
    metrics:
      address: 0.0.0.0:8888
  pipelines:
    logs:
      exporters:
        - otlphttp
      processors:
        - memory_limiter
        - batch
      receivers:
        - otlp
    metrics:
      exporters:
        - prometheus
      receivers:
        - spanmetrics
    traces:
      exporters:
        - spanmetrics
        - otlp
      processors:
        - k8sattributes
        - filter/droptraces
        - tail_sampling
        - memory_limiter
        - batch
      receivers:
        - otlp



BinaryData
====

Events:  <none>
```
