### ISSUE TITLE
Mimir received a series with an invalid label/metric name

### ISSUE THREAD

**Issue by sigurdfalk** [open-telemetry/opentelemetry-operator#3898]
### Component(s)

collector

## Description

After upgrading from Operator version `v0.117.0` and collector version `v0.117.0`, we see metric being dropped by Mimir due to "err-mimir-metric-name-invalid" and "err-mimir-label-invalid". More details about specific metric and label in log output.

## Steps to Reproduce

We install the OTEL Operator with the Helm Chart `v0.84.2` with the following values:

```
  replicaCount: 2
  manager:
    autoInstrumentationImage:
      java:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java
        tag: "2.14.0" # Can be removed when v2 is enabled by default
    featureGatesMap:
      operator.observability.prometheus: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
      defaultRules:
        enabled: true
  admissionWebhooks:
    certManager:
      enabled: false
```

### Kubernetes Version

1.30.11

### Operator version

0.120.0

### Collector version

0.120.0

## Environment
OS: AzureLinux on AKS
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell
{
  "time": "2025-04-11T11:30:34.140713136Z",
  "level": "ERROR",
  "source": "queue_manager.go:1670",
  "msg": "non-recoverable error",
  "component": "remote",
  "remote_name": "a5eb7f",
  "url": "http://mimir-distributed-gateway.system-mimir.svc/api/v1/push",
  "failedSampleCount": 2000,
  "failedHistogramCount": 0,
  "failedExemplarCount": 0,
  "err": "server returned HTTP status 400 Bad Request: received a series with invalid metric name: 'http.client.duration_bucket' (err-mimir-metric-name-invalid)\n"
}



{
  "time": "2025-04-11T11:18:19.851742758Z",
  "level": "ERROR",
  "source": "queue_manager.go:1670",
  "msg": "non-recoverable error",
  "component": "remote",
  "remote_name": "a5eb7f",
  "url": "http://mimir-distributed-gateway.system-mimir.svc/api/v1/push",
  "failedSampleCount": 2000,
  "failedHistogramCount": 0,
  "failedExemplarCount": 0,
  "err": "server returned HTTP status 400 Bad Request: received a series with an invalid label: 'service.instance.id' series: 'otelcol_processor_batch_batch_send_size_bucket{cluster=\"aks-tools-mgt-test-003\", container=\"otc-container\", endpoint=\"monitoring\", instance=\"10.90.9.137:8889\", job=\"otel-daemonset-collector-monitoring' (err-mimir-label-invalid)\n"
}
```

**Comment by pavolloffay** [comment]
Yes I think it is most likely issue with the Prometheus exporter. @swiatekm WDYT?

**Comment by swiatekm** [comment]
@sigurdfalk it would help a lot if you could post your collector configuration. This is a problem that could conceivably be caused by any of the prometheus-related components.

**Comment by sigurdfalk** [comment]
This is my config (copied after applied to k8s, so redacted/removed some noisy/sensitive fields):

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  labels:
    app: opentelemetry-operator
  name: otel-daemonset
  namespace: system-opentelemetry-operator
spec:
  config:
    exporters:
      otlphttp/loki:
        endpoint: xxx
        headers:
          Authorization: ${GRAFANA_LOKI_BASIC_AUTH}
          X-Scope-OrgID: xxx
    extensions:
      file_storage:
        directory: /var/lib/otelcol
      health_check:
        endpoint: 0.0.0.0:13134
    processors:
      batch: {}
      filter/loki-k8s:
        ...
      k8sattributes:
        ...
      memory_limiter:
        ...
      transform/filelog-receiver:
        ...
    receivers:
      filelog/k8s:
        ...
    service:
      extensions:
      - health_check
      - file_storage
      pipelines:
        logs/loki-k8s:
          exporters:
          - otlphttp/loki
          processors:
          - memory_limiter
          - k8sattributes
          - filter/loki-k8s
          - transform/filelog-receiver
          - batch
          receivers:
          - filelog/k8s
      telemetry:
        logs:
          encoding: json
          level: info
        metrics:
          address: 0.0.0.0:8889
          level: detailed
  configVersions: 3
  daemonSetUpdateStrategy: {}
  deploymentUpdateStrategy: {}
  env:
  - name: GOMEMLIMIT
    value: 13000MiB
  envFrom:
  - secretRef:
      name: collector-grafana-loki-auth
  hostNetwork: true
  ingress:
    route: {}
  ipFamilyPolicy: SingleStack
  managementState: managed
  mode: daemonset
  observability:
    metrics:
      enableMetrics: true
  podDnsConfig: {}
  replicas: 1
  resources: {}
  securityContext:
    runAsGroup: 0
    runAsUser: 0
  serviceAccount: otel-daemonset
  targetAllocator:
    allocationStrategy: consistent-hashing
    filterStrategy: relabel-config
    observability:
      metrics: {}
    prometheusCR:
      scrapeInterval: 30s
    resources: {}
  tolerations:
  - effect: NoSchedule
    operator: Exists
  upgradeStrategy: automatic
  volumeMounts:
  - mountPath: /var/log/pods
    name: varlogpods
    readOnly: true
  - mountPath: /var/lib/otelcol
    name: varlibotelcol
  volumes:
  - hostPath:
      path: /var/log/pods
    name: varlogpods
  - hostPath:
      path: /var/lib/otelcol
      type: DirectoryOrCreate
    name: varlibotelcol
```
