### ISSUE TITLE
Exporting failed "unknown service opentelemetry.proto.collector.logs.v1.LogsService"

### ISSUE THREAD

**Issue by yuzhouliu9** [open-telemetry/opentelemetry-operator#3909]
### Component(s)

collector

## Description
I have an existing splunk-otel-collector pipeline.
I'm using the OpenTelemetryCollector to set up a separate pipeline to export to S3.
I added a exporter on the splunk-otel-collector to forward logs to the new OpenTelemetryCollector.
```mermaid
flowchart LR
    A[Splunk agent Receivers] --> B[Pipeline] --> C(Splunk Exporter)
    B[Pipeline] --> D[OpenTelemetryCollector Exporter]
    
    X[OpenTelemetryCollector Receiver] --> Y[Pipeline] --> Z[S3 Exporter]
```

The splunk-otel-collector has these errors when exporting to the OpenTelemetryCollector receiver:
```
2025-04-14T21:10:28.205Z	error	exporterhelper/retry_sender.go:126	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "data_type": "logs", "name": "otlp/user", "error": "Permanent error: rpc error: code = Unimplemented desc = unknown service opentelemetry.proto.collector.logs.v1.LogsService", "dropped_items": 17}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/retry_sender.go:126
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send
	go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/logs.go:170
go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).consume
	go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/queue_sender.go:115
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue[...]).Consume
	go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/internal/bounded_memory_queue.go:55
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*QueueConsumers[...]).Start.func1
	go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/internal/consumers.go:43
```

Logs are going to Splunk fine, so I don't think there is an issue on the splunk-otel-collector config.

I think there is some config mismatch issue with the OpenTelemetryCollector.
The service name on the exporter is correct because when the OpenTelemetryCollector is down there is a different error of `no such host`. So something is wrong with the gRPC.

## Steps to Reproduce
On the splunk-otel-collector, I added this exporter (reduced config for brevity)
```diff
exporters:
...
+  otlp/user:
+    endpoint: s3-collector-collector:4317
+    tls:
+      insecure: true

service:
...
  pipelines:
    logs:
      exporters:
      - splunk_hec
+     - otlp/user
```

The opentelemetry-operator was deployed via helm-chart with these values. The `tag` matches the splunk-otel-collector version in use. I've also tried the latest tags `v0.122.0` and `0.123.0` respectively but same issue.
```
manager:
  image:
    repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
    tag: v0.91.0
  collectorImage:
    repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
    tag: 0.91.0

admissionWebhooks:
  create: true
  failurePolicy: Ignore
  timeoutSeconds: 3
  certManager:
    enabled: true
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: selfsigned

  autoGenerateCert:
    enabled: false
```

OpenTelemetryCollector spec. I've also tried an updated spec on `opentelemetry-collector-contrib:0.123.0`, same issue
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: s3-collector
  namespace: monitoring
spec:
  upgradeStrategy: automatic
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            max_recv_msg_size_mib: 10
          http:
            endpoint: 0.0.0.0:4318
    processors:
      # batch: null
      memory_limiter:
        check_interval: 2s
        limit_percentage: 90
        spike_limit_percentage: 8

    exporters:
      awss3/devops:
        s3uploader:
          region: 'us-east-1'
          s3_bucket: 'my-bucket'
          s3_prefix: 'devops'

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [awss3/devops]
```

## Expected Result
Exporter from splunk-otel-collector is able to successfully send logs to OpenTelemetryCollector receiver.

## Actual Result
Errors on the exporter

### Kubernetes Version

1.27.16

### Operator version

v0.91.0 v0.122.0

### Collector version

0.91.0 0.123.0

### Log output

```shell

```
