### ISSUE TITLE
Operator overwrites fields in `.spec.config.service.telemetry` (e.g. internal log level)

### ISSUE THREAD

**Issue by milas** [open-telemetry/opentelemetry-operator#3913]
### Component(s)

collector

## Description
Starting with 0.122, it's not possible to override `service.telemetry.logs.level`.

## Steps to Reproduce
Create an `OpenTelemetryCollector` CRD with:
```yaml
spec:
  config:
    service:
      telemetry:
        logs:
          level: debug
```

## Expected Result
Log level is preserved on CRD

## Actual Result
CRD deletes fields in `.spec.config.service.telemetry`

```yaml
spec:
  config:
    service:
      telemetry:
        metrics:
          readers:
          - pull:
              exporter:
                prometheus:
                  host: 0.0.0.0
                  port: 8888
```

### Kubernetes Version

1.31

### Operator version

0.122.0

### Collector version

0.122.1

### Log output

```shell

```

### Additional context

Regression introduced by https://github.com/open-telemetry/opentelemetry-operator/pull/3874

When trying to add the readers, it will drop almost every other field of `*Telemetry` because it uses an intermediate Go type to extract the reader address, losing all the other fields in the process.
