### ISSUE TITLE
Downgrading operator does not downgrade managed opentelemetrycollectors

### ISSUE THREAD

**Issue by dschaaff** [open-telemetry/opentelemetry-operator#3919]
### Component(s)

collector

## Description

When downgrading the operator to an older version, the managed opentelemetry collectors are not downgraded. 

## Steps to Reproduce

1). Install 0.122 of the operator (helm chart 0.86).
2). Create a managed collector 

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: test
  namespace: opentelemetry-operator
spec:
  mode: sidecar
  resources:
    requests:
      memory: 50Mi
      cpu: 5m
    limits:
      memory: 150Mi
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25

      resourcedetection/env:

      batch:

    exporters:
      prometheus:
        endpoint: "0.0.0.0:9317"
        resource_to_telemetry_conversion:
          enabled: true
        metric_expiration: 10m

    extensions:
      health_check:

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, resourcedetection/env, batch]
          exporters: [prometheus]
```
3) Down grade operator to 0.120 (helm chart 0.84)

The manged collectors will remain on version 0.122 and not be properly downgraded 

```
NAME   MODE      VERSION   READY   AGE   IMAGE   MANAGEMENT
test   sidecar   0.122.1           15m           managed
```

```{"level":"INFO","timestamp":"2025-04-17T16:12:06Z","logger":"instrumentation-upgrade","message":"no instances to upgrade"}```

## Expected Result

Managed collectors downgrade to 0.120.

## Actual Result

Downgrading the operator has no effect on the version of existing managed collectors.

### Kubernetes Version

1.30

### Operator version

0.122, 0.122

### Collector version

0.122.1

### Log output

```shell

```
