### ISSUE TITLE
Outdated Java autoinstrumentation version

### ISSUE THREAD

**Issue by mariusgiger** [open-telemetry/opentelemetry-operator#3966]
### Describe the issue you're reporting

We are currently trying to setup OTEL for microservices using Spring Boot with the [Java auto instrumentation](https://opentelemetry.io/docs/zero-code/java/agent/). We are using the reactive stack with Webflux and MongoDB.

Spans reported by the MongoDB auto instrumentation (io.opentelemetry.mongo-3.1) were not linked to the parent span of the HTTP request. This resulted in many different spans being reported for each call.

We were able to resolve this issue by hardcoding the image of the autoinstrumentation:
```
kind: Instrumentation
...
spec:
  java:
    image: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.15.0"
```

The default image when creating an `Instrumentation` resource is set to 1.33.6 which is an older version that apparently has this bug.

The version is hardcoded [here](https://github.com/open-telemetry/opentelemetry-operator/blob/main/versions.txt). 

Can this safely be updated? If yes, I will open a PR.
