### ISSUE TITLE
otel/opentelemetry-collector-contrib:0.124.1 this image can not pull

### ISSUE THREAD

**Issue by huangxiaofeng10047** [open-telemetry/opentelemetry-operator#3977]
### Component(s)

collector

### Kubernetes Version

1.24.0

### Operator version

0.124.0

### Collector version

0.124.1

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell

```

### Additional context

![Image](https://github.com/user-attachments/assets/bf608dd2-be9a-4d7f-8c7e-12318adaca47)

**Comment by KOCEAN33** [comment]
there is no 0.124 collector on docker hub due to image upload limit rate

check this issue (https://github.com/open-telemetry/opentelemetry-collector-releases/issues/946)

You can use 0.123.0 image or ghcr (https://github.com/orgs/open-telemetry/packages?repo_name=opentelemetry-collector-releases)
 
example

```YAML
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  image: otel/opentelemetry-collector-k8s:0.123.0
```
