### ISSUE TITLE
Enable mtls irrespective of certManager resource

### ISSUE THREAD

**Issue by younusmohmmad** [open-telemetry/opentelemetry-operator#3982]
## Description

Trying to enable mtls between TA and collector without the support of certManager
We have our own cert management service to issue certs and mount these secrets.

## Steps to Reproduce
Enable mtls flag in operator
Override tls config in prometheus receiver under target_allocator:
by pointing the cert locations

## Expected Result
Without the dependency on certManager , operator shall enable mtls and 
use the certs provided via the config

## Actual Result
As certManager resource is not present, operator is overriding the config
with no-tls config (http://<ta>:80)

### Kubernetes Version

1.23.0

### Operator version

0.123.0

### Collector version

0.125.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell

```

### Additional context

args:
   enable-https-server: "true"
   https-ca-file: /run/secrets/ta-ca/ca.crt
   https-tls-cert-file: /run/secrets/ta/certs/cert.crt
   https-tls-key-file: /run/secrets/ta/certs/cert.key
  volumes:
   - name: ta-certs
     secret:
        secretName: ta-cert-secret
   - name: ta-ca-certs
     secret:
        secretName: ta-ca-secret
  volumeMounts:
  - name: ta-certs
    mountPath: /run/secrets/ta/certs
    readOnly: true
  - name: ta-ca-certs
    mountPath: /run/secrets/ta-ca/certs
    readOnly: true

config in prometheus receiver:
prometheus:
    target_allocator:
       endpoint: http://localhost:8080
       timeout: 5s
       tls:
          ca_file: /run/secrets/ca/ca.crt
         cert_file: /run/secrets/client-cert/tls.crt
          key_file: /run/secrets/client-cert/tls.key
          interval: 30s
          collector_id: collector-1        

and the respective certs are mounted from secrets without certManager resource

**Comment by swiatekm** [comment]
This is not supported right now. The reason is that we're not clear on how it should work, exactly. Maybe we can start by adding instructions on how to do it manually with the TargetAllocator CRD, which should be possible.

**Comment by rfranzke** [comment]
@swiatekm What do you think about augmenting both the [`TargetAllocatorSpec`](https://github.com/open-telemetry/opentelemetry-operator/blob/39a0d78154a9570b9a6e82f1eb829c0c8ea8f831/apis/v1alpha1/targetallocator_types.go#L54) and the [`TargetAllocatorEmbedded`](https://github.com/open-telemetry/opentelemetry-operator/blob/39a0d78154a9570b9a6e82f1eb829c0c8ea8f831/apis/v1beta1/opentelemetrycollector_types.go#L149) types with an option to reference `Secret`s containing the required certificates? Using `cert-manager` is fine and a good default, but there should also be a way to manage the certificates outside and just provide them to the `opentelemetry-operator`:

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector-with-ta
spec:
  targetAllocator:
    enabled: true
    tls:
      certificateAuthorityCertificate:
        secretName: <name-of-secret-containing-ca-cert>
        dataKeyCertificate: tls.crt
      serverCertificate: # server certificate for target-allocator (when exposing its HTTPS server)
        secretName: <name-of-secret-containing-server-cert-and-key>
        dataKeyCertificate: tls.crt
        dataKeyKey: tls.key
      clientCertificate: # client certificate for opentelemetry-collector (when talking to target allocator's HTTPS server)
        secretName: <name-of-secret-containing-client-cert-and-key>
        dataKeyCertificate: tls.crt
        dataKeyKey: tls.key
  ...
```

or alternatively

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector-with-ta
  labels:
    opentelemetry.io/target-allocator: ta
spec:
  ...
---
apiVersion: opentelemetry.io/v1alpha1
kind: TargetAllocator
metadata:
  name: ta
spec:
  tls:
    certificateAuthorityCertificate:
      secretName: <name-of-secret-containing-ca-cert>
      dataKeyCertificate: tls.crt
    serverCertificate: # server certificate for target-allocator (when exposing its HTTPS server)
      secretName: <name-of-secret-containing-server-cert-and-key>
      dataKeyCertificate: tls.crt
      dataKeyKey: tls.key
    clientCertificate: # client certificate for opentelemetry-collector (when talking to target allocator's HTTPS server)
      secretName: <name-of-secret-containing-client-cert-and-key>
      dataKeyCertificate: tls.crt
      dataKeyKey: tls.key
```

Happy to get feedback on this :)

Background: We tried to manually provide the certificates to both components and modify their configurations accordingly (w/ MTLS feature gate disabled, obviously, since we don't run `cert-manager`), but `opentelemetry-operator` always falls back to the HTTP endpoint when computing the `opentelemetry-colector`'s configuration:

```yaml
data:
  collector.yaml: |
    receivers:
        prometheus:
            config: {}
            target_allocator:
                collector_id: ${POD_NAME}
                endpoint: http://external-otelcol-targetallocator:80 # we configured this explicitly to point to a manually created HTTPS server, but operator overwrites it
                interval: 30s
                tls:
                    ca_file: /etc/ssl/certs/ca/bundle.crt
                    cert_file: /etc/ssl/certs/client/tls.crt
                    key_file: /etc/ssl/certs/client/tls.key
```
