### ISSUE TITLE
Replace instances of `gopkg.in/yaml.v3`

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#3988]
the package is fully unmaintained and we shouldn't use it anymore.

**Comment by LucaLanziani** [comment]
hello @jaronoff97 replace it with https://pkg.go.dev/sigs.k8s.io/yaml or something else?

**Comment by jaronoff97** [comment]
That one is fine probably, yes

**Comment by jaronoff97** [comment]
iirc sigs.k8s.io is just a wrapper around go yaml, but i hope the k8s folks are maintaining it haha. I think it should be fine to do this move initially, and if we need to do it again we can do it again.

**Comment by LucaLanziani** [comment]
Happy to take this then.

**Comment by jaronoff97** [comment]
awesome, thank you!

**Comment by LucaLanziani** [comment]
With the k8s library the TestConfigYaml result goes from:

```
receivers:
  otlp: null
exporters:
  otlp/exporter: null
processors:
  modify_2000: enabled
connectors:
  con: magic
extensions:
  addon: option1
service:
  extensions:
    - addon
  telemetry:
    insights: yeah!
  pipelines:
    traces:
      exporters:
        - otlp/exporter
        - con
      processors:
        - modify_2000
      receivers:
        - otlp
```

to:

```
connectors:
  con: magic
exporters:
  otlp/exporter: null
extensions:
  addon: option1
processors:
  modify_2000: enabled
receivers:
  otlp: null
service:
  extensions:
  - addon
  pipelines:
    traces:
      exporters:
      - otlp/exporter
      - con
      processors:
      - modify_2000
      receivers:
      - otlp
  telemetry:
    insights: yeah!
```

You can see how lists are not indented while they were with the unsupported library, would you be ok with this new format?
