### ISSUE TITLE
terminationGracePeriodSeconds not applied to daemonset

### ISSUE THREAD

**Issue by tincho-burgos** [open-telemetry/opentelemetry-operator#4003]
### Component(s)

collector

## Description
When setting `terminationGracePeriodSeconds` on the otel-collector agent, it is not applied to the underlying daemonset.
https://github.com/open-telemetry/opentelemetry-operator/blob/main/apis/v1beta1/common.go

https://github.com/open-telemetry/opentelemetry-operator/blob/0cda0e2e94bcb231647d20fc2d1592d4615ad37a/internal/manifests/collector/daemonset.go

## Steps to Reproduce
helm template 

```yaml
---
# Source: dynatrace-otel-collector/templates/agent.yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: something-dynatrace-otel-collector-agent
spec:
  envFrom:
  - secretRef:
      name: something-dynatrace-otel-collector
  env:
  - name: KUBE_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  mode: "daemonset"
  terminationGracePeriodSeconds: 600
...
```

```yaml
# Source values.yaml 
...
# Agent relies on a DaemonSet
agent:
  enabled: true
  terminationGracePeriodSeconds: 600

  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi

  securityContext:
    capabilities:
...
```

## Expected Result
```bash
k get ds/collector 

...
      terminationGracePeriodSeconds: 600
...
```
## Actual Result
The daemonset is using the default value
```bash
k get ds/collector 

...
      terminationGracePeriodSeconds: 30
...
```

### Kubernetes Version

1.30

### Operator version

1.125.0

### Collector version

0.125.0

## Environment
OS Image:                   Amazon Linux 2
Operating System:           linux
Architecture:               arm64
Container Runtime Version:  containerd://1.7.27

### Log output

```shell

```
