### ISSUE TITLE
Duplicate Metrics Collected After Target Allocator Upgrade (v0.121+)

### ISSUE THREAD

**Issue by starzhanganz** [open-telemetry/opentelemetry-operator#4031]
### Component(s)

Target Allocator

## Description
After upgrading the Target Allocator from v0.120 to v0.121, we observed duplicate (sometimes even triplicate) metric samples being scraped by multiple collector instances. This has resulted in inflated metric values and confusion in dashboards and alerts. The issue was not present before the upgrade and seems to be related to changes introduced in Target Allocator versions v0.121 and later. No relevant breaking changes were noted in the release notes.
## Steps to Reproduce
1 Deploy Target Allocator version v0.121 or later alongside otel collector instances in a Kubernetes cluster.

Apply the following configuration:

```yaml
allocation_strategy: least-weighted
collector_selector:
  matchlabels:
    app.kubernetes.io/name: otelcollector
prometheus_cr:
  pod_monitor_selector: {}
  service_monitor_selector: {}
```
we have 4 otelcollector pod are running as STS.

Observe metric values in Google Managed Prometheus.
Config of otelcollector
```yaml
---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
processors:
  memory_limiter:
    check_interval: 60s
    limit_percentage: 80
    spike_limit_percentage: 15
extensions:
  health_check:
exporters:
  debug:
    verbosity: basic
  googlemanagedprometheus:
    project: PROJECT_ID_HERE
    timeout: 20s
    metric:
      add_metric_suffixes: false
      extra_metrics_config:
        enable_target_info: false
        enable_scope_info: false
    sending_queue:
      num_consumers: 40
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers:
        - otlp
      processors:
        - memory_limiter
      exporters:
        - googlemanagedprometheus
        - debug


```
## Expected Result
Each metric should be scraped once per target, resulting in correct (non-duplicated) metric values, with Target Allocator ensuring no overlap in assigned scrape targets among otelcollector instances.
## Actual Result
Multiple otelcollector instances scrape the same targets, leading to duplicate or even triplicate metric samples for the same target. This causes inflated values in dashboards and may trigger false positives in alerting.

### Kubernetes Version

v1.31.7

### Operator version

0.121

### Collector version

0.125

## Environment
go: 1.24.3
os: default otelcollector image version.

### Log output

```shell

```

### Additional context

Switching the strategy from `least-weighted` to `consistent-hashing` resolved the issue. However we may still need to use the `least-weighted`.
