### ISSUE TITLE
Same target from two different jobs missing after targetallocator upgrade 0.121.0+

### ISSUE THREAD

**Issue by gracewehner** [open-telemetry/opentelemetry-operator#4044]
### Component(s)

target allocator

## Description
In a practical case, this happens when two different jobs point to the same target but each job has a different metrics_path. Now the target is only scraped for one of the jobs, whereas before it was scraped for both.

I was able to change of the unit tests to reproduce this and attach a debugger. I have narrowed it down to this PR: https://github.com/open-telemetry/opentelemetry-operator/pull/3832 that changes the hash for a target from `t.JobName + t.TargetURL + strconv.FormatUint(t.Labels.Hash(), 10)` to `t.Labels.Hash()`.

The `targetgroup` map coming from the Prometheus discovery manager does not contain job as a label when the targets are being processed by the Target Allocator and stored in the target list:

<img width="417" alt="Image" src="https://github.com/user-attachments/assets/ed0deca3-e76e-41c4-8ae3-da6fec6c8e65" />

`Job` is the key to a `targetgroup` object in the map, which does have the `address` as a label per target. This is also not added a label when processing the targets right before hashing them: https://github.com/swiatekm/opentelemetry-operator/blob/main/cmd/otel-allocator/internal/target/discovery.go#L195. The metrics path is also not a label at the time.

## Steps to Reproduce
Use a scrape config pointing to the same target from two different jobs for Target Allocator version 0.121.0 and up:

```yaml
config:
  scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ["prom.domain:9001", "prom.domain:9002", "prom.domain:9003"]
  - job_name: prometheus2
    static_configs:
    - targets: ["prom.domain:9001"]
```

## Expected Result
Target `prom.domain:9001` will be allocated to a collector for both jobs `prometheus` or `prometheus2`.

## Actual Result
Target `prom.domain:9001` will be allocated to a collector for only one job of `prometheus` or `prometheus2`, but not both.

### Kubernetes Version

1.31.8

### Operator version

v0.121.0+

### Collector version

v0.121.0+

## Environment
OS: "Ubuntu 20.04"

### Log output

```shell

```

**Comment by gracewehner** [comment]
Thanks @swiatekm for the quick reply. The above debugger screenshot is for the config:
```
config:
  scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics1
    static_configs:
    - targets: ["prom.domain:9001", "prom.domain:9002", "prom.domain:9003"]
  - job_name: prometheus2
    metrics_path: /metrics2
    static_configs:
    - targets: ["prom.domain:9001"]
```

I was surprised to not see the `__metrics_path__` labels there too, along with job.

I looked into it more now just to double-check and the labels in the targetgroup and target returned by the discovery manager are the bare minimum with __address__ and some static labels. Then the scrape manager later takes these and combines these with more labels from the scrape config for job, __metrics_path__, etc: https://github.com/prometheus/prometheus/blob/main/scrape/target.go#L445

Discovery manager target groups: https://github.com/prometheus/prometheus/blob/main/discovery/targetgroup/targetgroup.go

I am happy to help with making a PR with a fix, but I'm not sure what strategy we want to take for the fix
