### ISSUE TITLE
Intermittent target loss during distribution by TargetAllocator

### ISSUE THREAD

**Issue by kwonjae-2** [open-telemetry/opentelemetry-operator#4072]
### Component(s)

target allocator

## Description
We have set up the TargetAllocator by creating a separate TargetAllocator CR and configured it to scrape targets. The OpenTelemetry Collector is configured with 2 replicas and uses the following Prometheus scrape config:

```yaml
            - job_name: cadvisor
              scrape_interval: 60s
              scrape_timeout: 30s
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - target_label: __metrics_path__
                  replacement: /metrics/cadvisor
                - source_labels: [ __address__ ]
                  regex: ([^:]+)(?::\d+)?
                  target_label: __address__
                  replacement: '$$1:10250'
            - job_name: node-exporter
              scrape_interval: 60s
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - action: labelmap
                  regex: __meta_kubernetes_node_label_(.+)
                - target_label: instance
                  replacement: kubernetes.default.svc:443
                - source_labels: [ __address__ ]
                  regex: ([^:]+)(?::\d+)?
                  target_label: __address__
                  replacement: '$$1:9100'
```

Target Allocator yaml:
```
apiVersion: opentelemetry.io/v1alpha1
kind: TargetAllocator
metadata:
  name: test-ta
  namespace: otel-test
spec:
  managementState: managed
  replicas: 1
  serviceAccount: test-ta-sa
  allocationStrategy: consistent-hashing
  resources:
    limits:
      memory: "2Gi"
      cpu: "2"
    requests:
      memory: "2Gi"
      cpu: "2"
  filterStrategy: relabel-config
```

Our cluster consists of 4 nodes. The `opentelemetry_allocator_targets` metric, collected from the TargetAllocator, consistently shows a value of 4.
However, the `opentelemetry_allocator_targets_per_collector` metric, which reflects the target distribution to the two collectors, normally shows values of `2, 2`. Intermittently, these values change to `2, 1`, indicating that one target node is being missed and not passed to one of the OpenTelemetry Collectors.
This results in missing cAdvisor metrics.

We have investigated potential issues related to `scrape_interval`, `scrape_timeout`, and resource constraints, but the problem persists. We are unsure what other issues to suspect.

## Steps to Reproduce
(It's difficult to provide exact steps to reproduce as the issue is intermittent. However, the setup involves:)
1. Deploy OpenTelemetry Operator.
2. Create a separate `TargetAllocator` CR.
3. Deploy an `OpenTelemetryCollector` CR with 2 replicas, configured with the cAdvisor scrape config mentioned above, and linked to the TargetAllocator.
4. Monitor `opentelemetry_allocator_targets` and `opentelemetry_allocator_targets_per_collector` metrics over time in a 4-node Kubernetes cluster.

## Expected Result
The sum of `opentelemetry_allocator_targets_per_collector` should consistently equal the value of `opentelemetry_allocator_targets`. Targets should be reliably distributed to the OpenTelemetry Collectors.

## Actual Result
Intermittently, the sum of `opentelemetry_allocator_targets_per_collector` becomes less than `opentelemetry_allocator_targets`. This indicates that some nodes are being omitted during target distribution to the OpenTelemetry Collectors, leading to them being excluded from scraping.

### Kubernetes Version

1.24.2

### Operator version

v0.126.0

### Collector version

otel/opentelemetry-collector-contrib:0.117.0

### Log output

```shell

```

### Additional context

We have another OpenTelemetry Collector deployed in the cluster as a standard Kubernetes Deployment (not managed by the OpenTelemetry Operator). This Deployment-managed Collector uses the exact same cAdvisor scrape configuration and is able to collect cAdvisor metrics reliably from all 4 nodes without any issues.

This observation leads us to believe that the issue is less likely to be related to the service discovery mechanism itself (e.g., `kubernetes_sd_configs` finding the nodes), and more likely to be an issue within the TargetAllocator, specifically in how it discovers, processes, or distributes these targets to the Operator-managed Collector replicas. The intermittent loss seems to occur during the handoff of targets from the TargetAllocator to the Collectors.

I have confirmed that targets are intermittently missing from the results, even when directly calling the Target Allocator's /jobs/cadvisor/targets endpoint.
