### ISSUE TITLE
Metric loss after scaling Collector during TargetAllocator rebalancing

### ISSUE THREAD

**Issue by bohub12** [open-telemetry/opentelemetry-operator#4085]
### Component(s)

target allocator, collector

## Description

I wanted to test whether metrics are preserved during TargetAllocator rebalancing, so I scaled the number of OpenTelemetryCollector replicas from 2 to 4. However, I noticed that some metrics from `node-exporter` were lost after this process. Please see the example screenshot below:
- `allocationStrategy`: `consistent-hashing`

![Image](https://github.com/user-attachments/assets/67d83bba-ab69-432e-ac14-53033c1dbb89)

After identifying a missing metric sample, I verified that `node-exporter` was indeed exposing the metric at the time. This suggests the issue was related to scraping rather than metric generation.

- missing metric sample
	- `{__name__="node_cpu_scaling_frequency_min_hertz", beta_kubernetes_io_arch="amd64", beta_kubernetes_io_os="linux", cluster="testcollector", cpu="1", instance="kubernetes.default.svc:443", job="node-exporter", kubernetes_io_arch="amd64", kubernetes_io_hostname="aaaaa", kubernetes_io_os="linux", node_role_kubernetes_io_worker="worker"}`
- When accessing the node-exporter endpoint for the `aaaaa` hostname, the `node_cpu_scaling_frequency_min_hertz` metric was confirmed to be exposed.

```console
$ curl 10.244.3.209:9100/metrics | grep node_cpu_scaling_frequency_min_hertz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP node_cpu_scaling_frequency_min_hertz Minimum scaled CPU thread frequency in hertz.
# TYPE node_cpu_scaling_frequency_min_hertz gauge
node_cpu_scaling_frequency_min_hertz{cpu="0"} 1e+09
node_cpu_scaling_frequency_min_hertz{cpu="1"} 1e+09
node_cpu_scaling_frequency_min_hertz{cpu="10"} 1e+09
node_cpu_scaling_frequency_min_hertz{cpu="11"} 1e+09
node_cpu_scaling_frequency_min_hertz{cpu="12"} 1e+09
node_cpu_scaling_frequency_min_hertz{cpu="13"} 1e+09
node_cpu_scaling_frequency_min_hertz{cpu="14"} 1e+09
node_cpu_scaling_frequency_min_hertz{cpu="15"} 1e+09
node_cpu_scaling_frequency_min_hertz{cpu="16"} 1e+09
node_cpu_scaling_frequency_min_hertz{cpu="17"} 1e+09
node_cpu_scaling_frequency_min_hertz{cpu="18"} 1e+09
node_cpu_scaling_frequency_min_hertz{cpu="19"} 1e+09
node_cpu_scaling_frequency_min_hertz{cpu="2"} 1e+09

```

Here is the `scrape_config` I used:

```yaml
            - job_name: cadvisor
              scrape_interval: 60s
              scrape_timeout: 60s
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - target_label: __metrics_path__
                  replacement: /metrics/cadvisor
                - source_labels: [__address__]
                  regex: ([^:]+)(?::\d+)?
                  target_label: __address__
                  replacement: "$$1:10250"
            - job_name: node-exporter
              scrape_interval: 60s
              scrape_timeout: 60s
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - action: labelmap
                  regex: __meta_kubernetes_node_label_(.+)
                - target_label: instance
                  replacement: kubernetes.default.svc:443
                - source_labels: [__address__]
                  regex: ([^:]+)(?::\d+)?
                  target_label: __address__
                  replacement: "$$1:31673"
```

I didn’t see any relevant logs from either the TargetAllocator or the OpenTelemetryCollector that pointed to the root cause. I’d appreciate it if you could help me understand what might have caused the metric loss, and how to prevent such losses after rebalancing.

Thanks!

## Steps to Reproduce

- Deploy the TargetAllocator CR with `replica: 2`.
- Deploy the OpenTelemetryCollector CR with `replica: 2`, using the `scrape_config` mentioned above.  
- Scale out the OpenTelemetryCollector custom resource to `replica: 4`.
	- `kubectl scale opentelemetrycollector <name> --replicas=4 -n <namespace>`
- Monitor the number of collected metrics.

## Expected Result

Metrics should not be lost after rebalancing.

## Actual Result

Metrics were lost after rebalancing.

### Kubernetes Version

1.24.2

### Operator version

v0.127.0

### Collector version

ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.127.0
