### ISSUE TITLE
Metric loss occurs after target re-allocation

### ISSUE THREAD

**Issue by bohub12** [open-telemetry/opentelemetry-operator#4090]
### Component(s)

target allocator

## Description

I wanted to test whether metrics are preserved during TargetAllocator rebalancing, so I scaled the number of OpenTelemetryCollector replicas from 2 to 4. However, I noticed that some metrics were lost after this process. Please see the example screenshot below:

![Image](https://github.com/user-attachments/assets/7d3badbe-84b1-4d5d-8d68-25d4e5f0ab10)

I've seen the code executed when the OpenTelemetry collector count changes, but I’m unable to determine why metrics are being lost. 
I modified the `collectorNotReadyGracePeriod` from 30s to 90s. And then scaled out the Otel Collector from 2 to 4 replicas, but the metrics were still lost just like before.

I also checked the logs of both the otel collector and the target allocator, but did not find anything unusual.

Could you help identify the root cause? I have included the configuration I used below as well.

Thanks!

```yaml
# Collector StatefulSet
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: test-collector-with-ta
  namespace: <namespace>
  labels:
    opentelemetry.io/target-allocator: test-ta-kbg # for connecting to target allocator
spec:
  mode: statefulset
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.127.0
  replicas: 2
  serviceAccount: test-collector-with-ta-sa
  observability:
    metrics:
      disablePrometheusAnnotations: true
  podDisruptionBudget:
    minAvailable: 1
  managementState: managed
  env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
  config:
    exporters:
      debug: {}
      otlphttp:
        endpoint: <endpoint>
      prometheusremotewrite:
        endpoint: <endpoint>
        external_labels:
          cluster: testcollector
        tls:
          insecure: true
          insecure_skip_verify: true
      prometheusremotewrite/2:
        endpoint: <endpoint>
        external_labels:
          cluster: testcollector
        tls:
          insecure: true
          insecure_skip_verify: true
      prometheusremotewrite/3:
        endpoint: <endpoint>
        external_labels:
          cluster: testcollector
        tls:
          insecure: true
          insecure_skip_verify: true
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 90
        spike_limit_percentage: 80
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: target-allocator
              scrape_interval: 1s
              static_configs:
                - targets:
                    - test-ta-kbg-targetallocator:80
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets:
                    - 0.0.0.0:8888
            - job_name: cadvisor
              scrape_interval: 60s
              scrape_timeout: 60s
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - target_label: __metrics_path__
                  replacement: /metrics/cadvisor
                - source_labels: [__address__]
                  regex: ([^:]+)(?::\d+)?
                  target_label: __address__
                  replacement: "$$1:10250"
            - job_name: node-exporter
              scrape_interval: 60s
              scrape_timeout: 60s
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
              kubernetes_sd_configs:
                - role: pod
                  selectors:
                    - role: pod
                      label: k8s-app=node-exporter
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_container_name]
                  regex: node-exporter
                  action: keep
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)
                - source_labels: [__address__]
                  regex: ([^:]+)(?::\d+)?
                  target_label: __address__
                  replacement: "$$1:9100"
    service:
      extensions:
        - health_check
      pipelines:
        logs:
          exporters:
            - debug
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
        metrics:
          exporters:
            - debug
            - prometheusremotewrite
            - prometheusremotewrite/2
            - prometheusremotewrite/3
          processors:
            - memory_limiter
            - batch
            - metricstransform
          receivers:
            - otlp
            - prometheus
        traces:
          exporters:
            - debug
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
      telemetry:
        metrics:
          address: 0.0.0.0:8888
        logs:
          level: DEBUG
---
# Target Allocator
apiVersion: opentelemetry.io/v1alpha1
kind: TargetAllocator
metadata:
  name: test-ta-kbg
  namespace: <namespace>
spec:
  managementState: managed
  replicas: 2
  serviceAccount: test-ta-sa
  allocationStrategy: consistent-hashing
  filterStrategy: relabel-config
  collectorNotReadyGracePeriod: 90s
  prometheusCR:
    enabled: false
  observability:
    metrics:
      disablePrometheusAnnotations: true

```

## Steps to Reproduce

- Deploy the TargetAllocator CR with `replica: 2`.
- Deploy the OpenTelemetryCollector CR with `replica: 2`, using the `yaml` mentioned above.
- Scale out the OpenTelemetryCollector custom resource to `replica: 4`.
    - `kubectl scale opentelemetrycollector <name> --replicas=4 -n <namespace>`
- Monitor the number of collected metrics.

## Expected Result

Metrics should not be lost after rebalancing.

## Actual Result

Metrics were lost after rebalancing.

### Kubernetes Version

1.24.2

### Operator version

v0.127.0

### Collector version

ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.127.0

### Log output

```shell

```
