### ISSUE TITLE
Generate RBAC rules when `config.extensions.k8s_observer` is used

### ISSUE THREAD

**Issue by ChristianCiach** [open-telemetry/opentelemetry-operator#4113]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

I am trying to enable annotation-based autodiscovery of the `receiver_creator` receiver:

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otelcol-daemonset
spec:
  mode: daemonset
  config:
    extensions:
      k8s_observer:
        observe_pods: true
    receivers:
      receiver_creator/logs:
        watch_observers: [k8s_observer]
        discovery:
          enabled: true
    processors: {}
    exporters:
      debug:
        verbosity: basic
    service:
      pipelines:
        logs:
          receivers: [receiver_creator/logs]
          exporters: [debug]
      extensions: [k8s_observer]
```

This fails due to RBAC permissions of the collector:

```
W0616 14:31:14.920655       1 reflector.go:569] k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:otelcol-system:otelcol-daemonset-collector" cannot list resource "pods" in API group "" at the cluster scope
E0616 14:31:14.920706       1 reflector.go:166] "Unhandled Error" err="k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:otelcol-system:otelcol-daemonset-collector\" cannot list resource \"pods\" in API group \"\" at the cluster scope" logger="UnhandledError"
```

The operator has permissions to deploy ClusterRoleBindings and so on (deployed via helm with `manager.createRbacPermissions=true`), but it doesn't seem to even attempt creating the necessary RBAC for the collector.

### Describe the solution you'd like

Looking at the source code, it looks like the operator is capable of dynamically creating the necessary RBAC rules for certain receivers and processors ([`k8sobjects`](https://github.com/open-telemetry/opentelemetry-operator/blob/5c8639856de1652e1ab78ab5f3d5030b05c021f7/internal/components/receivers/k8sobjects.go#L21), [`k8sattributes`](https://github.com/open-telemetry/opentelemetry-operator/blob/5c8639856de1652e1ab78ab5f3d5030b05c021f7/internal/components/processors/k8sattribute.go#L34)), but it doesn't seem to care about the `k8s_observer` extension.

The operator should probably treat the k8s_observer extension similarly to the k8sobjects receiver regarding the RBAC rules. Similar to the k8sobjects receiver, k8s_observer can be configured to listen to different kinds of objects (`observe_pods`, `observe_services` and so on), so the generated RBAC rules should take these flags into account.

### Additional context

Using Opentelemetry-Collector v0.127.0 deployed via helm with `manager.createRbacPermissions=true`

**Comment by ChristianCiach** [comment]
Workaround: Configure a dummy `k8sobjects` receiver to trick the operator into creating a necessary RBAC resources:

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
spec:
  config:
    receivers:
      # Not really used. Only declared to auto-generate RBAC:
      # https://github.com/open-telemetry/opentelemetry-operator/issues/4113
      k8sobjects:
        objects:
          - name: pods
            mode: watch
    exporters:
      nop: {}
    service:
      pipelines:
        logs/rbac_hack:
          receivers: [k8sobjects]
          exporters: [nop]
```

"If it's stupid but it works, it's not stupid"!
