### ISSUE TITLE
Add `extraLabels` to `spec.observability.metrics`

### ISSUE THREAD

**Issue by yuzhouliu9** [open-telemetry/opentelemetry-operator#4138]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

When an OpenTelemetryCollector is configured with the following
```yaml
spec:
  observability:
    metrics:
      enableMetrics: true
```

It will create a ServiceMonitor. However there is no configuration to add [extraLabels](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/values.yaml#L133) like in the case of the opentelemetry-operator.

Our prometheus instance is configured to only pick up ServiceMonitors and PodMonitors with a specific label. So the ServiceMonitors created from OpenTelemetryCollector are not being picked up as a target by prometheus right now.

Could this be added as a configuration parameter?

Thanks!

### Describe the solution you'd like

New field under metrics named `extraLabels` that is a map[string]string
```yaml
spec:
  observability:
    metrics:
      enableMetrics: true
      serviceMonitor:
        extraLabels:
          prometheus: kube-prometheus
```

### Describe alternatives you've considered

Create the ServiceMonitor object manually instead of relying on OpenTelemetryCollector
