### ISSUE TITLE
Add a mechanism to ignore certain receivers when deriving service from config

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-operator#527]
The specific receiver configuration that sparked this issue:

```
receivers:
      kubeletstats/node:
        auth_type: serviceAccount
        collection_interval: 1m
        endpoint: ${K8S_NODE_NAME}:10250
        insecure_skip_verify: true
        k8s_api_config:
          auth_type: serviceAccount
        metric_groups:
        - node
      kubeletstats/pods:
        auth_type: serviceAccount
        collection_interval: 1m
        endpoint: ${K8S_NODE_NAME}:10250
        insecure_skip_verify: true
        k8s_api_config:
          auth_type: serviceAccount
        metric_groups:
        - pod
```

This fails, because the service derives that there are two endpoints, each with port 10250, giving this error:
```
{"level":"error","ts":1636559029.2833467,"logger":"controllers.OpenTelemetryCollector","msg":"failed to reconcile services","error":"failed to reconcile the expected services: failed to apply changes: Service \"opentelemetry-node-agent-collector\" is invalid: spec.ports[1]: Duplicate value: core.ServicePort{Name:\"\", Protocol:\"TCP\", AppProtocol:(*string)(nil), Port:10250, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:\"\"}, NodePort:0}","stacktrace":"github.com/open-telemetry/opentelemetry-operator/controllers.(*OpenTelemetryCollectorReconciler).Reconcile\n\t/workspace/controllers/opentelemetrycollector_controller.go:147\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:214"}
```

The problem here is that `endpoint` doesn't define an endpoint for something connecting to the collector, rather it's an endpoint that is scraped by the collector. These ports shouldn't be mapped in the service, since they are not for inbound connections.

Currently the workaround for this is to not use `endpoint` for this specific scenario and have the receiver figure it out, but I could see this being a problem with other "scraping" receivers as well.

Ideally, there'd be a way to skip gathering ports from certain receivers, or even a way to disable the port auto-detection as a whole.
