### ISSUE TITLE
The pod name is empty in pod webhook

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#554]
The pod name is empty/not set in the pod webhook when the pod is created from higher-level object - deployment, statefulset. This also applies for pod UID. The only time pod name is present is when the pod is created from the pod object. 

We should figure out how to get the pod name and set it in the resource attributes. One way to get the pod name is via k8s downward API, but we cannot use it out-of-the-box as there is no way to set it to resource variable - see https://github.com/open-telemetry/opentelemetry-specification/issues/2135

@jpkrohling any thoughts?

**Comment by jpkrohling** [comment]
We have something similar for the Jaeger operator, where we set it to an env var, and use that env var as part of JAEGER_TAGS. Wouldn't that solve the problem here?

**Comment by pavolloffay** [comment]
That should work

**Comment by pavolloffay** [comment]
the `JAEGER_TAGS` env var is not used in the Jaeger operator. The operator is using `---jaeger-tags` flag https://github.com/pavolloffay/jaeger-operator/blob/df4351001697e68e7fd99a3b886d34e86f4efef9/pkg/inject/sidecar.go#L203 as CMD argument. The CMD interprets all env variables.

In this operator, we set the resource attributes via env VAR `OTEL_RESOURCE_ATTRIBUTES`. IIRC the env var substitution does not work for env vars in Kubernetes e.g.

```yaml
env:
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: k8s.namespace.name=default,k8s.pod.name:${POD_NAME}
  - name: POD_NAME
     valueFrom:
       fieldRef:
          fieldPath: metadata.name
```
