### ISSUE TITLE
Error when apply documented yaml

### ISSUE THREAD

**Issue by AWinterman** [open-telemetry/opentelemetry-operator#593]
I installed the operator with the following:

```bash
# install and verify the cert manager - a dependency of the operator  
# from https://cert-manager.io/docs/installation/kubectl/
# curl -L https://github.com/jetstack/cert-manager/releases/download/v1.6.0/cert-manager.yaml > cert-manager.yaml
kubectl apply -f cert-manager.yaml


# install and verify the open telemetry operator exists 
# from https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.38.0/opentelemetry-operator.yaml
# https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.38.0/opentelemetry-operator.yaml > opentelemetry-operator.yaml
kubectl apply -f opentelemetry-operator.yaml
```

Then I defined a custom collector.yaml based on the docs

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-sidecar
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:

    exporters:
      logging:
    extensions:
      health_check:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [otlp]

---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest

```

but when i apply it with `kubectl apply -f collector.yaml` I get
```
error: error validating "collector.yaml": error validating data: [ValidationError(Instrumentation.spec): unknown field "nodejs" in io.opentelemetry.v1alpha1.Instrumentation.spec, ValidationError(Instrumentation.spec): unknown field "propagators" in io.opentelemetry.v1alpha1.Instrumentation.spec, ValidationError(Instrumentation.spec): unknown field "python" in io.opentelemetry.v1alpha1.Instrumentation.spec, ValidationError(Instrumentation.spec): unknown field "sampler" in io.opentelemetry.v1alpha1.Instrumentation.spec]; if you choose to ignore these errors, turn validation off with --validate=false
```

Indeed, looking at the specification for the Instrumentation kind, I see the following starting on line 49

```
         spec:
            description: InstrumentationSpec defines the desired state of OpenTelemetry
              SDK and instrumentation.
            properties:
              exporter:
                description: Exporter defines exporter configuration.
                properties:
                  endpoint:
                    description: Endpoint is address of the collector with OTLP endpoint.
                    type: string
                type: object
              java:
                description: Java defines configuration for java auto-instrumentation.
                properties:
                  image:
                    description: Image is a container image with javaagent JAR.
                    type: string
                type: object
            type: object
```
