### ISSUE TITLE
Auto instrumentation injects into wrong container

### ISSUE THREAD

**Issue by BronzeDeer** [open-telemetry/opentelemetry-operator#618]
Currently, Autoinstrumentation seems to inject into the first container in the list, which is especially troublesome if used with istio, which injects its proxy ahead of the normal container.

[While injection into the first container](https://github.com/open-telemetry/opentelemetry-operator/blob/ae8f3a852623f465a6c1802d03ffa31651bf0888/pkg/instrumentation/javaagent.go#L31) is surely a good default, an optional annotation could be added which contains the name(s) of containers to inject into

**Comment by jpkrohling** [comment]
cc @pavolloffay, @anuraaga

**Comment by pavolloffay** [comment]
hi @BronzeDeer, thanks for reaching out. 

Generally speaking, where to inject can be controlled in a CR or via an annotation. The value of this config could be container index/position or container name. 

#### CR

The CR could look like this:

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  injectIntoContainers: 
    - app
    - myapp
  injectIntoConainerIndices: 
    - 0
    - 2
```

The injection would be done if any of the criteria matched. It could be as well used to inject into init-containers. 

#### Annotation 

At the moment the instrumentation CR supports the following annotation:

```golang
instrumentation.opentelemetry.io/inject-{java,python,nodejs}={"true", "false", "instr-name"}
```

e.g.:
```
instrumentation.opentelemetry.io/inject-into-conainers="app,myapp"
instrumentation.opentelemetry.io/inject-into-containerIndices="0,2"
```

The annotation could be applied on the pod spec or namespace.


I find supporting injection to multiple containers useful, also we could extend the functionality to inject into the init containers as well. Related comment https://github.com/open-telemetry/opentelemetry-operator/issues/529#issuecomment-966279517


@BronzeDeer I would like to know your preference - CR or annotation
