### ISSUE TITLE
Upgrading operator on k8s < 1.22 is broken

### ISSUE THREAD

**Issue by Apollorion** [open-telemetry/opentelemetry-operator#644]
[This change](https://github.com/open-telemetry/opentelemetry-operator/pull/521) broke upgrading existing operators in k8s < 1.22.

We attempted to upgrade our operator today, via:
```
kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml
```

And we're getting this error:
```
CustomResourceDefinition/opentelemetrycollectors.opentelemetry.io dry-run failed, reason: Invalid, error: CustomResourceDefinition.apiextensions.k8s.io "opentelemetrycollectors.opentelemetry.io" is invalid: [spec.conversion.strategy: Required value, spec.conversion.webhookClientConfig: Forbidden: should not be set when strategy is not set to Webhook]
```

We were able to get around it by adding the default strategy back into `opentelemetry-operator.yaml` spec.
```
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle: Cg==
        service:
          name: webhook-service
          namespace: opentelemetry-operator-system
          path: /convert
          port: 443
      conversionReviewVersions:
        - v1
        - v1beta1
 ```
