### ISSUE TITLE
Parsing httpd endpoint in Otel-operator is broken.

### ISSUE THREAD

**Issue by yuriolisa** [open-telemetry/opentelemetry-operator#646]
I'm trying to use the httpd receiver with a declared endpoint, like : 

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: localhost:9090
      httpd:
        endpoint: http://localhost:8080/server-status?auto
        collection_interval: 10s
    processors:
      nop:
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
        metrics:
          receivers: [httpd]
          processors: [nop]
          exporters: [logging]
```

However, I'm getting the following error once the CR is deployed: 
```
opentelemetry-operator-controller-manager-68cf456bd-6lmbs manager {"level":"info","ts":1640033774.9538267,"logger":"controllers.OpenTelemetryCollector","msg":"couldn't parse the endpoint's port","opentelemetrycollector":"opentelemetry-operator-system/simplest","endpoint":"http://localhost:80/server-status?auto"}
opentelemetry-operator-controller-manager-68cf456bd-6lmbs manager {"level":"info","ts":1640033774.9549108,"logger":"controllers.OpenTelemetryCollector","msg":"couldn't parse the endpoint's port","opentelemetrycollector":"opentelemetry-operator-system/simplest","endpoint":"http://localhost:80/server-status?auto"}
```
