### ISSUE TITLE
Add more configuration for auto-instrumentations

### ISSUE THREAD

**Issue by Duncan-tree-zhou** [open-telemetry/opentelemetry-operator#657]
is't able to set instrument configs, like chose exporter, enable/disable instruments, instrument log level etc. ?

**Comment by VineethReddy02** [comment]
@Duncan-tree-zhou can you describe the issue with more details and if possible with an example usecase?

**Comment by Duncan-tree-zhou** [comment]
> @Duncan-tree-zhou can you describe the issue with more details and if possible with an example usecase?

following the guide in README.md to instrument java app deployment. some "OTEL_" prefix env was automatically injected to the java app container. but I want to add more "OTEL_" prefix env for the java app container like "OTEL_TRACES_EXPORTER=jaeger". in other word, is't possible to config java/python/nodejs instruments in Instrumentation CRD?

for java autoinstrument configs, reffer to [java agent config](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md)

for python autoinstrument configs, reffer to [python agent config](https://opentelemetry-python.readthedocs.io/en/latest/sdk/environment_variables.html#envvar-OTEL_EXPORTER_JAEGER_USER)

**Comment by pavolloffay** [comment]
This is not supported at the moment. The current CR supports only a minimal set of conf options. 

@Duncan-tree-zhou exactly which configuration options would you like to configure?

**Comment by pavolloffay** [comment]
thanks for more input @Duncan-tree-zhou. 

The OTEL spec defined config should go into the main nodes in the CR (exporter, propagation..) https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#jaeger-exporter
The language-specific configuration should go under language node in the CR.


Here is how the CR could look like:

```yaml
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector:4317
    exporter: otlp # defaults to otlp, possible values are: jaeger, zipkin, otlp, none, https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#exporter-selection
  python:
    env:
     - name: 
       value: 
EOF
```

**Comment by Duncan-tree-zhou** [comment]
@pavolloffay Agreed. But should we allow Instrumentation CR to inject any env by language spec envs? If so, I would like to meke summit a mr for it. 

Besides, I look into the code [here](https://github.com/open-telemetry/opentelemetry-operator/blob/55a0dc2e86a930ff72aac54391f369520c0d8064/pkg/instrumentation/python.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L28). the value of `OTEL_TRACES_EXPORTER` was hardcode with 'otlp_proto_http', it looks like that the python insturments is not following the specification.

**Comment by pavolloffay** [comment]
> @pavolloffay Agreed. But should we allow Instrumentation CR to inject any env by language spec envs? If so, I would like to summit a mr for it.

I can think of two ways how we could design CR: 
1. define a property for each configuration option 
2. allow users to define any env var

The 1. requires a lot of CR maintenance to keep up with the SDK and instrumentation changes. However, it might provide a better UX.  I would go with option 2 anyways because of the maintainability. 

> Besides, I look into the code here. the value of OTEL_TRACES_EXPORTER was a hardcoded string 'otlp_proto_http', it looks like that the python insturments is not following the specification.

The python SDK probably supports only HTTP. cc) @anuraaga

**Comment by Duncan-tree-zhou** [comment]
Following your idea, I think we could define two kind of envs in CR:

1. common env
2. language specific env 

the CR may look like:

```
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  common:
    - name: OTEL_TRACES_EXPORTER
      value: "jaeger"
    - name: OTEL_EXPORTER_JAEGER_ENDPOINT
      value: "http://jaeger-collector:14250" 
    - name: OTEL_EXPORTER_JAEGER_TIMEOUT
      value: "20"
    - name: OTEL_PROPAGATORS
      value: "tracecontext,baggage,b3"
    - name: OTEL_TRACES_SAMPLER
      value: "parentbased_traceidratio"
    - name: OTEL_TRACES_SAMPLER_ARG
      value: "0.25"
  java:
    - name: OTEL_JAVAAGENT_DEBUG
       value: "true"
    - name: OTEL_INSTRUMENTATION_JDBC_ENABLED
       value: "false"
  python:
    - name: OTEL_LOG_LEVEL
      value: "debug"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp_proto_http"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://otel-collector:4317"
    - name: OTEL_EXPORTER_OTLP_TIMEOUT
      value: "30"
  nodejs:
    - name:  OTEL_XXX
      value: "xxx"
EOF
```

common envs would be injected into every containers with any instrument annotation, and language spec envs would be injected into containers with language spec instrument annotation. 
when the same env was defined in both common and language spec, then the language spec env should ovewrite the common env.
Only envs that begin with "OTEL_" would be inejcted, to avoid pollution of pod envs.

**Comment by pavolloffay** [comment]
Slight change 

```yaml
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  env:
    - name: OTEL_
      value: ""
  python:
    env:
    - name: OTEL_
      value: ""
EOF
```

For exporter type it is worth defining a dedicated field under the `exporter` node. 

> when the same env was defined in both common and language spec, then the language spec env should ovewrite the common env.

+1

> Only envs that begin with "OTEL_" would be inejcted, to avoid effects on non-otel process.

+1 can be done in the validating webhook
