### ISSUE TITLE
The OpenTelemetryCollector "opentelemetry-dev" is invalid: type: Required value

### ISSUE THREAD

**Issue by domyway** [open-telemetry/opentelemetry-operator#675]
here is my test.yaml, kubectl apply -f test.yaml .  output :
The OpenTelemetryCollector "opentelemetry-dev" is invalid: type: Required value

anything wrong?

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: opentelemetry-operator-system
data:
  collector.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:

    exporters:
      jaeger_thrift:
        endpoint: "http://xxxxxx:14268/api/traces"
      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger_thrift, logging]
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-dev
  namespace: opentelemetry-operator-system
spec:
  mode: daemonset
  upgradeStrategy: none
  image: otel/opentelemetry-collector-contrib:latest
  volumeMounts:
  - mountPath: /conf/collector.yaml
    name: data
    subPath: collector.yaml
    readOnly: true
  volumes:
    - name: data
      configMap:
        name: otel-collector-config
        items:
        - key: collector.yaml
          path: collector.yaml
```

**Comment by Duncan-tree-zhou** [comment]
Hi @domyway ,

try like this:

``` yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-dev
  namespace: opentelemetry-operator-system
spec:
  mode: daemonset
  config: |-
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:

    exporters:
      jaeger_thrift:
        endpoint: "http://xxxxxx:14268/api/traces"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger_thrift, logging]
```


OpenTelemetryCollector is a CR, and `spec.config` is an attribute of this CR. I think we can not mount a folder to a CR.

It looks like the opentelemetry-operator is on developing, the attributes in CR may be changed in different version. So you can reffer [opentelemetrycollector_types.go](https://github.com/open-telemetry/opentelemetry-operator/blob/main/apis/v1alpha1/opentelemetrycollector_types.go)  and find the CR verison you used, to get the exact attributes that you can config.
