### ISSUE TITLE
Injected Instrumentation object unable to connect to OT Collector daemonset service

### ISSUE THREAD

**Issue by rcooper85** [open-telemetry/opentelemetry-operator#694]
Hi, i’m using the opentelemetry-operator with kubernetes and i’ve deployed the collector as a daemonset. I have also deployed an Instrumentation custom resource. I have then annotated my java application with `instrumentation.opentelemetry.io/inject-java: “true”`.
When I deploy the application, I am seeing the following error: `ERROR: io.opentelemetry.exporter.otlp.internal.grpc.DefaultGrpcExporter - Failed to export spans. Server is UNAVAILABLE. Make sure your collector is running and reachable from this network`.
I have configured the Instrumentation object’s Exporter endpoint like this:
```
Spec:
  Exporter:
    Endpoint: http://otcollector-collector.default.svc.cluster.local:4317
```
I’ve also tried setting the endpoint to just ```http://otcollector-collector:4317```  but I got the same error. Just wondering if there is an issue with the daemonset? My daemonset config is:
```
config: |
  receivers:
    otlp:
      protocols: 
        grpc:
        http:
  processors: 
  exporters:
    logging:
    otlp/elastic:
      endpoint: "my-elastic-endpoint"
      headers: 
        Authorization: "APM token"
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: []
        exporters: [otlp/elastic, logging]
```
Oh, the logs for the collector pods that are running as part of the daemonset deployment show “Everything is ready. Begin running and processing data”. 
I have also tried kubectl exec'ing onto the application pod and I can't even curl the endpoints for the daemonset service using the IP addresses.

**Comment by yuriolisa** [comment]
@jpkrohling , could you please assign this issue to me?

**Comment by pavolloffay** [comment]
> Hi, i’m using the opentelemetry-operator with kubernetes and i’ve deployed the collector as a daemonset. 

In this case you exporter endpoint should be configured to report data to localhost.

**Comment by rcooper85** [comment]
> > Hi, i’m using the opentelemetry-operator with kubernetes and i’ve deployed the collector as a daemonset. 
> 
> 
> 
> In this case you exporter endpoint should be configured to report data to localhost.

The exporter endpoint configuration is for the Instrumentation CR which gets injected into the Java app. Setting that to localhost would only work if I was running the collector as a sidecar, no? I want to set the endpoint to be the Collector Service which is created by the Daemonset deployment so that it is loadbalanced between the collector pods on each node.

**Comment by pavolloffay** [comment]
In the first sense you mention that the collector is deployed as daemonset, in this case the app can report data to the localhost if I am not mistaken.

**Comment by pavolloffay** [comment]
I would be helpful if you posted full otelcol and instrumentation CRs and as well `kubectl get all` from the namespace where the collector is deployed.

**Comment by rcooper85** [comment]
I managed to fix this issue last night. I noticed that in the daemonset yaml file (I followed the pattern from [here](https://github.com/open-telemetry/opentelemetry-operator/blob/main/tests/e2e/daemonset-features/00-install.yaml)) I noticed hostNetwork was set. So I added the following to my java application's deployment.yaml:
```yaml
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
```
I could then see the collector logs receiving spans.
