### ISSUE TITLE
istio protocol selection

### ISSUE THREAD

**Issue by binjip978** [open-telemetry/opentelemetry-operator#696]
Hi, we are using opentelemetry collector with Istio and facing issue with protocol selection on istio side. According to istio [documentation](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/) protocol selection can be configured in two ways:

- By the name of the port, in format: "name: \<protocol\>\[-\<suffix\>\]"
- By specifying appProtocol, work with Kubernetes 1.18+

Unfortunately for us collector specify protocol name in a service as "otlp-grpc", and istio can't deduce and pick grpc, it would work if name was "grpc-oltp".

So, there are two solution for this problem:
- rename oltp-grpc to grpc-oltp, but it's probably to big to change right now, but i'm not totally sure about that.
- add appProtocol field to OLTP/Jaeger receiver parsers `Ports` function, right now is currently not used and specify protocol name there, and it should look like this: 
```yaml
    ports:
    - appProtocol: grpc
      name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
```

Any feedback are welcome, and i can provide a patch if any approach is suitable for the project.
