### ISSUE TITLE
otelinst did not support other exporters config in nodejs app.

### ISSUE THREAD

**Issue by Duncan-tree-zhou** [open-telemetry/opentelemetry-operator#710]
I try to config nodejs and config to chose jaeger exporter, but it's not work.

``` yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instru
spec:
  env:
  propagators:
  - tracecontext
  - baggage
  - b3
  java:
  nodejs:
    env:
    - name: "OTEL_LOG_LEVEL"
      value: "DEBUG"
    - name: "OTEL_TRACES_EXPORTER"
      value: "jaeger" 
    - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
      value: "http://jaeger-collector:14250" 
    - name: "OTEL_TRACES_SAMPLER_ARG"
      value: "1"
```

And it looks like that the trace exporter is hardcoded to otel exporter. 

ref here: https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/nodejs/src/autoinstrumentation.ts

Are there any problem if we implement the exporter configs for nodejs app?
