### ISSUE TITLE
is there a way to add annotation to service of the collector

### ISSUE THREAD

**Issue by domyway** [open-telemetry/opentelemetry-operator#715]
I want add some custom annotation to the svc that operator auto create. But it seems only support podAnnotation.

**Comment by pavolloffay** [comment]
The annotations specified in the CR should be propagated to service annotations. 

e.g. 

```
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
  annotations:
    foo: bar
spec:
EOF
```
