### ISSUE TITLE
Syslog receiver doesn't properly set UDP/TCP protocol for k8s service

### ISSUE THREAD

**Issue by geoffreytran** [open-telemetry/opentelemetry-operator#767]
Unable to use the syslog receiver endpoints for UDP because the k8s server port protocol is always TCP. It doesn't appear to detect the proper protocol type for the syslog receiver.

```
      syslog:
        tcp:
          listen_address: 0.0.0.0:1468
        udp:
          listen_address: 0.0.0.0:5514
        protocol: rfc5424
        location: UTC
```

The configuration above results in just the k8s service definition for the port 5514 as TCP. It should result in both the TCP 1428 and UDP 5514.

```
      syslog:
        udp:
          listen_address: 0.0.0.0:5514
        protocol: rfc5424
        location: UTC
```

This configuration results in the k8s service definition of TCP 5514 rather than the expected results of UDP 5514.
