### ISSUE TITLE
Add support for "distributions"

### ISSUE THREAD

**Issue by ocervell** [open-telemetry/opentelemetry-operator#77]
Currently, we cannot deploy `opentelemetry-collector-contrib` using this operator because although the `image` field can be configured to `opentelemetry-collector-contrib:<VERSION>`, the container command name is different than `opentelemetry-collector`.

Here is a sample deployment that we should be able to support with the operator:

```
      containers:
      - image: otel/opentelemetry-collector-contrib:0.7.0
        command:
          - "/otelcontribcol"
          - "--config=/conf/otel-agent-config.yaml"
          - "--mem-ballast-size-mib=165"
```

We could add a field in the CRD to support a configurable `command` field.

**Comment by naivcit** [comment]
Can I take this up ?

**Comment by jpkrohling** [comment]
I thought about this a bit more, and I think it would be better to create a new type, `OpenTelemetryCollectorDistribution`, like this:

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollectorDistribution
metadata:
  name: otelcoldist-sample
spec:
  image: quay.io/jpkroehling/some-otelcoldist
  version: 0.11.0 # if specified, pins to this version, otherwise, follows the same procedure as the core distribution
  binary: "/otelcoldist" # the location of the binary in the image
```

We can then resolve which distribution to use based on:

1. explicit mention in the `OpenTelemetryCollector` CR (new fields)
1. namespace annotation
1. existence of a single CR in the namespace

When none of them exists, we fallback to the core distribution.

How does that sound? 

cc @objectiser

**Comment by objectiser** [comment]
@jpkrohling like the idea of the new type - it could avoid the complexity in the OTCollector CR.

Not sure whether namespace annotation is appropriate though.

**Comment by jpkrohling** [comment]
What do you think, @naivcit? Do you want to try it out?

**Comment by ziksha-tech** [comment]
Hey @jpkrohling although  I might need some time to wrap my head around it , since I am new here , but would definitely love to take a stab at it

**Comment by naivcit** [comment]
Hey @jpkrohling Sure, though I might need some time to wrap my head around it since I am new here , but would definitely love to take a dig at this

**Comment by jpkrohling** [comment]
I'd recommend to start by reading the Operator SDK tutorial: https://sdk.operatorframework.io/docs/building-operators/golang/ . The new CRD can be created with the instructions from "Create an API".

**Comment by jpkrohling** [comment]
@naivcit are you still interested in this one?

**Comment by naivcit** [comment]
Hey @jpkrohling ya , sorry there's been some health issues on my side , will work on this this weekend

**Comment by jpkrohling** [comment]
@ocervell, I'm working on this right now, and I noticed that we don't actually specify the command for the container: we rely on whatever the `ENTRYPOINT` for the container is, which does seem correct for the contrib distribution: 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e1a9ff10219bdf53cd51eb35fa1ba6268114037d/cmd/otelcontribcol/Dockerfile#L8

Could you please share the CR you are using so that I can try to reproduce your issue?

**Comment by ovidiubuligan** [comment]
@jpkrohling  do you know if there will be a `otel-collector-contrib` docker image alongside the binaries ? Since the binaries are already ``. (I need the azure exporter)

**Comment by ovidiubuligan** [comment]
It looks looks there is an image ; https://hub.docker.com/r/otel/opentelemetry-collector-contrib

**Comment by ocervell** [comment]
@jpkrohling Sure, but if we want to specify custom parameters, we have to input `command` as well, right ? Or are you saying that if we leave `command` empty, the command name will automatically be inferred from the ENTRYPOINT, hence `otelcontribcol` ?

**Comment by jpkrohling** [comment]
You'll have to specify the args, not the command. What kind of parameters are you interested in overriding? I think I might need to add this to the #129, but I wanted to understand your use case first.

**Comment by cemo** [comment]
What is the proper way to use "otel/opentelemetry-collector-contrib" currently? Is there a way with opentelemetry-operator?

**Comment by jpkrohling** [comment]
Yes, you should be able to use it by just overriding the image in the CR.

**Comment by kaskavalci** [comment]
@jpkrohling can you provide an example of how to set the image? I couldn't find a resource that documents this.

**Comment by jpkrohling** [comment]
It's the `image` property as part of the spec: https://github.com/open-telemetry/opentelemetry-operator/blob/b6ac997b1ba13d756f8679870d49ee497b699c6f/api/v1alpha1/opentelemetrycollector_types.go#L39-L42

Example:

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetrycollector-sample
spec:
  image: registry/my-custom-image:v1.2.3
```

**Comment by kaskavalci** [comment]
For future reference, a copy paste solution :) 

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: sidecar-for-my-app
spec:
  mode: sidecar
  image: otel/opentelemetry-collector-contrib:0.24.0
  config: |
    receivers:
      jaeger:
        protocols:
          grpc:
    processors:

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: []
          exporters: [logging]
```
