### ISSUE TITLE
After upgrading operator v0.48.0, operator doesn't respect the collectorImage configuration

### ISSUE THREAD

**Issue by logamanig** [open-telemetry/opentelemetry-operator#808]
Following values.yaml is used to install the OpenTelemetery Operator helm chart (chart version is upgraded from 0.6.5 to 0.6.6). until operator v0.47.0, manager.collectorImage.repository value is used as default image for the OpenTelmeteryCollector CRD instances. after the upgrade to v0.48.0, it's not respecting this configuration in operator and uses the otel collector core docker image.

Have to downgrade the operator image version to 0.47.0 to make it working

```
manager:
  image:
    repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
    tag: v0.48.0
  collectorImage:
    repository: otel/opentelemetry-collector-contrib
    tag: 0.48.0
```
