### ISSUE TITLE
Changing `env` in `OpenTelemetryCollector` does not cause the DaemonSet to update

### ISSUE THREAD

**Issue by tillig** [open-telemetry/opentelemetry-operator#825]
Given an `OpenTelemetryCollector` like this:

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
  namespace: opentelemetry
spec:
  config: |
    [Valid config omitted]
  env:
  - name: FIRST_ENV_VAR
    value: some-value
  image: otel/opentelemetry-collector-contrib:0.48.0
  imagePullPolicy: IfNotPresent
  mode: daemonset
  upgradeStrategy: automatic
```

If you add an environment variable and use `kubectl apply` or Helm (if this is in a chart)...

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
  namespace: opentelemetry
spec:
  config: |
    [Valid config omitted]
  env:
  - name: FIRST_ENV_VAR
    value: some-value
  - name: SECOND_ENV_VAR
    value: other-value
  image: otel/opentelemetry-collector-contrib:0.48.0
  imagePullPolicy: IfNotPresent
  mode: daemonset
  upgradeStrategy: automatic
```

...this does NOT cause the DaemonSet to be redeployed with the updated environment variables. If the configuration makes use of these environment variables, this will then cause the collector pods to fail on restart.

The only way to work around this is to fully remove the `OpenTelemetryCollector` instance and then deploy it fresh.
