### ISSUE TITLE
Support resources (Requests and Limits) for auto-instrumentation initContainers

### ISSUE THREAD

**Issue by ringerc** [open-telemetry/opentelemetry-operator#895]
An auto-instrumented Pod may fail to deploy or force a scale-up because no resource `requests` or `limits` are set on the injected `initContainer`, so the namespace defaults are used. These are generally grossly excessive for a trivial `initContainer`, and will force the pod to reserve more than it needs.

The `initContainer` injected by the `Instrumentation` resource by request of the `instrumentation.opentelemetry.io/inject-nodejs: true` pod annotation should default to some very low resource limits for CPU and memory. The `Instrumentation` CRD probably needs to make them configurable, since no doubt someone will find a problem with any sensible low default, somehow, somewhere.

If you get deployment delays like

```
  Warning  FailedScheduling  38s   default-scheduler   0/25 nodes are available: 22 Insufficient cpu, 3 node(s) had taint {CriticalAddonsOnly: true}, that the pod didn't tolerate.
```

or related errors, this is probably why.

I don't see a practical way to patch this in my deployments because the container spec is generated by the operator on the fly.

**Comment by ringerc** [comment]
A workaround can be to deploy a very low `LimitRange` to your namespace, then make sure everything else specifies limits and requests explicitly.

E.g.

```
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: my-namespace-here
spec:
  limits:
  - default:
      cpu: 500m
      memory: 250Mi
    defaultRequest:
      cpu: 0.1
      memory: 100Mi
    type: Container
```
