### ISSUE TITLE
Expose collector outside of cluster

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#902]
Use case: a user wants to send telemetry data to the OTEL collector from outside of the cluster - e.g. mobile clients or just a different cluster.

**Comment by ringerc** [comment]
Wouldn't this typically be done on k8s via deployment of a `LoadBalancer` endpoint?

**Comment by sergeyshevch** [comment]
Another option is adding k8s Ingress support. Some ingress controllers have a good support for gRPC as well

**Comment by frzifus** [comment]
Hey what would be a suitable solution for this? I have summarized my thoughts [here](https://github.com/open-telemetry/opentelemetry-operator/issues/1002#issue-1316552044). Would be very happy about your feedback.

**Comment by frzifus** [comment]
After playing around i have now ended up with this CR extension. What are your thoughts? This would eliminate a few manual steps on the receiver side. In https://github.com/open-telemetry/opentelemetry.io/pull/1684 I wrote all the manual steps down.

```golang
// Ingress is used to specify how OpenTelemetry Collector is exposed. This
// functionality is only available if one of the valid modes is set.
// Valid modes are: deployment, daemonset and statefulset.
type Ingress struct {
	// Type default value is: none
	// Supported types are: route/loadbalancer/nodeport/ingress
	Type string

	// IngressClassName is the name of the IngressClass cluster resource.
	ClassName string

	// Hostname by which the ingress proxy can be reached.
	Hostname string

	// Protocol used in exposed backend.
	Protocol string

	// Annotations to add to ingress separated by comma,
	// e.g. 'cert-manager.io/cluster-issuer: "letsencrypt"'
	// +optional
	Annotations string

	// TLS configuration.
	// +optional
	TLS []networkingv1.IngressTLS
}
```

**Comment by yuriolisa** [comment]
@frzifus, +1 for your idea.
would we have an implementation for Routes in Openshift scenario?

**Comment by sergeyshevch** [comment]
@frzifus Looks like Kubernetes already has all types for ingress. Can we just reuse it in your implementation?

**Comment by PengWang-SMARTM** [comment]
Can someone summarize the current status regarding what's supported and what's not? I'm really confused. I'd appreciate if there is a sharable successfully story with details to follow.

I happened to work on this subject in the past week, and came here after reading [the blog](https://opentelemetry.io/blog/2022/k8s-otel-expose/), which is posted about ten days ago.

According to the blog, it sounds like Ben(@frzifus) successfully made an otlp grpc connection over an nginx ingress between two otel collectors. However, the example instructions are questionable to me. For example, in the edge side client otel configuration, the endpoint should have a port number. 
```
    exporters:
      otlp:
        endpoint: "<REPLACE: your domain endpoint, e.g.: "traces.example.com">"
```

Anyway, I'd admit I'm still struggling to create an otlp connection over a traefik ingress, no matter grpc or https. I've successfully made an https connection over the traefik ingress to browse an https server. I thought the otlphttp would be something similar, but I was wrong. I got some success, but still have questions and problems.

### otlphttp
Client OTEL
```
exporters:
  otlphttp:
    endpoint: https://example.com
    auth:
      authenticator: basicauth/client
    tls:
      cert_file: /conf/certs/tls.crt
      key_file: /conf/certs/tls.key
      ca_file: /conf/certs/ca.crt
```
Server OTEL
```
receivers:
  otlp:
    protocols:
      http:
        auth:
          authenticator: basicauth/server
        tls:
          cert_file: /conf/certs/tls.crt
          key_file: /conf/certs/tls.key
          client_ca_file: /conf/certs/ca.crt
```
Service
```
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: "https"
    traefik.ingress.kubernetes.io/service.passhostheader: "false"
```
Ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - "example.com"
      secretName: "example-ingress"
  rules:
    - host: "example.com"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: example-otel
                port:
                  number: 4318
```

I started with the configuration above. The client otel got 502 errors, and the server otel said the client did not provide a certificate.

Then I disabled the service side client certificate verification by removing `client_ca_file: /conf/certs/ca.crt`. Without the certification verification, the otlphttp appears working now.

As you may see, the ingress routing path has to be "/". If I change it to something like (Client exporter endpoint to be `https://example.com/otlphttp` and Ingress path to be `/otlphttp`), the connection will fail, and the Client gets `Permanent error: error exporting items, request to https://example.com/otlphttp/v1/metrics responded with HTTP Status Code 404` with nothing in the Server log.

`traefik.ingress.kubernetes.io/service.passhostheader: "false"`, this seems important. If it is `"true"`, somewhere would fail after about 3 or 4 minutes. Since I'm new here, I can only record my observation rather than figuring out what exactly happened. I thought if it works, it should work always. Working for couple minutes is something odd to me.

Anyway, I'm still having two issues with this otlphttp over ingress:
1. how to enable the Server side client certificate verification
2. how to add a basepath rather than "/"

### otlpgrpc config
I'm having much more troubles with otlpgrpc.

Client OTEL
```
exporters:
      otlp:
        endpoint: example.com:443
        auth:
          authenticator: basicauth/client
        tls:
          cert_file: /conf/certs/tls.crt
          key_file: /conf/certs/tls.key
          ca_file: /conf/certs/ca.crt
```
Server OTEL
```
receivers:
  otlp:
    protocols:
          grpc:
            max_recv_msg_size_mib: 32
            auth:
              authenticator: basicauth/server
            tls:
              cert_file: /conf/certs/tls.crt
              key_file: /conf/certs/tls.key
              client_ca_file: /conf/certs/ca.crt
```
Service
```
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: "h2c"
    traefik.ingress.kubernetes.io/service.passhostheader: "false"
```
Ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - "example.com"
      secretName: "example-ingress"
  rules:
    - host: "example.com"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: example-otel
                port:
                  number: 4317
```
Then I started grpc test with the configuration above. Like https, the Client got `Permanent error: rpc error: code = Unknown desc = unexpected HTTP status code received from server: 500 (Internal Server Error); transport: received unexpected content-type \"text/plain; charset=utf-8\"`, and nothing on the Server side.

Then delete `client_ca_file: /conf/certs/ca.crt`. The Client gets a 502 (Bad Gateway) error message followed by the 500 error message seen above.

I certainly need a lot helps here.

**Comment by frzifus** [comment]
> would we have an implementation for Routes in Openshift scenario?

@yuriolisa yes, Depending on the selected type, an ingress or route entry should be created.

> Looks like Kubernetes already has all types for ingress. Can we just reuse it in your implementation?

@sergeyshevch Do you mean we should embed `networkingv1.Ingress` in the CRD? In my opinion, this would be equivalent to no CRD entry. It does not simplify the exposing of a collector. Also, the automatic setting/overwriting of e.g. service names and ports could lead to confusion.

> Also, It will be better to have annotations as map[string]string. For example in AWS ingress controller i have 8-10 different annotations per ingress

Sounds ligitimate. I don't have a strong opinion on that.

> Can someone summarize the current status regarding what's supported and what's not? 

Hi @PengWang-SMARTM, the goal is to simplify exactly this point. A desirable end result would be to configure a hostname, routing types, annotations and tls in the OTEL-collector CRD. Then the collector should be reachable from outside a cluster.

Currently I am trying to figure out how to expose different receivers in an elegant way. One consideration would be to route the various receiver endpoints via the URL. 

A translation would look like this:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
  otlp/2:
    protocols:
      http:
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
```
Configured hostname: `example.com`, should lead to addresses like:
```
example.com/otlp/grpc
example.com/otlp-2/http
example.com/jaeger/grpc
example.com/jaeger/thrift_binary
example.com/jaeger/thrift_compact
```

This way, however, it would be difficult to allow different TLS configurations for different collectors. What are your thoughts? @yuriolisa @pavolloffay and all the others?

---
Regarding the issue you faced with exposing the collector:

> I started with the configuration above. The client otel got 502 errors, and the server otel said the client did not provide a certificate.

I don't really have experience with traefik, but can it be that you need to enable tls passthrough? It seems that the tls certificate is no longer present, that traefik has already removed it. In the setup described in the blogpost I had the same problem and only had a tls connection up to the nginx proxy.

**Comment by PengWang-SMARTM** [comment]
@frzifus , I'm new to Kubernetes, and I haven't got a chance to learn how to use CRD yet. Since I have a working otlphttp connection, I'll come back to the otlp grpc connection later time.

Regarding the grpc configuration mentioned in your blog, I suspect `endpoint: "<REPLACE: your domain endpoint, e.g.: "traces.example.com:443">"` won't be enough.

That's because, from Ingress point of view, like routing http(s), it needs something to distinguish the target pod:port so it knows where to forward the incoming requests from port 443. Unless only one grpc routing is allowed through Ingress, there has to be something like the path for http, or each target pod:port needs a unique port number.

**Comment by frzifus** [comment]
> That's because, from Ingress point of view, like routing http(s), it needs something to distinguish the target pod:port so it knows where to forward the incoming requests from port 443. Unless only one grpc routing is allowed through Ingress, there has to be something like the path for http (or subdomain), or each target pod:port needs a unique port number.

In the example case it is specified in a ingress rule:
```yaml
  rules:
  - host: <REPLACE: your domain endpoint, e.g.: "traces@example.com">
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: otel-collector-app-collector
            port:
              number: 4317    
```
There you can map different paths to different service port numbers. 

Since [v0.61.0](https://github.com/open-telemetry/opentelemetry-operator/blob/main/CHANGELOG.md#-new-components-) there is an Ingress entry in the CRD. Based on the specified ports and collectors, rules for routing the traffics are automatically created. 

Example:
```bash
$ kubectl apply -f tests/e2e/ingress/00-install.yaml

$ kubectl describe ingress
...
Rules:
  Host         Path  Backends
  ----         ----  --------
  example.com  
               /otlp-grpc          simplest-collector:otlp-grpc (10.244.0.15:4317)
               /otlp-http          simplest-collector:otlp-http (10.244.0.15:4318)
...
```

---

Currently I am working on OpenShift route support and came across the [ingress-to-route controller](https://github.com/openshift/route-controller-manager/tree/a8d57986cd6ae78322d1449669e30f8f655a1435#ingress-to-route-controller)[[method](https://github.com/openshift/route-controller-manager/blob/c232643fbc47d167030d3ec7f3ea9b6b92ac20d2/pkg/route/ingress/ingress.go#L415)]. What do you think, would it make senes to expose the `IngressClass` field and simply link to the documentation that configuring [openshift.io/ingress-to-route](https://github.com/openshift/api/blob/013a7b8bf9b3d57d0642b8f14122f881635ed5a3/route/v1/types.go#L339-L345) as classname does the job? It would be nice and simple. But it seems that this controller is not pre-installed.

**Comment by fredthomsen** [comment]
How are people actually leveraging the ingress to get data into a OTEL collector running in a cluster now?
* You cannot add any path information to receiver endpoints in the CRD config ie `0.0.0.0:4318` is valid, but setting `0.0.0.0:4318/otlp-http/` is not.
* The ingress reconciliation process doesn't seem to account for the fact that these paths (like `otlp-http` in the example above) are not removed by the ingress and require something like URL rewrite to be setup
* The limited configuration of the ingress exposed by the CRD doesn't allow the above two issues to be resolved via changing the ingress config.
What am I missing here and how are people dealing with the above?

**Comment by wizardist** [comment]
@fredthomsen this is not quite clear.

By default, the operator will use `ruleType: prefix`, and it will create prefix rules for the ingress. It's much more involved to support these prefixes in either _Collector_ or _SDKs,_ although it seems that at least the Collector received some work to support prefixes in the OTLP HTTP receiver. Not sure about gRPC.

Short of adding support to receivers, exporters and SDKs, you can utilize `ruleType: subdomain` if that works for you.

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otlc-main
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
    processors:
    exporters:
      debug:
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [debug]
  ingress:
    type: ingress
    ruleType: subdomain
    annotations:
      cert-manager.io/cluster-issuer: lets-encrypt # Replace with your issuer
      nginx.ingress.kubernetes.io/backend-protocol: GRPC
    ingressClassName: public
    hostname: 'otlc.example.org'
    tls:
      - hosts:
          - 'otlp-grpc.otlc.example.org'
        secretName: otlc-main-ingress-tls

```

`otlc.example.org` will be used as the higher-level domain for each of the exposed ports for receivers.

```
$ kubectl describe service otlc-main-collector
Name:              otlc-main-collector
IP:                10.152.183.207
Port:              otlp-grpc  4317/TCP
TargetPort:        4317/TCP
Endpoints:         10.1.27.137:4317
```

The ingress will be created as follows:

```
$ kubectl describe ingress otlc-main-ingress
Name:             otlc-main-ingress
Address:          127.0.0.1
Ingress Class:    public
Default backend:  <default>
TLS:
  otlc-main-ingress-tls terminates otlp-grpc.otlc.example.org
Rules:
  Host                                            Path  Backends
  ----                                            ----  --------
  otlp-grpc.otlc.example.org
                                                  /   otlc-main-collector:otlp-grpc (10.1.27.137:4317)
Annotations:                                      cert-manager.io/cluster-issuer: lets-encrypt
                                                  nginx.ingress.kubernetes.io/backend-protocol: GRPC
Events:                                           <none>
```

Obviously, this is a ClusterIP service with pretty much out-of-box configuration, so you'd be defining the endpoint as `https://otlp-grpc.otlc.example.org:443`. It might be far from a production-worthy configuration, but relieves you from handling the custom path prefix configuration.
