### ISSUE TITLE
Multiple `OpenTelemetryCollector` resources in same namespaces cannot create sidecar container to pods created by deployment

### ISSUE THREAD

**Issue by trend-hong-chen** [open-telemetry/opentelemetry-operator#915]
When provision multiple `OpenTelemetryCollector` resources in same namespace, opentelemetry-operator-controller-manager pod will show `multiple OpenTelemetry Collect or instances available, cannot determine which one to select` error message.

In the [README](https://github.com/open-telemetry/opentelemetry-operator#sidecar-injection) mentioned that `When there are multiple OpenTelemetryCollector resources with a mode set to Sidecar in the same namespace, a concrete name should be used.`

What does the `concrete name` mean? Does `OpenTelemetryCollector` metadata.name need to be provided proper naming convention to match specific `Deployment`?

error message:

`
{"level":"error","ts":1654611376.2250822,"msg":"failed to select an OpenTelemetry Collector instance for this pod's sidecar","namespace":"","name":"","error":"multiple OpenTelemetry Collector instances available, cannot determine which one to select","stacktrace":"github.com/open-telemetry/opentelemetry-operator/internal/webhookhandler.(*podSidecarInjector).Handle\n\t/workspace/internal/webhookhandler/webhookhandler.go:92\nsigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/webhook/admission/webhook.go:146\nsigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/webhook/admission/http.go:99\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:40\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:101\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:76\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2462\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2916\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1966"}
`

manifest: 
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lab
  name: deploy-a
  labels:
    app: deploy-a
spec:
  ...
  selector:
    matchLabels:
      app: deploy-a
  template:
    metadata:
      labels:
        app: deploy-a
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
        ...
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  namespace: lab
  name: deploy-a
spec:
  mode: sidecar
  config: |
    receivers:
      jaeger:
        protocols:
          grpc:
    processors:
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: []
          exporters: [logging]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lab
  name: deploy-b
  labels:
    app: deploy-b
spec:
  ...
  selector:
    matchLabels:
      app: deploy-b
  template:
    metadata:
      labels:
        app: deploy-b
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
        ...
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  namespace: lab
  name: deploy-b
spec:
  mode: sidecar
  config: |
    receivers:
      jaeger:
        protocols:
          grpc:
    processors:
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: []
          exporters: [logging]

```
