### ISSUE TITLE
[target-allocator] `ServiceMonitor` must rely on an empty job

### ISSUE THREAD

**Issue by CoderPoet** [open-telemetry/opentelemetry-operator#963]
At present, when we use servicemonitor, we must set an empty job as a placeholder for config replace
eg:

```yaml
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: serviceMonitor/vke-system/harbor-server/0
```

<img width="660" alt="image" src="https://user-images.githubusercontent.com/19374680/177596833-09522c21-0b98-4b87-a9cc-f854bcbf6f5b.png">

servicemonitor is dynamically created, so there is no way to preset an empty job. Can we consider generating these scrape job configurations automatically?
