### ISSUE TITLE
[target-allocator] unknown fields "serviceAccount" and "prometheusCR" in io.opentelemetry.v1alpha1.OpenTelemetryCollector.spec.targetAllocator

### ISSUE THREAD

**Issue by moh-osman3** [open-telemetry/opentelemetry-operator#985]
Hey Otel folks!  I am opening this issue due to unrecognized fields when using the latest image version of the otel target-allocator in collector helm chart.

The error I'm seeing when running a helm upgrade

```
Error: UPGRADE FAILED: error validating "": error validating data:[
ValidationError(OpenTelemetryCollector.spec.targetAllocator): 
 unknown field "prometheusCR" in io.opentelemetry.v1alpha1.OpenTelemetryCollector.spec.targetAllocator, 
ValidationError(OpenTelemetryCollector.spec.targetAllocator):
 unknown field "serviceAccount" in io.opentelemetry.v1alpha1.OpenTelemetryCollector.spec.targetAllocator]
```

Which seems to point to invalid fields in my yaml file for the collector

```
spec:
  mode: {{ .Values.collector.mode }}
  image: {{ .Values.collector.image }}
  replicas: 3
  targetAllocator:
    enabled: true
    image: ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:latest
    serviceAccount: {{ .Release.Name }}-collector-targetallocator
    prometheusCR:
      enabled: true
```

For reference, the version of otel operator i am running
```
    image:
      repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
      tag: 0.55.0
```
Wondering if this means the changes made in this PR https://github.com/open-telemetry/opentelemetry-operator/pull/836 have not been picked up in the latest release of target-allocator image?  Or if there is a different cause for this issue? Thanks for your time!
