### ISSUE TITLE
Add support for hostAliases

### ISSUE THREAD

**Issue by Daklon** [open-telemetry/opentelemetry-operator#986]
I have an use case where i need to use the [HostAliases](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/) on the otelcol cr.

If I'm not wrong, after reviewing the [crd](https://github.com/open-telemetry/opentelemetry-operator/blob/main/apis/v1alpha1/opentelemetrycollector_types.go) this isn't currently supported by the operator.

Here is a proposal for it:
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  image: otel/opentelemetry-collector-contrib:0.55.0
  maxReplicas: 4
  serviceAccount: otel-collector-sa
  hostAliases:
    - ip: "127.0.0.1"
      hostnames:
        - "foo.local"
        - "bar.local"
    - ip: "10.1.2.3"
      hostnames:
        - "foo.remote"
        - "bar.remote"
  config: |
...
```

**Comment by pavolloffay** [comment]
@Daklon could you please describe your use-case?

**Comment by Daklon** [comment]
Yes, of course. I need to deploy open telemetry operator on a cluster where the dns resolution is not available for our kafka servers. The idea is to use kafka as exporter.
```yaml
exporters:
      kafka:
        protocol_version: 2.0.0
        brokers:
          - 172.0.0.1:9092
          - 172.0.0.2:9092
          - 172.0.0.3:9092
        topic: example-topic
```
I can set the ip address of the bootstrap server directly on the brokers list. The problem is that the bootstrap kafka server replies with a fqdn, not with an ip addresses, and the collector is unable to resolve them. We cannot change this behavior on our kafka servers since they are used on other applications. So I think the best approach here is to allow the spec to define the hostAliases for the created operator's generated pods.
